-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel is
generic (
    C_S_AXI_CONTROL_ADDR_WIDTH : INTEGER := 6;
    C_S_AXI_CONTROL_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_IN_R_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_IN_R_ID_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_IN_R_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_ADDR_WIDTH : INTEGER := 64;
    C_M_AXI_OUT_R_ID_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_AWUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_DATA_WIDTH : INTEGER := 32;
    C_M_AXI_OUT_R_WUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_ARUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_RUSER_WIDTH : INTEGER := 1;
    C_M_AXI_OUT_R_BUSER_WIDTH : INTEGER := 1;
    C_M_AXI_IN_R_USER_VALUE : INTEGER := 0;
    C_M_AXI_IN_R_PROT_VALUE : INTEGER := 0;
    C_M_AXI_IN_R_CACHE_VALUE : INTEGER := 3;
    C_M_AXI_OUT_R_USER_VALUE : INTEGER := 0;
    C_M_AXI_OUT_R_PROT_VALUE : INTEGER := 0;
    C_M_AXI_OUT_R_CACHE_VALUE : INTEGER := 3 );
port (
    s_axi_control_AWVALID : IN STD_LOGIC;
    s_axi_control_AWREADY : OUT STD_LOGIC;
    s_axi_control_AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_WVALID : IN STD_LOGIC;
    s_axi_control_WREADY : OUT STD_LOGIC;
    s_axi_control_WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH/8-1 downto 0);
    s_axi_control_ARVALID : IN STD_LOGIC;
    s_axi_control_ARREADY : OUT STD_LOGIC;
    s_axi_control_ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_CONTROL_ADDR_WIDTH-1 downto 0);
    s_axi_control_RVALID : OUT STD_LOGIC;
    s_axi_control_RREADY : IN STD_LOGIC;
    s_axi_control_RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_CONTROL_DATA_WIDTH-1 downto 0);
    s_axi_control_RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    s_axi_control_BVALID : OUT STD_LOGIC;
    s_axi_control_BREADY : IN STD_LOGIC;
    s_axi_control_BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    interrupt : OUT STD_LOGIC;
    m_axi_in_r_AWVALID : OUT STD_LOGIC;
    m_axi_in_r_AWREADY : IN STD_LOGIC;
    m_axi_in_r_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ADDR_WIDTH-1 downto 0);
    m_axi_in_r_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ID_WIDTH-1 downto 0);
    m_axi_in_r_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_AWUSER_WIDTH-1 downto 0);
    m_axi_in_r_WVALID : OUT STD_LOGIC;
    m_axi_in_r_WREADY : IN STD_LOGIC;
    m_axi_in_r_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_DATA_WIDTH-1 downto 0);
    m_axi_in_r_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_DATA_WIDTH/8-1 downto 0);
    m_axi_in_r_WLAST : OUT STD_LOGIC;
    m_axi_in_r_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ID_WIDTH-1 downto 0);
    m_axi_in_r_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_WUSER_WIDTH-1 downto 0);
    m_axi_in_r_ARVALID : OUT STD_LOGIC;
    m_axi_in_r_ARREADY : IN STD_LOGIC;
    m_axi_in_r_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ADDR_WIDTH-1 downto 0);
    m_axi_in_r_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ID_WIDTH-1 downto 0);
    m_axi_in_r_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_in_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_in_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_in_r_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_IN_R_ARUSER_WIDTH-1 downto 0);
    m_axi_in_r_RVALID : IN STD_LOGIC;
    m_axi_in_r_RREADY : OUT STD_LOGIC;
    m_axi_in_r_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_IN_R_DATA_WIDTH-1 downto 0);
    m_axi_in_r_RLAST : IN STD_LOGIC;
    m_axi_in_r_RID : IN STD_LOGIC_VECTOR (C_M_AXI_IN_R_ID_WIDTH-1 downto 0);
    m_axi_in_r_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN_R_RUSER_WIDTH-1 downto 0);
    m_axi_in_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_BVALID : IN STD_LOGIC;
    m_axi_in_r_BREADY : OUT STD_LOGIC;
    m_axi_in_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_in_r_BID : IN STD_LOGIC_VECTOR (C_M_AXI_IN_R_ID_WIDTH-1 downto 0);
    m_axi_in_r_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_IN_R_BUSER_WIDTH-1 downto 0);
    m_axi_out_r_AWVALID : OUT STD_LOGIC;
    m_axi_out_r_AWREADY : IN STD_LOGIC;
    m_axi_out_r_AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ADDR_WIDTH-1 downto 0);
    m_axi_out_r_AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_r_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_AWUSER_WIDTH-1 downto 0);
    m_axi_out_r_WVALID : OUT STD_LOGIC;
    m_axi_out_r_WREADY : IN STD_LOGIC;
    m_axi_out_r_WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH-1 downto 0);
    m_axi_out_r_WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH/8-1 downto 0);
    m_axi_out_r_WLAST : OUT STD_LOGIC;
    m_axi_out_r_WID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_WUSER_WIDTH-1 downto 0);
    m_axi_out_r_ARVALID : OUT STD_LOGIC;
    m_axi_out_r_ARREADY : IN STD_LOGIC;
    m_axi_out_r_ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ADDR_WIDTH-1 downto 0);
    m_axi_out_r_ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
    m_axi_out_r_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ARUSER_WIDTH-1 downto 0);
    m_axi_out_r_RVALID : IN STD_LOGIC;
    m_axi_out_r_RREADY : OUT STD_LOGIC;
    m_axi_out_r_RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_DATA_WIDTH-1 downto 0);
    m_axi_out_r_RLAST : IN STD_LOGIC;
    m_axi_out_r_RID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_RUSER_WIDTH-1 downto 0);
    m_axi_out_r_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_BVALID : IN STD_LOGIC;
    m_axi_out_r_BREADY : OUT STD_LOGIC;
    m_axi_out_r_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_BID : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_ID_WIDTH-1 downto 0);
    m_axi_out_r_BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_OUT_R_BUSER_WIDTH-1 downto 0) );
end;


architecture behav of top_kernel is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=65614,HLS_SYN_TPT=65536,HLS_SYN_MEM=4,HLS_SYN_DSP=0,HLS_SYN_FF=8323,HLS_SYN_LUT=9095,HLS_VERSION=2025_1_1}";
    constant C_S_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant C_M_AXI_DATA_WIDTH : INTEGER := 32;
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_rst_n_inv : STD_LOGIC;
    signal in_r_r : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_r : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_start : STD_LOGIC;
    signal ap_ready : STD_LOGIC;
    signal ap_done : STD_LOGIC;
    signal ap_idle : STD_LOGIC;
    signal in_r_0_AWREADY : STD_LOGIC;
    signal in_r_0_WREADY : STD_LOGIC;
    signal in_r_0_ARREADY : STD_LOGIC;
    signal in_r_0_RVALID : STD_LOGIC;
    signal in_r_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal in_r_0_RLAST : STD_LOGIC;
    signal in_r_0_RID : STD_LOGIC_VECTOR (0 downto 0);
    signal in_r_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal in_r_0_RUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal in_r_0_RRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal in_r_0_BVALID : STD_LOGIC;
    signal out_r_0_AWREADY : STD_LOGIC;
    signal out_r_0_WREADY : STD_LOGIC;
    signal out_r_0_ARREADY : STD_LOGIC;
    signal out_r_0_RVALID : STD_LOGIC;
    signal out_r_0_RDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal out_r_0_RFIFONUM : STD_LOGIC_VECTOR (8 downto 0);
    signal out_r_0_BVALID : STD_LOGIC;
    signal out_r_0_BRESP : STD_LOGIC_VECTOR (1 downto 0);
    signal out_r_0_BID : STD_LOGIC_VECTOR (0 downto 0);
    signal out_r_0_BUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal entry_proc_U0_ap_start : STD_LOGIC;
    signal entry_proc_U0_ap_done : STD_LOGIC;
    signal entry_proc_U0_ap_continue : STD_LOGIC;
    signal entry_proc_U0_ap_idle : STD_LOGIC;
    signal entry_proc_U0_ap_ready : STD_LOGIC;
    signal entry_proc_U0_start_out : STD_LOGIC;
    signal entry_proc_U0_start_write : STD_LOGIC;
    signal entry_proc_U0_out_r_r_c_din : STD_LOGIC_VECTOR (63 downto 0);
    signal entry_proc_U0_out_r_r_c_write : STD_LOGIC;
    signal K0_U0_ap_start : STD_LOGIC;
    signal K0_U0_start_full_n : STD_LOGIC;
    signal K0_U0_ap_done : STD_LOGIC;
    signal K0_U0_ap_continue : STD_LOGIC;
    signal K0_U0_ap_idle : STD_LOGIC;
    signal K0_U0_ap_ready : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_AWVALID : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal K0_U0_m_axi_in_r_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal K0_U0_m_axi_in_r_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal K0_U0_m_axi_in_r_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal K0_U0_m_axi_in_r_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal K0_U0_m_axi_in_r_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal K0_U0_m_axi_in_r_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_WVALID : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal K0_U0_m_axi_in_r_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_WLAST : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_ARVALID : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal K0_U0_m_axi_in_r_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal K0_U0_m_axi_in_r_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal K0_U0_m_axi_in_r_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal K0_U0_m_axi_in_r_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal K0_U0_m_axi_in_r_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal K0_U0_m_axi_in_r_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal K0_U0_m_axi_in_r_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K0_U0_m_axi_in_r_0_RREADY : STD_LOGIC;
    signal K0_U0_m_axi_in_r_0_BREADY : STD_LOGIC;
    signal K0_U0_s0_to_k1_din : STD_LOGIC_VECTOR (31 downto 0);
    signal K0_U0_s0_to_k1_write : STD_LOGIC;
    signal K0_U0_s0_to_k2_din : STD_LOGIC_VECTOR (31 downto 0);
    signal K0_U0_s0_to_k2_write : STD_LOGIC;
    signal K0_U0_start_out : STD_LOGIC;
    signal K0_U0_start_write : STD_LOGIC;
    signal K1_U0_ap_start : STD_LOGIC;
    signal K1_U0_ap_done : STD_LOGIC;
    signal K1_U0_ap_continue : STD_LOGIC;
    signal K1_U0_ap_idle : STD_LOGIC;
    signal K1_U0_ap_ready : STD_LOGIC;
    signal K1_U0_s0_to_k1_read : STD_LOGIC;
    signal K1_U0_s1_to_k3_din : STD_LOGIC_VECTOR (31 downto 0);
    signal K1_U0_s1_to_k3_write : STD_LOGIC;
    signal K1_U0_s1_to_k3_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal K1_U0_s1_to_k3_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal K1_U0_start_out : STD_LOGIC;
    signal K1_U0_start_write : STD_LOGIC;
    signal K2_U0_ap_start : STD_LOGIC;
    signal K2_U0_ap_done : STD_LOGIC;
    signal K2_U0_ap_continue : STD_LOGIC;
    signal K2_U0_ap_idle : STD_LOGIC;
    signal K2_U0_ap_ready : STD_LOGIC;
    signal K2_U0_s0_to_k2_read : STD_LOGIC;
    signal K2_U0_k2_to_k3_din : STD_LOGIC_VECTOR (31 downto 0);
    signal K2_U0_k2_to_k3_write : STD_LOGIC;
    signal K2_U0_k2_to_k3_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal K2_U0_k2_to_k3_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal K3_U0_ap_start : STD_LOGIC;
    signal K3_U0_ap_done : STD_LOGIC;
    signal K3_U0_ap_continue : STD_LOGIC;
    signal K3_U0_ap_idle : STD_LOGIC;
    signal K3_U0_ap_ready : STD_LOGIC;
    signal K3_U0_k2_to_k3_read : STD_LOGIC;
    signal K3_U0_s1_to_k3_read : STD_LOGIC;
    signal K3_U0_s3_to_k4_din : STD_LOGIC_VECTOR (31 downto 0);
    signal K3_U0_s3_to_k4_write : STD_LOGIC;
    signal K3_U0_s3_to_k4_num_data_valid : STD_LOGIC_VECTOR (31 downto 0);
    signal K3_U0_s3_to_k4_fifo_cap : STD_LOGIC_VECTOR (31 downto 0);
    signal K4_U0_ap_start : STD_LOGIC;
    signal K4_U0_ap_done : STD_LOGIC;
    signal K4_U0_ap_continue : STD_LOGIC;
    signal K4_U0_ap_idle : STD_LOGIC;
    signal K4_U0_ap_ready : STD_LOGIC;
    signal K4_U0_out_r_r_read : STD_LOGIC;
    signal K4_U0_s3_to_k4_read : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_AWVALID : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_AWADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal K4_U0_m_axi_out_r_0_AWID : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_AWLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal K4_U0_m_axi_out_r_0_AWSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal K4_U0_m_axi_out_r_0_AWBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal K4_U0_m_axi_out_r_0_AWLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal K4_U0_m_axi_out_r_0_AWCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_AWPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal K4_U0_m_axi_out_r_0_AWQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_AWREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_AWUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_WVALID : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_WDATA : STD_LOGIC_VECTOR (31 downto 0);
    signal K4_U0_m_axi_out_r_0_WSTRB : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_WLAST : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_WID : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_WUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_ARVALID : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_ARADDR : STD_LOGIC_VECTOR (63 downto 0);
    signal K4_U0_m_axi_out_r_0_ARID : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_ARLEN : STD_LOGIC_VECTOR (31 downto 0);
    signal K4_U0_m_axi_out_r_0_ARSIZE : STD_LOGIC_VECTOR (2 downto 0);
    signal K4_U0_m_axi_out_r_0_ARBURST : STD_LOGIC_VECTOR (1 downto 0);
    signal K4_U0_m_axi_out_r_0_ARLOCK : STD_LOGIC_VECTOR (1 downto 0);
    signal K4_U0_m_axi_out_r_0_ARCACHE : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_ARPROT : STD_LOGIC_VECTOR (2 downto 0);
    signal K4_U0_m_axi_out_r_0_ARQOS : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_ARREGION : STD_LOGIC_VECTOR (3 downto 0);
    signal K4_U0_m_axi_out_r_0_ARUSER : STD_LOGIC_VECTOR (0 downto 0);
    signal K4_U0_m_axi_out_r_0_RREADY : STD_LOGIC;
    signal K4_U0_m_axi_out_r_0_BREADY : STD_LOGIC;
    signal out_r_r_c_full_n : STD_LOGIC;
    signal out_r_r_c_dout : STD_LOGIC_VECTOR (63 downto 0);
    signal out_r_r_c_empty_n : STD_LOGIC;
    signal out_r_r_c_num_data_valid : STD_LOGIC_VECTOR (3 downto 0);
    signal out_r_r_c_fifo_cap : STD_LOGIC_VECTOR (3 downto 0);
    signal s0_to_k1_full_n : STD_LOGIC;
    signal s0_to_k1_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s0_to_k1_empty_n : STD_LOGIC;
    signal s0_to_k1_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_to_k1_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_to_k2_full_n : STD_LOGIC;
    signal s0_to_k2_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s0_to_k2_empty_n : STD_LOGIC;
    signal s0_to_k2_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal s0_to_k2_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal s1_to_k3_full_n : STD_LOGIC;
    signal s1_to_k3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s1_to_k3_empty_n : STD_LOGIC;
    signal s1_to_k3_num_data_valid : STD_LOGIC_VECTOR (9 downto 0);
    signal s1_to_k3_fifo_cap : STD_LOGIC_VECTOR (9 downto 0);
    signal k2_to_k3_full_n : STD_LOGIC;
    signal k2_to_k3_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal k2_to_k3_empty_n : STD_LOGIC;
    signal k2_to_k3_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal k2_to_k3_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_to_k4_full_n : STD_LOGIC;
    signal s3_to_k4_dout : STD_LOGIC_VECTOR (31 downto 0);
    signal s3_to_k4_empty_n : STD_LOGIC;
    signal s3_to_k4_num_data_valid : STD_LOGIC_VECTOR (2 downto 0);
    signal s3_to_k4_fifo_cap : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sync_ready : STD_LOGIC;
    signal ap_sync_reg_entry_proc_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_entry_proc_U0_ap_ready : STD_LOGIC;
    signal ap_sync_reg_K0_U0_ap_ready : STD_LOGIC := '0';
    signal ap_sync_K0_U0_ap_ready : STD_LOGIC;
    signal start_for_K4_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K4_U0_full_n : STD_LOGIC;
    signal start_for_K4_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K4_U0_empty_n : STD_LOGIC;
    signal start_for_K1_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K1_U0_full_n : STD_LOGIC;
    signal start_for_K1_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K1_U0_empty_n : STD_LOGIC;
    signal start_for_K2_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K2_U0_full_n : STD_LOGIC;
    signal start_for_K2_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K2_U0_empty_n : STD_LOGIC;
    signal start_for_K3_U0_din : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K3_U0_full_n : STD_LOGIC;
    signal start_for_K3_U0_dout : STD_LOGIC_VECTOR (0 downto 0);
    signal start_for_K3_U0_empty_n : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_entry_proc IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        out_r_r : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_r_c_din : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r_r_c_full_n : IN STD_LOGIC;
        out_r_r_c_write : OUT STD_LOGIC;
        out_r_r_c_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        out_r_r_c_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component top_kernel_K0 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        m_axi_in_r_0_AWVALID : OUT STD_LOGIC;
        m_axi_in_r_0_AWREADY : IN STD_LOGIC;
        m_axi_in_r_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_r_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_r_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_r_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_r_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_WVALID : OUT STD_LOGIC;
        m_axi_in_r_0_WREADY : IN STD_LOGIC;
        m_axi_in_r_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_r_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_WLAST : OUT STD_LOGIC;
        m_axi_in_r_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_ARVALID : OUT STD_LOGIC;
        m_axi_in_r_0_ARREADY : IN STD_LOGIC;
        m_axi_in_r_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_in_r_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_r_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_r_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_in_r_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_in_r_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_RVALID : IN STD_LOGIC;
        m_axi_in_r_0_RREADY : OUT STD_LOGIC;
        m_axi_in_r_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_in_r_0_RLAST : IN STD_LOGIC;
        m_axi_in_r_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_in_r_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_BVALID : IN STD_LOGIC;
        m_axi_in_r_0_BREADY : OUT STD_LOGIC;
        m_axi_in_r_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_in_r_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_in_r_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        s0_to_k1_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s0_to_k1_full_n : IN STD_LOGIC;
        s0_to_k1_write : OUT STD_LOGIC;
        s0_to_k1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s0_to_k1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        s0_to_k2_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s0_to_k2_full_n : IN STD_LOGIC;
        s0_to_k2_write : OUT STD_LOGIC;
        s0_to_k2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s0_to_k2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC;
        in_r_r : IN STD_LOGIC_VECTOR (63 downto 0) );
    end component;


    component top_kernel_K1 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        start_full_n : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s0_to_k1_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s0_to_k1_empty_n : IN STD_LOGIC;
        s0_to_k1_read : OUT STD_LOGIC;
        s0_to_k1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s0_to_k1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        s1_to_k3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s1_to_k3_full_n : IN STD_LOGIC;
        s1_to_k3_write : OUT STD_LOGIC;
        s1_to_k3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        s1_to_k3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0);
        start_out : OUT STD_LOGIC;
        start_write : OUT STD_LOGIC );
    end component;


    component top_kernel_K2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        s0_to_k2_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s0_to_k2_empty_n : IN STD_LOGIC;
        s0_to_k2_read : OUT STD_LOGIC;
        s0_to_k2_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s0_to_k2_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        k2_to_k3_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        k2_to_k3_full_n : IN STD_LOGIC;
        k2_to_k3_write : OUT STD_LOGIC;
        k2_to_k3_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        k2_to_k3_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_kernel_K3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        k2_to_k3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        k2_to_k3_empty_n : IN STD_LOGIC;
        k2_to_k3_read : OUT STD_LOGIC;
        k2_to_k3_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        k2_to_k3_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        s1_to_k3_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s1_to_k3_empty_n : IN STD_LOGIC;
        s1_to_k3_read : OUT STD_LOGIC;
        s1_to_k3_num_data_valid : IN STD_LOGIC_VECTOR (9 downto 0);
        s1_to_k3_fifo_cap : IN STD_LOGIC_VECTOR (9 downto 0);
        s3_to_k4_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        s3_to_k4_full_n : IN STD_LOGIC;
        s3_to_k4_write : OUT STD_LOGIC;
        s3_to_k4_num_data_valid : IN STD_LOGIC_VECTOR (31 downto 0);
        s3_to_k4_fifo_cap : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component top_kernel_K4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        out_r_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
        out_r_r_empty_n : IN STD_LOGIC;
        out_r_r_read : OUT STD_LOGIC;
        out_r_r_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
        out_r_r_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
        s3_to_k4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        s3_to_k4_empty_n : IN STD_LOGIC;
        s3_to_k4_read : OUT STD_LOGIC;
        s3_to_k4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        s3_to_k4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_AWVALID : OUT STD_LOGIC;
        m_axi_out_r_0_AWREADY : IN STD_LOGIC;
        m_axi_out_r_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_WVALID : OUT STD_LOGIC;
        m_axi_out_r_0_WREADY : IN STD_LOGIC;
        m_axi_out_r_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_WLAST : OUT STD_LOGIC;
        m_axi_out_r_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_ARVALID : OUT STD_LOGIC;
        m_axi_out_r_0_ARREADY : IN STD_LOGIC;
        m_axi_out_r_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
        m_axi_out_r_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        m_axi_out_r_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        m_axi_out_r_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RVALID : IN STD_LOGIC;
        m_axi_out_r_0_RREADY : OUT STD_LOGIC;
        m_axi_out_r_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        m_axi_out_r_0_RLAST : IN STD_LOGIC;
        m_axi_out_r_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
        m_axi_out_r_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_BVALID : IN STD_LOGIC;
        m_axi_out_r_0_BREADY : OUT STD_LOGIC;
        m_axi_out_r_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        m_axi_out_r_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
        m_axi_out_r_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0) );
    end component;


    component top_kernel_fifo_w64_d5_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (63 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (63 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (3 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component top_kernel_fifo_w32_d2_S IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (2 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (2 downto 0) );
    end component;


    component top_kernel_fifo_w32_d512_A IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (31 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (31 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC;
        if_num_data_valid : OUT STD_LOGIC_VECTOR (9 downto 0);
        if_fifo_cap : OUT STD_LOGIC_VECTOR (9 downto 0) );
    end component;


    component top_kernel_start_for_K4_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component top_kernel_start_for_K1_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component top_kernel_start_for_K2_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component top_kernel_start_for_K3_U0 IS
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        if_read_ce : IN STD_LOGIC;
        if_write_ce : IN STD_LOGIC;
        if_din : IN STD_LOGIC_VECTOR (0 downto 0);
        if_full_n : OUT STD_LOGIC;
        if_write : IN STD_LOGIC;
        if_dout : OUT STD_LOGIC_VECTOR (0 downto 0);
        if_empty_n : OUT STD_LOGIC;
        if_read : IN STD_LOGIC );
    end component;


    component top_kernel_control_s_axi IS
    generic (
        C_S_AXI_ADDR_WIDTH : INTEGER;
        C_S_AXI_DATA_WIDTH : INTEGER );
    port (
        AWVALID : IN STD_LOGIC;
        AWREADY : OUT STD_LOGIC;
        AWADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        WVALID : IN STD_LOGIC;
        WREADY : OUT STD_LOGIC;
        WDATA : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : IN STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH/8-1 downto 0);
        ARVALID : IN STD_LOGIC;
        ARREADY : OUT STD_LOGIC;
        ARADDR : IN STD_LOGIC_VECTOR (C_S_AXI_ADDR_WIDTH-1 downto 0);
        RVALID : OUT STD_LOGIC;
        RREADY : IN STD_LOGIC;
        RDATA : OUT STD_LOGIC_VECTOR (C_S_AXI_DATA_WIDTH-1 downto 0);
        RRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        BVALID : OUT STD_LOGIC;
        BREADY : IN STD_LOGIC;
        BRESP : OUT STD_LOGIC_VECTOR (1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        in_r_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        out_r_r : OUT STD_LOGIC_VECTOR (63 downto 0);
        ap_start : OUT STD_LOGIC;
        interrupt : OUT STD_LOGIC;
        ap_ready : IN STD_LOGIC;
        ap_done : IN STD_LOGIC;
        ap_idle : IN STD_LOGIC );
    end component;


    component top_kernel_in_r_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;


    component top_kernel_out_r_m_axi IS
    generic (
        CONSERVATIVE : INTEGER;
        USER_MAXREQS : INTEGER;
        MAX_READ_BURST_LENGTH : INTEGER;
        MAX_WRITE_BURST_LENGTH : INTEGER;
        C_M_AXI_ID_WIDTH : INTEGER;
        C_M_AXI_ADDR_WIDTH : INTEGER;
        C_M_AXI_DATA_WIDTH : INTEGER;
        C_M_AXI_AWUSER_WIDTH : INTEGER;
        C_M_AXI_ARUSER_WIDTH : INTEGER;
        C_M_AXI_WUSER_WIDTH : INTEGER;
        C_M_AXI_RUSER_WIDTH : INTEGER;
        C_M_AXI_BUSER_WIDTH : INTEGER;
        C_USER_VALUE : INTEGER;
        C_PROT_VALUE : INTEGER;
        C_CACHE_VALUE : INTEGER;
        CH0_NUM_READ_OUTSTANDING : INTEGER;
        CH0_NUM_WRITE_OUTSTANDING : INTEGER;
        CH0_USER_RFIFONUM_WIDTH : INTEGER;
        CH0_USER_DW : INTEGER;
        CH0_USER_AW : INTEGER;
        NUM_READ_OUTSTANDING : INTEGER;
        NUM_WRITE_OUTSTANDING : INTEGER );
    port (
        AWVALID : OUT STD_LOGIC;
        AWREADY : IN STD_LOGIC;
        AWADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        AWID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        AWLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        AWUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_AWUSER_WIDTH-1 downto 0);
        WVALID : OUT STD_LOGIC;
        WREADY : IN STD_LOGIC;
        WDATA : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        WSTRB : OUT STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH/8-1 downto 0);
        WLAST : OUT STD_LOGIC;
        WID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        WUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_WUSER_WIDTH-1 downto 0);
        ARVALID : OUT STD_LOGIC;
        ARREADY : IN STD_LOGIC;
        ARADDR : OUT STD_LOGIC_VECTOR (C_M_AXI_ADDR_WIDTH-1 downto 0);
        ARID : OUT STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        ARLEN : OUT STD_LOGIC_VECTOR (7 downto 0);
        ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
        ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
        ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
        ARUSER : OUT STD_LOGIC_VECTOR (C_M_AXI_ARUSER_WIDTH-1 downto 0);
        RVALID : IN STD_LOGIC;
        RREADY : OUT STD_LOGIC;
        RDATA : IN STD_LOGIC_VECTOR (C_M_AXI_DATA_WIDTH-1 downto 0);
        RLAST : IN STD_LOGIC;
        RID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        RUSER : IN STD_LOGIC_VECTOR (C_M_AXI_RUSER_WIDTH-1 downto 0);
        RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BVALID : IN STD_LOGIC;
        BREADY : OUT STD_LOGIC;
        BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
        BID : IN STD_LOGIC_VECTOR (C_M_AXI_ID_WIDTH-1 downto 0);
        BUSER : IN STD_LOGIC_VECTOR (C_M_AXI_BUSER_WIDTH-1 downto 0);
        ACLK : IN STD_LOGIC;
        ARESET : IN STD_LOGIC;
        ACLK_EN : IN STD_LOGIC;
        I_CH0_ARVALID : IN STD_LOGIC;
        I_CH0_ARREADY : OUT STD_LOGIC;
        I_CH0_ARADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_ARLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RVALID : OUT STD_LOGIC;
        I_CH0_RREADY : IN STD_LOGIC;
        I_CH0_RDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_RFIFONUM : OUT STD_LOGIC_VECTOR (8 downto 0);
        I_CH0_AWVALID : IN STD_LOGIC;
        I_CH0_AWREADY : OUT STD_LOGIC;
        I_CH0_AWADDR : IN STD_LOGIC_VECTOR (63 downto 0);
        I_CH0_AWLEN : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WVALID : IN STD_LOGIC;
        I_CH0_WREADY : OUT STD_LOGIC;
        I_CH0_WDATA : IN STD_LOGIC_VECTOR (31 downto 0);
        I_CH0_WSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
        I_CH0_BVALID : OUT STD_LOGIC;
        I_CH0_BREADY : IN STD_LOGIC );
    end component;



begin
    control_s_axi_U : component top_kernel_control_s_axi
    generic map (
        C_S_AXI_ADDR_WIDTH => C_S_AXI_CONTROL_ADDR_WIDTH,
        C_S_AXI_DATA_WIDTH => C_S_AXI_CONTROL_DATA_WIDTH)
    port map (
        AWVALID => s_axi_control_AWVALID,
        AWREADY => s_axi_control_AWREADY,
        AWADDR => s_axi_control_AWADDR,
        WVALID => s_axi_control_WVALID,
        WREADY => s_axi_control_WREADY,
        WDATA => s_axi_control_WDATA,
        WSTRB => s_axi_control_WSTRB,
        ARVALID => s_axi_control_ARVALID,
        ARREADY => s_axi_control_ARREADY,
        ARADDR => s_axi_control_ARADDR,
        RVALID => s_axi_control_RVALID,
        RREADY => s_axi_control_RREADY,
        RDATA => s_axi_control_RDATA,
        RRESP => s_axi_control_RRESP,
        BVALID => s_axi_control_BVALID,
        BREADY => s_axi_control_BREADY,
        BRESP => s_axi_control_BRESP,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        in_r_r => in_r_r,
        out_r_r => out_r_r,
        ap_start => ap_start,
        interrupt => interrupt,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_idle => ap_idle);

    in_r_m_axi_U : component top_kernel_in_r_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 7,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_IN_R_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_IN_R_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_IN_R_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_IN_R_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_IN_R_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_IN_R_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_IN_R_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_IN_R_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_IN_R_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_IN_R_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_IN_R_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 16,
        NUM_WRITE_OUTSTANDING => 0)
    port map (
        AWVALID => m_axi_in_r_AWVALID,
        AWREADY => m_axi_in_r_AWREADY,
        AWADDR => m_axi_in_r_AWADDR,
        AWID => m_axi_in_r_AWID,
        AWLEN => m_axi_in_r_AWLEN,
        AWSIZE => m_axi_in_r_AWSIZE,
        AWBURST => m_axi_in_r_AWBURST,
        AWLOCK => m_axi_in_r_AWLOCK,
        AWCACHE => m_axi_in_r_AWCACHE,
        AWPROT => m_axi_in_r_AWPROT,
        AWQOS => m_axi_in_r_AWQOS,
        AWREGION => m_axi_in_r_AWREGION,
        AWUSER => m_axi_in_r_AWUSER,
        WVALID => m_axi_in_r_WVALID,
        WREADY => m_axi_in_r_WREADY,
        WDATA => m_axi_in_r_WDATA,
        WSTRB => m_axi_in_r_WSTRB,
        WLAST => m_axi_in_r_WLAST,
        WID => m_axi_in_r_WID,
        WUSER => m_axi_in_r_WUSER,
        ARVALID => m_axi_in_r_ARVALID,
        ARREADY => m_axi_in_r_ARREADY,
        ARADDR => m_axi_in_r_ARADDR,
        ARID => m_axi_in_r_ARID,
        ARLEN => m_axi_in_r_ARLEN,
        ARSIZE => m_axi_in_r_ARSIZE,
        ARBURST => m_axi_in_r_ARBURST,
        ARLOCK => m_axi_in_r_ARLOCK,
        ARCACHE => m_axi_in_r_ARCACHE,
        ARPROT => m_axi_in_r_ARPROT,
        ARQOS => m_axi_in_r_ARQOS,
        ARREGION => m_axi_in_r_ARREGION,
        ARUSER => m_axi_in_r_ARUSER,
        RVALID => m_axi_in_r_RVALID,
        RREADY => m_axi_in_r_RREADY,
        RDATA => m_axi_in_r_RDATA,
        RLAST => m_axi_in_r_RLAST,
        RID => m_axi_in_r_RID,
        RUSER => m_axi_in_r_RUSER,
        RRESP => m_axi_in_r_RRESP,
        BVALID => m_axi_in_r_BVALID,
        BREADY => m_axi_in_r_BREADY,
        BRESP => m_axi_in_r_BRESP,
        BID => m_axi_in_r_BID,
        BUSER => m_axi_in_r_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => K0_U0_m_axi_in_r_0_ARVALID,
        I_CH0_ARREADY => in_r_0_ARREADY,
        I_CH0_ARADDR => K0_U0_m_axi_in_r_0_ARADDR,
        I_CH0_ARLEN => K0_U0_m_axi_in_r_0_ARLEN,
        I_CH0_RVALID => in_r_0_RVALID,
        I_CH0_RREADY => K0_U0_m_axi_in_r_0_RREADY,
        I_CH0_RDATA => in_r_0_RDATA,
        I_CH0_RFIFONUM => in_r_0_RFIFONUM,
        I_CH0_AWVALID => ap_const_logic_0,
        I_CH0_AWREADY => in_r_0_AWREADY,
        I_CH0_AWADDR => ap_const_lv64_0,
        I_CH0_AWLEN => ap_const_lv32_0,
        I_CH0_WVALID => ap_const_logic_0,
        I_CH0_WREADY => in_r_0_WREADY,
        I_CH0_WDATA => ap_const_lv32_0,
        I_CH0_WSTRB => ap_const_lv4_0,
        I_CH0_BVALID => in_r_0_BVALID,
        I_CH0_BREADY => ap_const_logic_0);

    out_r_m_axi_U : component top_kernel_out_r_m_axi
    generic map (
        CONSERVATIVE => 1,
        USER_MAXREQS => 4,
        MAX_READ_BURST_LENGTH => 16,
        MAX_WRITE_BURST_LENGTH => 16,
        C_M_AXI_ID_WIDTH => C_M_AXI_OUT_R_ID_WIDTH,
        C_M_AXI_ADDR_WIDTH => C_M_AXI_OUT_R_ADDR_WIDTH,
        C_M_AXI_DATA_WIDTH => C_M_AXI_OUT_R_DATA_WIDTH,
        C_M_AXI_AWUSER_WIDTH => C_M_AXI_OUT_R_AWUSER_WIDTH,
        C_M_AXI_ARUSER_WIDTH => C_M_AXI_OUT_R_ARUSER_WIDTH,
        C_M_AXI_WUSER_WIDTH => C_M_AXI_OUT_R_WUSER_WIDTH,
        C_M_AXI_RUSER_WIDTH => C_M_AXI_OUT_R_RUSER_WIDTH,
        C_M_AXI_BUSER_WIDTH => C_M_AXI_OUT_R_BUSER_WIDTH,
        C_USER_VALUE => C_M_AXI_OUT_R_USER_VALUE,
        C_PROT_VALUE => C_M_AXI_OUT_R_PROT_VALUE,
        C_CACHE_VALUE => C_M_AXI_OUT_R_CACHE_VALUE,
        CH0_NUM_READ_OUTSTANDING => 16,
        CH0_NUM_WRITE_OUTSTANDING => 16,
        CH0_USER_RFIFONUM_WIDTH => 9,
        CH0_USER_DW => 32,
        CH0_USER_AW => 64,
        NUM_READ_OUTSTANDING => 0,
        NUM_WRITE_OUTSTANDING => 16)
    port map (
        AWVALID => m_axi_out_r_AWVALID,
        AWREADY => m_axi_out_r_AWREADY,
        AWADDR => m_axi_out_r_AWADDR,
        AWID => m_axi_out_r_AWID,
        AWLEN => m_axi_out_r_AWLEN,
        AWSIZE => m_axi_out_r_AWSIZE,
        AWBURST => m_axi_out_r_AWBURST,
        AWLOCK => m_axi_out_r_AWLOCK,
        AWCACHE => m_axi_out_r_AWCACHE,
        AWPROT => m_axi_out_r_AWPROT,
        AWQOS => m_axi_out_r_AWQOS,
        AWREGION => m_axi_out_r_AWREGION,
        AWUSER => m_axi_out_r_AWUSER,
        WVALID => m_axi_out_r_WVALID,
        WREADY => m_axi_out_r_WREADY,
        WDATA => m_axi_out_r_WDATA,
        WSTRB => m_axi_out_r_WSTRB,
        WLAST => m_axi_out_r_WLAST,
        WID => m_axi_out_r_WID,
        WUSER => m_axi_out_r_WUSER,
        ARVALID => m_axi_out_r_ARVALID,
        ARREADY => m_axi_out_r_ARREADY,
        ARADDR => m_axi_out_r_ARADDR,
        ARID => m_axi_out_r_ARID,
        ARLEN => m_axi_out_r_ARLEN,
        ARSIZE => m_axi_out_r_ARSIZE,
        ARBURST => m_axi_out_r_ARBURST,
        ARLOCK => m_axi_out_r_ARLOCK,
        ARCACHE => m_axi_out_r_ARCACHE,
        ARPROT => m_axi_out_r_ARPROT,
        ARQOS => m_axi_out_r_ARQOS,
        ARREGION => m_axi_out_r_ARREGION,
        ARUSER => m_axi_out_r_ARUSER,
        RVALID => m_axi_out_r_RVALID,
        RREADY => m_axi_out_r_RREADY,
        RDATA => m_axi_out_r_RDATA,
        RLAST => m_axi_out_r_RLAST,
        RID => m_axi_out_r_RID,
        RUSER => m_axi_out_r_RUSER,
        RRESP => m_axi_out_r_RRESP,
        BVALID => m_axi_out_r_BVALID,
        BREADY => m_axi_out_r_BREADY,
        BRESP => m_axi_out_r_BRESP,
        BID => m_axi_out_r_BID,
        BUSER => m_axi_out_r_BUSER,
        ACLK => ap_clk,
        ARESET => ap_rst_n_inv,
        ACLK_EN => ap_const_logic_1,
        I_CH0_ARVALID => ap_const_logic_0,
        I_CH0_ARREADY => out_r_0_ARREADY,
        I_CH0_ARADDR => ap_const_lv64_0,
        I_CH0_ARLEN => ap_const_lv32_0,
        I_CH0_RVALID => out_r_0_RVALID,
        I_CH0_RREADY => ap_const_logic_0,
        I_CH0_RDATA => out_r_0_RDATA,
        I_CH0_RFIFONUM => out_r_0_RFIFONUM,
        I_CH0_AWVALID => K4_U0_m_axi_out_r_0_AWVALID,
        I_CH0_AWREADY => out_r_0_AWREADY,
        I_CH0_AWADDR => K4_U0_m_axi_out_r_0_AWADDR,
        I_CH0_AWLEN => K4_U0_m_axi_out_r_0_AWLEN,
        I_CH0_WVALID => K4_U0_m_axi_out_r_0_WVALID,
        I_CH0_WREADY => out_r_0_WREADY,
        I_CH0_WDATA => K4_U0_m_axi_out_r_0_WDATA,
        I_CH0_WSTRB => K4_U0_m_axi_out_r_0_WSTRB,
        I_CH0_BVALID => out_r_0_BVALID,
        I_CH0_BREADY => K4_U0_m_axi_out_r_0_BREADY);

    entry_proc_U0 : component top_kernel_entry_proc
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => entry_proc_U0_ap_start,
        start_full_n => start_for_K4_U0_full_n,
        ap_done => entry_proc_U0_ap_done,
        ap_continue => entry_proc_U0_ap_continue,
        ap_idle => entry_proc_U0_ap_idle,
        ap_ready => entry_proc_U0_ap_ready,
        start_out => entry_proc_U0_start_out,
        start_write => entry_proc_U0_start_write,
        out_r_r => out_r_r,
        out_r_r_c_din => entry_proc_U0_out_r_r_c_din,
        out_r_r_c_full_n => out_r_r_c_full_n,
        out_r_r_c_write => entry_proc_U0_out_r_r_c_write,
        out_r_r_c_num_data_valid => out_r_r_c_num_data_valid,
        out_r_r_c_fifo_cap => out_r_r_c_fifo_cap);

    K0_U0 : component top_kernel_K0
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => K0_U0_ap_start,
        start_full_n => K0_U0_start_full_n,
        ap_done => K0_U0_ap_done,
        ap_continue => K0_U0_ap_continue,
        ap_idle => K0_U0_ap_idle,
        ap_ready => K0_U0_ap_ready,
        m_axi_in_r_0_AWVALID => K0_U0_m_axi_in_r_0_AWVALID,
        m_axi_in_r_0_AWREADY => ap_const_logic_0,
        m_axi_in_r_0_AWADDR => K0_U0_m_axi_in_r_0_AWADDR,
        m_axi_in_r_0_AWID => K0_U0_m_axi_in_r_0_AWID,
        m_axi_in_r_0_AWLEN => K0_U0_m_axi_in_r_0_AWLEN,
        m_axi_in_r_0_AWSIZE => K0_U0_m_axi_in_r_0_AWSIZE,
        m_axi_in_r_0_AWBURST => K0_U0_m_axi_in_r_0_AWBURST,
        m_axi_in_r_0_AWLOCK => K0_U0_m_axi_in_r_0_AWLOCK,
        m_axi_in_r_0_AWCACHE => K0_U0_m_axi_in_r_0_AWCACHE,
        m_axi_in_r_0_AWPROT => K0_U0_m_axi_in_r_0_AWPROT,
        m_axi_in_r_0_AWQOS => K0_U0_m_axi_in_r_0_AWQOS,
        m_axi_in_r_0_AWREGION => K0_U0_m_axi_in_r_0_AWREGION,
        m_axi_in_r_0_AWUSER => K0_U0_m_axi_in_r_0_AWUSER,
        m_axi_in_r_0_WVALID => K0_U0_m_axi_in_r_0_WVALID,
        m_axi_in_r_0_WREADY => ap_const_logic_0,
        m_axi_in_r_0_WDATA => K0_U0_m_axi_in_r_0_WDATA,
        m_axi_in_r_0_WSTRB => K0_U0_m_axi_in_r_0_WSTRB,
        m_axi_in_r_0_WLAST => K0_U0_m_axi_in_r_0_WLAST,
        m_axi_in_r_0_WID => K0_U0_m_axi_in_r_0_WID,
        m_axi_in_r_0_WUSER => K0_U0_m_axi_in_r_0_WUSER,
        m_axi_in_r_0_ARVALID => K0_U0_m_axi_in_r_0_ARVALID,
        m_axi_in_r_0_ARREADY => in_r_0_ARREADY,
        m_axi_in_r_0_ARADDR => K0_U0_m_axi_in_r_0_ARADDR,
        m_axi_in_r_0_ARID => K0_U0_m_axi_in_r_0_ARID,
        m_axi_in_r_0_ARLEN => K0_U0_m_axi_in_r_0_ARLEN,
        m_axi_in_r_0_ARSIZE => K0_U0_m_axi_in_r_0_ARSIZE,
        m_axi_in_r_0_ARBURST => K0_U0_m_axi_in_r_0_ARBURST,
        m_axi_in_r_0_ARLOCK => K0_U0_m_axi_in_r_0_ARLOCK,
        m_axi_in_r_0_ARCACHE => K0_U0_m_axi_in_r_0_ARCACHE,
        m_axi_in_r_0_ARPROT => K0_U0_m_axi_in_r_0_ARPROT,
        m_axi_in_r_0_ARQOS => K0_U0_m_axi_in_r_0_ARQOS,
        m_axi_in_r_0_ARREGION => K0_U0_m_axi_in_r_0_ARREGION,
        m_axi_in_r_0_ARUSER => K0_U0_m_axi_in_r_0_ARUSER,
        m_axi_in_r_0_RVALID => in_r_0_RVALID,
        m_axi_in_r_0_RREADY => K0_U0_m_axi_in_r_0_RREADY,
        m_axi_in_r_0_RDATA => in_r_0_RDATA,
        m_axi_in_r_0_RLAST => in_r_0_RLAST,
        m_axi_in_r_0_RID => in_r_0_RID,
        m_axi_in_r_0_RFIFONUM => in_r_0_RFIFONUM,
        m_axi_in_r_0_RUSER => in_r_0_RUSER,
        m_axi_in_r_0_RRESP => in_r_0_RRESP,
        m_axi_in_r_0_BVALID => ap_const_logic_0,
        m_axi_in_r_0_BREADY => K0_U0_m_axi_in_r_0_BREADY,
        m_axi_in_r_0_BRESP => ap_const_lv2_0,
        m_axi_in_r_0_BID => ap_const_lv1_0,
        m_axi_in_r_0_BUSER => ap_const_lv1_0,
        s0_to_k1_din => K0_U0_s0_to_k1_din,
        s0_to_k1_full_n => s0_to_k1_full_n,
        s0_to_k1_write => K0_U0_s0_to_k1_write,
        s0_to_k1_num_data_valid => s0_to_k1_num_data_valid,
        s0_to_k1_fifo_cap => s0_to_k1_fifo_cap,
        s0_to_k2_din => K0_U0_s0_to_k2_din,
        s0_to_k2_full_n => s0_to_k2_full_n,
        s0_to_k2_write => K0_U0_s0_to_k2_write,
        s0_to_k2_num_data_valid => s0_to_k2_num_data_valid,
        s0_to_k2_fifo_cap => s0_to_k2_fifo_cap,
        start_out => K0_U0_start_out,
        start_write => K0_U0_start_write,
        in_r_r => in_r_r);

    K1_U0 : component top_kernel_K1
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => K1_U0_ap_start,
        start_full_n => start_for_K3_U0_full_n,
        ap_done => K1_U0_ap_done,
        ap_continue => K1_U0_ap_continue,
        ap_idle => K1_U0_ap_idle,
        ap_ready => K1_U0_ap_ready,
        s0_to_k1_dout => s0_to_k1_dout,
        s0_to_k1_empty_n => s0_to_k1_empty_n,
        s0_to_k1_read => K1_U0_s0_to_k1_read,
        s0_to_k1_num_data_valid => s0_to_k1_num_data_valid,
        s0_to_k1_fifo_cap => s0_to_k1_fifo_cap,
        s1_to_k3_din => K1_U0_s1_to_k3_din,
        s1_to_k3_full_n => s1_to_k3_full_n,
        s1_to_k3_write => K1_U0_s1_to_k3_write,
        s1_to_k3_num_data_valid => K1_U0_s1_to_k3_num_data_valid,
        s1_to_k3_fifo_cap => K1_U0_s1_to_k3_fifo_cap,
        start_out => K1_U0_start_out,
        start_write => K1_U0_start_write);

    K2_U0 : component top_kernel_K2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => K2_U0_ap_start,
        ap_done => K2_U0_ap_done,
        ap_continue => K2_U0_ap_continue,
        ap_idle => K2_U0_ap_idle,
        ap_ready => K2_U0_ap_ready,
        s0_to_k2_dout => s0_to_k2_dout,
        s0_to_k2_empty_n => s0_to_k2_empty_n,
        s0_to_k2_read => K2_U0_s0_to_k2_read,
        s0_to_k2_num_data_valid => s0_to_k2_num_data_valid,
        s0_to_k2_fifo_cap => s0_to_k2_fifo_cap,
        k2_to_k3_din => K2_U0_k2_to_k3_din,
        k2_to_k3_full_n => k2_to_k3_full_n,
        k2_to_k3_write => K2_U0_k2_to_k3_write,
        k2_to_k3_num_data_valid => K2_U0_k2_to_k3_num_data_valid,
        k2_to_k3_fifo_cap => K2_U0_k2_to_k3_fifo_cap);

    K3_U0 : component top_kernel_K3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => K3_U0_ap_start,
        ap_done => K3_U0_ap_done,
        ap_continue => K3_U0_ap_continue,
        ap_idle => K3_U0_ap_idle,
        ap_ready => K3_U0_ap_ready,
        k2_to_k3_dout => k2_to_k3_dout,
        k2_to_k3_empty_n => k2_to_k3_empty_n,
        k2_to_k3_read => K3_U0_k2_to_k3_read,
        k2_to_k3_num_data_valid => k2_to_k3_num_data_valid,
        k2_to_k3_fifo_cap => k2_to_k3_fifo_cap,
        s1_to_k3_dout => s1_to_k3_dout,
        s1_to_k3_empty_n => s1_to_k3_empty_n,
        s1_to_k3_read => K3_U0_s1_to_k3_read,
        s1_to_k3_num_data_valid => s1_to_k3_num_data_valid,
        s1_to_k3_fifo_cap => s1_to_k3_fifo_cap,
        s3_to_k4_din => K3_U0_s3_to_k4_din,
        s3_to_k4_full_n => s3_to_k4_full_n,
        s3_to_k4_write => K3_U0_s3_to_k4_write,
        s3_to_k4_num_data_valid => K3_U0_s3_to_k4_num_data_valid,
        s3_to_k4_fifo_cap => K3_U0_s3_to_k4_fifo_cap);

    K4_U0 : component top_kernel_K4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => K4_U0_ap_start,
        ap_done => K4_U0_ap_done,
        ap_continue => K4_U0_ap_continue,
        ap_idle => K4_U0_ap_idle,
        ap_ready => K4_U0_ap_ready,
        out_r_r_dout => out_r_r_c_dout,
        out_r_r_empty_n => out_r_r_c_empty_n,
        out_r_r_read => K4_U0_out_r_r_read,
        out_r_r_num_data_valid => out_r_r_c_num_data_valid,
        out_r_r_fifo_cap => out_r_r_c_fifo_cap,
        s3_to_k4_dout => s3_to_k4_dout,
        s3_to_k4_empty_n => s3_to_k4_empty_n,
        s3_to_k4_read => K4_U0_s3_to_k4_read,
        s3_to_k4_num_data_valid => s3_to_k4_num_data_valid,
        s3_to_k4_fifo_cap => s3_to_k4_fifo_cap,
        m_axi_out_r_0_AWVALID => K4_U0_m_axi_out_r_0_AWVALID,
        m_axi_out_r_0_AWREADY => out_r_0_AWREADY,
        m_axi_out_r_0_AWADDR => K4_U0_m_axi_out_r_0_AWADDR,
        m_axi_out_r_0_AWID => K4_U0_m_axi_out_r_0_AWID,
        m_axi_out_r_0_AWLEN => K4_U0_m_axi_out_r_0_AWLEN,
        m_axi_out_r_0_AWSIZE => K4_U0_m_axi_out_r_0_AWSIZE,
        m_axi_out_r_0_AWBURST => K4_U0_m_axi_out_r_0_AWBURST,
        m_axi_out_r_0_AWLOCK => K4_U0_m_axi_out_r_0_AWLOCK,
        m_axi_out_r_0_AWCACHE => K4_U0_m_axi_out_r_0_AWCACHE,
        m_axi_out_r_0_AWPROT => K4_U0_m_axi_out_r_0_AWPROT,
        m_axi_out_r_0_AWQOS => K4_U0_m_axi_out_r_0_AWQOS,
        m_axi_out_r_0_AWREGION => K4_U0_m_axi_out_r_0_AWREGION,
        m_axi_out_r_0_AWUSER => K4_U0_m_axi_out_r_0_AWUSER,
        m_axi_out_r_0_WVALID => K4_U0_m_axi_out_r_0_WVALID,
        m_axi_out_r_0_WREADY => out_r_0_WREADY,
        m_axi_out_r_0_WDATA => K4_U0_m_axi_out_r_0_WDATA,
        m_axi_out_r_0_WSTRB => K4_U0_m_axi_out_r_0_WSTRB,
        m_axi_out_r_0_WLAST => K4_U0_m_axi_out_r_0_WLAST,
        m_axi_out_r_0_WID => K4_U0_m_axi_out_r_0_WID,
        m_axi_out_r_0_WUSER => K4_U0_m_axi_out_r_0_WUSER,
        m_axi_out_r_0_ARVALID => K4_U0_m_axi_out_r_0_ARVALID,
        m_axi_out_r_0_ARREADY => ap_const_logic_0,
        m_axi_out_r_0_ARADDR => K4_U0_m_axi_out_r_0_ARADDR,
        m_axi_out_r_0_ARID => K4_U0_m_axi_out_r_0_ARID,
        m_axi_out_r_0_ARLEN => K4_U0_m_axi_out_r_0_ARLEN,
        m_axi_out_r_0_ARSIZE => K4_U0_m_axi_out_r_0_ARSIZE,
        m_axi_out_r_0_ARBURST => K4_U0_m_axi_out_r_0_ARBURST,
        m_axi_out_r_0_ARLOCK => K4_U0_m_axi_out_r_0_ARLOCK,
        m_axi_out_r_0_ARCACHE => K4_U0_m_axi_out_r_0_ARCACHE,
        m_axi_out_r_0_ARPROT => K4_U0_m_axi_out_r_0_ARPROT,
        m_axi_out_r_0_ARQOS => K4_U0_m_axi_out_r_0_ARQOS,
        m_axi_out_r_0_ARREGION => K4_U0_m_axi_out_r_0_ARREGION,
        m_axi_out_r_0_ARUSER => K4_U0_m_axi_out_r_0_ARUSER,
        m_axi_out_r_0_RVALID => ap_const_logic_0,
        m_axi_out_r_0_RREADY => K4_U0_m_axi_out_r_0_RREADY,
        m_axi_out_r_0_RDATA => ap_const_lv32_0,
        m_axi_out_r_0_RLAST => ap_const_logic_0,
        m_axi_out_r_0_RID => ap_const_lv1_0,
        m_axi_out_r_0_RFIFONUM => ap_const_lv9_0,
        m_axi_out_r_0_RUSER => ap_const_lv1_0,
        m_axi_out_r_0_RRESP => ap_const_lv2_0,
        m_axi_out_r_0_BVALID => out_r_0_BVALID,
        m_axi_out_r_0_BREADY => K4_U0_m_axi_out_r_0_BREADY,
        m_axi_out_r_0_BRESP => out_r_0_BRESP,
        m_axi_out_r_0_BID => out_r_0_BID,
        m_axi_out_r_0_BUSER => out_r_0_BUSER);

    out_r_r_c_U : component top_kernel_fifo_w64_d5_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => entry_proc_U0_out_r_r_c_din,
        if_full_n => out_r_r_c_full_n,
        if_write => entry_proc_U0_out_r_r_c_write,
        if_dout => out_r_r_c_dout,
        if_empty_n => out_r_r_c_empty_n,
        if_read => K4_U0_out_r_r_read,
        if_num_data_valid => out_r_r_c_num_data_valid,
        if_fifo_cap => out_r_r_c_fifo_cap);

    s0_to_k1_U : component top_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => K0_U0_s0_to_k1_din,
        if_full_n => s0_to_k1_full_n,
        if_write => K0_U0_s0_to_k1_write,
        if_dout => s0_to_k1_dout,
        if_empty_n => s0_to_k1_empty_n,
        if_read => K1_U0_s0_to_k1_read,
        if_num_data_valid => s0_to_k1_num_data_valid,
        if_fifo_cap => s0_to_k1_fifo_cap);

    s0_to_k2_U : component top_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => K0_U0_s0_to_k2_din,
        if_full_n => s0_to_k2_full_n,
        if_write => K0_U0_s0_to_k2_write,
        if_dout => s0_to_k2_dout,
        if_empty_n => s0_to_k2_empty_n,
        if_read => K2_U0_s0_to_k2_read,
        if_num_data_valid => s0_to_k2_num_data_valid,
        if_fifo_cap => s0_to_k2_fifo_cap);

    s1_to_k3_U : component top_kernel_fifo_w32_d512_A
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => K1_U0_s1_to_k3_din,
        if_full_n => s1_to_k3_full_n,
        if_write => K1_U0_s1_to_k3_write,
        if_dout => s1_to_k3_dout,
        if_empty_n => s1_to_k3_empty_n,
        if_read => K3_U0_s1_to_k3_read,
        if_num_data_valid => s1_to_k3_num_data_valid,
        if_fifo_cap => s1_to_k3_fifo_cap);

    k2_to_k3_U : component top_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => K2_U0_k2_to_k3_din,
        if_full_n => k2_to_k3_full_n,
        if_write => K2_U0_k2_to_k3_write,
        if_dout => k2_to_k3_dout,
        if_empty_n => k2_to_k3_empty_n,
        if_read => K3_U0_k2_to_k3_read,
        if_num_data_valid => k2_to_k3_num_data_valid,
        if_fifo_cap => k2_to_k3_fifo_cap);

    s3_to_k4_U : component top_kernel_fifo_w32_d2_S
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => K3_U0_s3_to_k4_din,
        if_full_n => s3_to_k4_full_n,
        if_write => K3_U0_s3_to_k4_write,
        if_dout => s3_to_k4_dout,
        if_empty_n => s3_to_k4_empty_n,
        if_read => K4_U0_s3_to_k4_read,
        if_num_data_valid => s3_to_k4_num_data_valid,
        if_fifo_cap => s3_to_k4_fifo_cap);

    start_for_K4_U0_U : component top_kernel_start_for_K4_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_K4_U0_din,
        if_full_n => start_for_K4_U0_full_n,
        if_write => entry_proc_U0_start_write,
        if_dout => start_for_K4_U0_dout,
        if_empty_n => start_for_K4_U0_empty_n,
        if_read => K4_U0_ap_ready);

    start_for_K1_U0_U : component top_kernel_start_for_K1_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_K1_U0_din,
        if_full_n => start_for_K1_U0_full_n,
        if_write => K0_U0_start_write,
        if_dout => start_for_K1_U0_dout,
        if_empty_n => start_for_K1_U0_empty_n,
        if_read => K1_U0_ap_ready);

    start_for_K2_U0_U : component top_kernel_start_for_K2_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_K2_U0_din,
        if_full_n => start_for_K2_U0_full_n,
        if_write => K0_U0_start_write,
        if_dout => start_for_K2_U0_dout,
        if_empty_n => start_for_K2_U0_empty_n,
        if_read => K2_U0_ap_ready);

    start_for_K3_U0_U : component top_kernel_start_for_K3_U0
    port map (
        clk => ap_clk,
        reset => ap_rst_n_inv,
        if_read_ce => ap_const_logic_1,
        if_write_ce => ap_const_logic_1,
        if_din => start_for_K3_U0_din,
        if_full_n => start_for_K3_U0_full_n,
        if_write => K1_U0_start_write,
        if_dout => start_for_K3_U0_dout,
        if_empty_n => start_for_K3_U0_empty_n,
        if_read => K3_U0_ap_ready);





    ap_sync_reg_K0_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_K0_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_K0_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_K0_U0_ap_ready <= ap_sync_K0_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;


    ap_sync_reg_entry_proc_U0_ap_ready_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
            else
                if (((ap_sync_ready and ap_start) = ap_const_logic_1)) then 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_const_logic_0;
                else 
                    ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
                end if; 
            end if;
        end if;
    end process;

    K0_U0_ap_continue <= ap_const_logic_1;
    K0_U0_ap_start <= ((ap_sync_reg_K0_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    K0_U0_start_full_n <= (start_for_K2_U0_full_n and start_for_K1_U0_full_n);
    K1_U0_ap_continue <= ap_const_logic_1;
    K1_U0_ap_start <= start_for_K1_U0_empty_n;
    K1_U0_s1_to_k3_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(s1_to_k3_fifo_cap),10))),32));
    K1_U0_s1_to_k3_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(s1_to_k3_num_data_valid),10))),32));
    K2_U0_ap_continue <= ap_const_logic_1;
    K2_U0_ap_start <= start_for_K2_U0_empty_n;
    K2_U0_k2_to_k3_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(k2_to_k3_fifo_cap),3))),32));
    K2_U0_k2_to_k3_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(k2_to_k3_num_data_valid),3))),32));
    K3_U0_ap_continue <= ap_const_logic_1;
    K3_U0_ap_start <= start_for_K3_U0_empty_n;
    K3_U0_s3_to_k4_fifo_cap <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(s3_to_k4_fifo_cap),3))),32));
    K3_U0_s3_to_k4_num_data_valid <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(IEEE.numeric_std.resize(unsigned(s3_to_k4_num_data_valid),3))),32));
    K4_U0_ap_continue <= ap_const_logic_1;
    K4_U0_ap_start <= start_for_K4_U0_empty_n;
    ap_done <= K4_U0_ap_done;
    ap_idle <= (entry_proc_U0_ap_idle and K4_U0_ap_idle and K3_U0_ap_idle and K2_U0_ap_idle and K1_U0_ap_idle and K0_U0_ap_idle);
    ap_ready <= ap_sync_ready;

    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    ap_sync_K0_U0_ap_ready <= (ap_sync_reg_K0_U0_ap_ready or K0_U0_ap_ready);
    ap_sync_entry_proc_U0_ap_ready <= (entry_proc_U0_ap_ready or ap_sync_reg_entry_proc_U0_ap_ready);
    ap_sync_ready <= (ap_sync_entry_proc_U0_ap_ready and ap_sync_K0_U0_ap_ready);
    entry_proc_U0_ap_continue <= ap_const_logic_1;
    entry_proc_U0_ap_start <= ((ap_sync_reg_entry_proc_U0_ap_ready xor ap_const_logic_1) and ap_start and ap_const_logic_1);
    in_r_0_RID <= ap_const_lv1_0;
    in_r_0_RLAST <= ap_const_logic_0;
    in_r_0_RRESP <= ap_const_lv2_0;
    in_r_0_RUSER <= ap_const_lv1_0;
    out_r_0_BID <= ap_const_lv1_0;
    out_r_0_BRESP <= ap_const_lv2_0;
    out_r_0_BUSER <= ap_const_lv1_0;
    start_for_K1_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_K2_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_K3_U0_din <= (0=>ap_const_logic_1, others=>'-');
    start_for_K4_U0_din <= (0=>ap_const_logic_1, others=>'-');
end behav;
