-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_K4 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    out_r_r_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    out_r_r_empty_n : IN STD_LOGIC;
    out_r_r_read : OUT STD_LOGIC;
    out_r_r_num_data_valid : IN STD_LOGIC_VECTOR (3 downto 0);
    out_r_r_fifo_cap : IN STD_LOGIC_VECTOR (3 downto 0);
    s3_to_k4_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    s3_to_k4_empty_n : IN STD_LOGIC;
    s3_to_k4_read : OUT STD_LOGIC;
    s3_to_k4_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    s3_to_k4_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_0_AWVALID : OUT STD_LOGIC;
    m_axi_out_r_0_AWREADY : IN STD_LOGIC;
    m_axi_out_r_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_out_r_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_r_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_WVALID : OUT STD_LOGIC;
    m_axi_out_r_0_WREADY : IN STD_LOGIC;
    m_axi_out_r_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_r_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_WLAST : OUT STD_LOGIC;
    m_axi_out_r_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_ARVALID : OUT STD_LOGIC;
    m_axi_out_r_0_ARREADY : IN STD_LOGIC;
    m_axi_out_r_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_out_r_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_r_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_out_r_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_out_r_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_RVALID : IN STD_LOGIC;
    m_axi_out_r_0_RREADY : OUT STD_LOGIC;
    m_axi_out_r_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_out_r_0_RLAST : IN STD_LOGIC;
    m_axi_out_r_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_out_r_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_BVALID : IN STD_LOGIC;
    m_axi_out_r_0_BREADY : OUT STD_LOGIC;
    m_axi_out_r_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_out_r_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_out_r_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of top_kernel_K4 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv64_10000 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000010000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_FFFF : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv24_0 : STD_LOGIC_VECTOR (23 downto 0) := "000000000000000000000000";
    constant ap_const_lv22_0 : STD_LOGIC_VECTOR (21 downto 0) := "0000000000000000000000";
    constant ap_const_lv55_CCCCC000000 : STD_LOGIC_VECTOR (54 downto 0) := "0000000000011001100110011001100000000000000000000000000";
    constant ap_const_lv32_36 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110110";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_35 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110101";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_7FFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "01111111111111111111111111111111";
    constant ap_const_lv32_80000000 : STD_LOGIC_VECTOR (31 downto 0) := "10000000000000000000000000000000";
    constant ap_const_lv32_1F99999A : STD_LOGIC_VECTOR (31 downto 0) := "00011111100110011001100110011010";
    constant ap_const_lv29_0 : STD_LOGIC_VECTOR (28 downto 0) := "00000000000000000000000000000";
    constant ap_const_lv29_1F99999A : STD_LOGIC_VECTOR (28 downto 0) := "11111100110011001100110011010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal first_iter_0_reg_148 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter1_grp1 : BOOLEAN;
    signal first_iter_0_reg_148_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state3_io_grp1 : BOOLEAN;
    signal icmp_ln113_reg_473 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter7_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state9_pp0_stage0_iter8_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln113_fu_174_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal s3_to_k4_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_grp1 : BOOLEAN;
    signal out_r_blk_n_AW : STD_LOGIC;
    signal out_r_blk_n_W : STD_LOGIC;
    signal out_r_blk_n_B : STD_LOGIC;
    signal out_r_r_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0_11001_grp1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone_grp0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln113_reg_473_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter4_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter5_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln113_reg_473_pp0_iter6_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_reg_477 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln1_reg_482 : STD_LOGIC_VECTOR (29 downto 0);
    signal tmp_reg_487 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_fu_438_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal select_ln17_reg_492 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal sext_ln113_fu_213_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_01001_grp1 : BOOLEAN;
    signal k1_fu_108 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    signal k_fu_168_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_sig_allocacmp_k1_load : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln115_fu_228_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal zext_ln115_fu_231_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal add_ln115_fu_234_p2 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_1_fu_248_p3 : STD_LOGIC_VECTOR (52 downto 0);
    signal p_shl_fu_240_p3 : STD_LOGIC_VECTOR (54 downto 0);
    signal sext_ln115_1_fu_256_p1 : STD_LOGIC_VECTOR (54 downto 0);
    signal add_ln115_2_fu_260_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal add_ln115_1_fu_266_p2 : STD_LOGIC_VECTOR (54 downto 0);
    signal tmp_3_fu_290_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal z_fu_280_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal zext_ln115_1_fu_306_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_1_fu_310_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_4_fu_298_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_316_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_fu_324_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_2_fu_272_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_2_fu_330_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_2_fu_342_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_3_fu_348_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_fu_354_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_1_fu_336_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_3_fu_366_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln115_4_fu_372_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_fu_360_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln115_1_fu_378_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln115_1_fu_392_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln115_fu_384_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal z_3_fu_398_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_6_fu_410_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln18_fu_418_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln17_fu_432_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln17_1_fu_424_p3 : STD_LOGIC_VECTOR (28 downto 0);
    signal trunc_ln115_fu_406_p1 : STD_LOGIC_VECTOR (28 downto 0);
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal ap_condition_510 : BOOLEAN;
    signal ap_condition_273 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_flow_control_loop_pipe IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC;
        ap_continue : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_U : component top_kernel_flow_control_loop_pipe
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int,
        ap_continue => ap_continue);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_loop_exit_ready_pp0_iter8_reg_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_loop_exit_ready_pp0_iter7_reg = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_const_logic_0;
            elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then 
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
            end if; 
        end if;
    end process;

    first_iter_0_reg_148_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_pp0_stage0)) then
                if ((ap_const_boolean_1 = ap_condition_510)) then 
                    first_iter_0_reg_148 <= ap_const_lv1_0;
                elsif (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
                    first_iter_0_reg_148 <= ap_const_lv1_1;
                end if;
            end if; 
        end if;
    end process;

    k1_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_273)) then
                k1_fu_108 <= k_fu_168_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                icmp_ln113_reg_473 <= icmp_ln113_fu_174_p2;
                icmp_ln113_reg_473_pp0_iter1_reg <= icmp_ln113_reg_473;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                icmp_ln113_reg_473_pp0_iter2_reg <= icmp_ln113_reg_473_pp0_iter1_reg;
                icmp_ln113_reg_473_pp0_iter3_reg <= icmp_ln113_reg_473_pp0_iter2_reg;
                icmp_ln113_reg_473_pp0_iter4_reg <= icmp_ln113_reg_473_pp0_iter3_reg;
                icmp_ln113_reg_473_pp0_iter5_reg <= icmp_ln113_reg_473_pp0_iter4_reg;
                icmp_ln113_reg_473_pp0_iter6_reg <= icmp_ln113_reg_473_pp0_iter5_reg;
                icmp_ln113_reg_473_pp0_iter7_reg <= icmp_ln113_reg_473_pp0_iter6_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then
                first_iter_0_reg_148_pp0_iter1_reg <= first_iter_0_reg_148;
                tmp_reg_487 <= s3_to_k4_dout(1 downto 1);
                trunc_ln1_reg_482 <= s3_to_k4_dout(31 downto 2);
                trunc_ln_reg_477 <= out_r_r_dout(63 downto 2);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1)) then
                select_ln17_reg_492 <= select_ln17_fu_438_p3;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln115_1_fu_266_p2 <= std_logic_vector(unsigned(add_ln115_2_fu_260_p2) + unsigned(ap_const_lv55_CCCCC000000));
    add_ln115_2_fu_260_p2 <= std_logic_vector(unsigned(p_shl_fu_240_p3) + unsigned(sext_ln115_1_fu_256_p1));
    add_ln115_fu_234_p2 <= std_logic_vector(signed(sext_ln115_fu_228_p1) + signed(zext_ln115_fu_231_p1));
    and_ln115_1_fu_378_p2 <= (xor_ln115_4_fu_372_p2 and tmp_2_fu_272_p3);
    and_ln115_fu_360_p2 <= (xor_ln115_1_fu_336_p2 and or_ln115_fu_354_p2);
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter8, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state9_pp0_stage0_iter8_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_01001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_out_r_0_WREADY, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state3_io_grp1, ap_block_state9_pp0_stage0_iter8_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8_grp1)) or ((m_axi_out_r_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp0_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_11001_grp1_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_out_r_0_WREADY, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state3_io_grp1, ap_block_state9_pp0_stage0_iter8_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_11001_grp1 <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8_grp1)) or ((m_axi_out_r_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;

        ap_block_pp0_stage0_grp1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter8, m_axi_out_r_0_WREADY, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1_grp1, ap_block_state3_io_grp1, ap_block_state9_pp0_stage0_iter8_grp1, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_done_reg = ap_const_logic_1) or ((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state9_pp0_stage0_iter8_grp1)) or ((m_axi_out_r_0_WREADY = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state3_io_grp1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1_grp1)) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_pp0_stage0_subdone_grp0_assign_proc : process(ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_start_int)
    begin
                ap_block_pp0_stage0_subdone_grp0 <= ((ap_done_reg = ap_const_logic_1) or ((ap_start_int = ap_const_logic_1) and (ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)));
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_done_reg = ap_const_logic_1);
    end process;


    ap_block_state2_pp0_stage0_iter1_grp1_assign_proc : process(out_r_r_empty_n, s3_to_k4_empty_n, first_iter_0_reg_148)
    begin
                ap_block_state2_pp0_stage0_iter1_grp1 <= ((s3_to_k4_empty_n = ap_const_logic_0) or ((out_r_r_empty_n = ap_const_logic_0) and (first_iter_0_reg_148 = ap_const_lv1_1)));
    end process;


    ap_block_state3_io_grp1_assign_proc : process(m_axi_out_r_0_AWREADY, first_iter_0_reg_148_pp0_iter1_reg)
    begin
                ap_block_state3_io_grp1 <= ((m_axi_out_r_0_AWREADY = ap_const_logic_0) and (first_iter_0_reg_148_pp0_iter1_reg = ap_const_lv1_1));
    end process;


    ap_block_state9_pp0_stage0_iter8_grp1_assign_proc : process(m_axi_out_r_0_BVALID, icmp_ln113_reg_473_pp0_iter7_reg)
    begin
                ap_block_state9_pp0_stage0_iter8_grp1 <= ((icmp_ln113_reg_473_pp0_iter7_reg = ap_const_lv1_1) and (m_axi_out_r_0_BVALID = ap_const_logic_0));
    end process;


    ap_condition_273_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001, ap_start_int)
    begin
                ap_condition_273 <= ((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001));
    end process;


    ap_condition_510_assign_proc : process(ap_enable_reg_pp0_iter1, icmp_ln113_reg_473, ap_block_pp0_stage0_11001)
    begin
                ap_condition_510 <= ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln113_reg_473 = ap_const_lv1_0));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, icmp_ln113_fu_174_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln113_fu_174_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_done_reg, ap_block_pp0_stage0_subdone, ap_loop_exit_ready_pp0_iter8_reg)
    begin
        if (((ap_loop_exit_ready_pp0_iter8_reg = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_k1_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_loop_init, ap_block_pp0_stage0, k1_fu_108, ap_start_int)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_start_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_sig_allocacmp_k1_load <= ap_const_lv16_0;
        else 
            ap_sig_allocacmp_k1_load <= k1_fu_108;
        end if; 
    end process;

    icmp_ln113_fu_174_p2 <= "1" when (ap_sig_allocacmp_k1_load = ap_const_lv16_FFFF) else "0";
    icmp_ln18_fu_418_p2 <= "1" when (signed(z_3_fu_398_p3) > signed(ap_const_lv32_1F99999A)) else "0";
    k_fu_168_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_k1_load) + unsigned(ap_const_lv16_1));
    m_axi_out_r_0_ARADDR <= ap_const_lv64_0;
    m_axi_out_r_0_ARBURST <= ap_const_lv2_0;
    m_axi_out_r_0_ARCACHE <= ap_const_lv4_0;
    m_axi_out_r_0_ARID <= ap_const_lv1_0;
    m_axi_out_r_0_ARLEN <= ap_const_lv32_0;
    m_axi_out_r_0_ARLOCK <= ap_const_lv2_0;
    m_axi_out_r_0_ARPROT <= ap_const_lv3_0;
    m_axi_out_r_0_ARQOS <= ap_const_lv4_0;
    m_axi_out_r_0_ARREGION <= ap_const_lv4_0;
    m_axi_out_r_0_ARSIZE <= ap_const_lv3_0;
    m_axi_out_r_0_ARUSER <= ap_const_lv1_0;
    m_axi_out_r_0_ARVALID <= ap_const_logic_0;
    m_axi_out_r_0_AWADDR <= sext_ln113_fu_213_p1;
    m_axi_out_r_0_AWBURST <= ap_const_lv2_0;
    m_axi_out_r_0_AWCACHE <= ap_const_lv4_0;
    m_axi_out_r_0_AWID <= ap_const_lv1_0;
    m_axi_out_r_0_AWLEN <= ap_const_lv64_10000(32 - 1 downto 0);
    m_axi_out_r_0_AWLOCK <= ap_const_lv2_0;
    m_axi_out_r_0_AWPROT <= ap_const_lv3_0;
    m_axi_out_r_0_AWQOS <= ap_const_lv4_0;
    m_axi_out_r_0_AWREGION <= ap_const_lv4_0;
    m_axi_out_r_0_AWSIZE <= ap_const_lv3_0;
    m_axi_out_r_0_AWUSER <= ap_const_lv1_0;

    m_axi_out_r_0_AWVALID_assign_proc : process(ap_enable_reg_pp0_iter2, first_iter_0_reg_148_pp0_iter1_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (first_iter_0_reg_148_pp0_iter1_reg = ap_const_lv1_1))) then 
            m_axi_out_r_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_out_r_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_out_r_0_BREADY_assign_proc : process(ap_enable_reg_pp0_iter8, icmp_ln113_reg_473_pp0_iter7_reg, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (icmp_ln113_reg_473_pp0_iter7_reg = ap_const_lv1_1))) then 
            m_axi_out_r_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_out_r_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_out_r_0_RREADY <= ap_const_logic_0;
    m_axi_out_r_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln17_reg_492),32));
    m_axi_out_r_0_WID <= ap_const_lv1_0;
    m_axi_out_r_0_WLAST <= ap_const_logic_0;
    m_axi_out_r_0_WSTRB <= ap_const_lv4_F;
    m_axi_out_r_0_WUSER <= ap_const_lv1_0;

    m_axi_out_r_0_WVALID_assign_proc : process(ap_enable_reg_pp0_iter3, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            m_axi_out_r_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_out_r_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

    or_ln115_1_fu_392_p2 <= (and_ln115_fu_360_p2 or and_ln115_1_fu_378_p2);
    or_ln115_2_fu_330_p2 <= (xor_ln115_fu_324_p2 or tmp_5_fu_316_p3);
    or_ln115_3_fu_366_p2 <= (tmp_5_fu_316_p3 or tmp_4_fu_298_p3);
    or_ln115_fu_354_p2 <= (xor_ln115_3_fu_348_p2 or tmp_5_fu_316_p3);
    or_ln17_fu_432_p2 <= (tmp_6_fu_410_p3 or icmp_ln18_fu_418_p2);

    out_r_blk_n_AW_assign_proc : process(ap_enable_reg_pp0_iter2, m_axi_out_r_0_AWREADY, first_iter_0_reg_148_pp0_iter1_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (first_iter_0_reg_148_pp0_iter1_reg = ap_const_lv1_1))) then 
            out_r_blk_n_AW <= m_axi_out_r_0_AWREADY;
        else 
            out_r_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    out_r_blk_n_B_assign_proc : process(ap_enable_reg_pp0_iter8, m_axi_out_r_0_BVALID, icmp_ln113_reg_473_pp0_iter7_reg, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter8 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (icmp_ln113_reg_473_pp0_iter7_reg = ap_const_lv1_1))) then 
            out_r_blk_n_B <= m_axi_out_r_0_BVALID;
        else 
            out_r_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    out_r_blk_n_W_assign_proc : process(ap_enable_reg_pp0_iter3, m_axi_out_r_0_WREADY, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            out_r_blk_n_W <= m_axi_out_r_0_WREADY;
        else 
            out_r_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;


    out_r_r_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, out_r_r_empty_n, first_iter_0_reg_148, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1) and (first_iter_0_reg_148 = ap_const_lv1_1))) then 
            out_r_r_blk_n <= out_r_r_empty_n;
        else 
            out_r_r_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    out_r_r_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, first_iter_0_reg_148, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1) and (first_iter_0_reg_148 = ap_const_lv1_1))) then 
            out_r_r_read <= ap_const_logic_1;
        else 
            out_r_r_read <= ap_const_logic_0;
        end if; 
    end process;

    p_shl_fu_240_p3 <= (add_ln115_fu_234_p2 & ap_const_lv24_0);

    s3_to_k4_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, s3_to_k4_empty_n, ap_block_pp0_stage0_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_grp1))) then 
            s3_to_k4_blk_n <= s3_to_k4_empty_n;
        else 
            s3_to_k4_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    s3_to_k4_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001_grp1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001_grp1))) then 
            s3_to_k4_read <= ap_const_logic_1;
        else 
            s3_to_k4_read <= ap_const_logic_0;
        end if; 
    end process;

    select_ln115_fu_384_p3 <= 
        ap_const_lv32_7FFFFFFF when (and_ln115_fu_360_p2(0) = '1') else 
        ap_const_lv32_80000000;
    select_ln17_1_fu_424_p3 <= 
        ap_const_lv29_0 when (tmp_6_fu_410_p3(0) = '1') else 
        ap_const_lv29_1F99999A;
    select_ln17_fu_438_p3 <= 
        select_ln17_1_fu_424_p3 when (or_ln17_fu_432_p2(0) = '1') else 
        trunc_ln115_fu_406_p1;
        sext_ln113_fu_213_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_reg_477),64));

        sext_ln115_1_fu_256_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_1_fu_248_p3),55));

        sext_ln115_fu_228_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln1_reg_482),31));

    tmp_1_fu_248_p3 <= (add_ln115_fu_234_p2 & ap_const_lv22_0);
    tmp_2_fu_272_p3 <= add_ln115_1_fu_266_p2(54 downto 54);
    tmp_3_fu_290_p3 <= add_ln115_1_fu_266_p2(21 downto 21);
    tmp_4_fu_298_p3 <= add_ln115_1_fu_266_p2(53 downto 53);
    tmp_5_fu_316_p3 <= z_1_fu_310_p2(31 downto 31);
    tmp_6_fu_410_p3 <= z_3_fu_398_p3(31 downto 31);
    trunc_ln115_fu_406_p1 <= z_3_fu_398_p3(29 - 1 downto 0);
    xor_ln115_1_fu_336_p2 <= (tmp_2_fu_272_p3 xor ap_const_lv1_1);
    xor_ln115_2_fu_342_p2 <= (tmp_2_fu_272_p3 xor or_ln115_2_fu_330_p2);
    xor_ln115_3_fu_348_p2 <= (xor_ln115_2_fu_342_p2 xor ap_const_lv1_1);
    xor_ln115_4_fu_372_p2 <= (or_ln115_3_fu_366_p2 xor ap_const_lv1_1);
    xor_ln115_fu_324_p2 <= (tmp_4_fu_298_p3 xor ap_const_lv1_1);
    z_1_fu_310_p2 <= std_logic_vector(unsigned(z_fu_280_p4) + unsigned(zext_ln115_1_fu_306_p1));
    z_3_fu_398_p3 <= 
        select_ln115_fu_384_p3 when (or_ln115_1_fu_392_p2(0) = '1') else 
        z_1_fu_310_p2;
    z_fu_280_p4 <= add_ln115_1_fu_266_p2(53 downto 22);
    zext_ln115_1_fu_306_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_3_fu_290_p3),32));
    zext_ln115_fu_231_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_reg_487),31));
end behav;
