-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_write_output is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    grid_final_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    grid_final_empty_n : IN STD_LOGIC;
    grid_final_read : OUT STD_LOGIC;
    grid_final_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    grid_final_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_out_0_AWVALID : OUT STD_LOGIC;
    m_axi_A_out_0_AWREADY : IN STD_LOGIC;
    m_axi_A_out_0_AWADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_A_out_0_AWID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_AWLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_A_out_0_AWSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_out_0_AWBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_AWLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_AWCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_AWPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_out_0_AWQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_AWREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_AWUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_WVALID : OUT STD_LOGIC;
    m_axi_A_out_0_WREADY : IN STD_LOGIC;
    m_axi_A_out_0_WDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_A_out_0_WSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_WLAST : OUT STD_LOGIC;
    m_axi_A_out_0_WID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_WUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_ARVALID : OUT STD_LOGIC;
    m_axi_A_out_0_ARREADY : IN STD_LOGIC;
    m_axi_A_out_0_ARADDR : OUT STD_LOGIC_VECTOR (63 downto 0);
    m_axi_A_out_0_ARID : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_ARLEN : OUT STD_LOGIC_VECTOR (31 downto 0);
    m_axi_A_out_0_ARSIZE : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_out_0_ARBURST : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_ARLOCK : OUT STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_ARCACHE : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_ARPROT : OUT STD_LOGIC_VECTOR (2 downto 0);
    m_axi_A_out_0_ARQOS : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_ARREGION : OUT STD_LOGIC_VECTOR (3 downto 0);
    m_axi_A_out_0_ARUSER : OUT STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_RVALID : IN STD_LOGIC;
    m_axi_A_out_0_RREADY : OUT STD_LOGIC;
    m_axi_A_out_0_RDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    m_axi_A_out_0_RLAST : IN STD_LOGIC;
    m_axi_A_out_0_RID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_RFIFONUM : IN STD_LOGIC_VECTOR (8 downto 0);
    m_axi_A_out_0_RUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_RRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_BVALID : IN STD_LOGIC;
    m_axi_A_out_0_BREADY : OUT STD_LOGIC;
    m_axi_A_out_0_BRESP : IN STD_LOGIC_VECTOR (1 downto 0);
    m_axi_A_out_0_BID : IN STD_LOGIC_VECTOR (0 downto 0);
    m_axi_A_out_0_BUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    A_out1_dout : IN STD_LOGIC_VECTOR (63 downto 0);
    A_out1_empty_n : IN STD_LOGIC;
    A_out1_read : OUT STD_LOGIC;
    A_out1_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    A_out1_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0) );
end;


architecture behav of top_kernel_write_output is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv64_10000 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000010000000000000000";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal grid_final_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal icmp_ln128_fu_155_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal A_out_blk_n_AW : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal A_out_blk_n_W : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal A_out_blk_n_B : STD_LOGIC;
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal A_out1_blk_n : STD_LOGIC;
    signal A_out_addr_reg_182 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal add_ln127_fu_149_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln127_reg_192 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln128_fu_161_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln128_reg_200 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state4 : BOOLEAN;
    signal grid_final_read_reg_205 : STD_LOGIC_VECTOR (23 downto 0);
    signal j_reg_104 : STD_LOGIC_VECTOR (8 downto 0);
    signal icmp_ln127_fu_143_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln127_fu_125_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_68 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal trunc_ln_fu_115_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((m_axi_A_out_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_68_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
                i_fu_68 <= ap_const_lv9_0;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4) and (icmp_ln128_fu_155_p2 = ap_const_lv1_1))) then 
                i_fu_68 <= add_ln127_reg_192;
            end if; 
        end if;
    end process;

    j_reg_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((m_axi_A_out_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                j_reg_104 <= add_ln128_reg_200;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln127_fu_143_p2 = ap_const_lv1_0))) then 
                j_reg_104 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                A_out_addr_reg_182 <= sext_ln127_fu_125_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                add_ln127_reg_192 <= add_ln127_fu_149_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4))) then
                add_ln128_reg_200 <= add_ln128_fu_161_p2;
                grid_final_read_reg_205 <= grid_final_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, m_axi_A_out_0_AWREADY, m_axi_A_out_0_WREADY, m_axi_A_out_0_BVALID, ap_CS_fsm_state4, icmp_ln128_fu_155_p2, ap_CS_fsm_state2, ap_CS_fsm_state5, ap_CS_fsm_state10, ap_block_state1, ap_CS_fsm_state3, ap_block_state4, icmp_ln127_fu_143_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((m_axi_A_out_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (icmp_ln127_fu_143_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4) and (icmp_ln128_fu_155_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4) and (icmp_ln128_fu_155_p2 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((m_axi_A_out_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                if (((m_axi_A_out_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;

    A_out1_blk_n_assign_proc : process(ap_start, ap_done_reg, ap_CS_fsm_state1, A_out1_empty_n)
    begin
        if ((not(((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            A_out1_blk_n <= A_out1_empty_n;
        else 
            A_out1_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    A_out1_read_assign_proc : process(ap_CS_fsm_state1, ap_block_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_const_boolean_0 = ap_block_state1))) then 
            A_out1_read <= ap_const_logic_1;
        else 
            A_out1_read <= ap_const_logic_0;
        end if; 
    end process;


    A_out_blk_n_AW_assign_proc : process(m_axi_A_out_0_AWREADY, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            A_out_blk_n_AW <= m_axi_A_out_0_AWREADY;
        else 
            A_out_blk_n_AW <= ap_const_logic_1;
        end if; 
    end process;


    A_out_blk_n_B_assign_proc : process(m_axi_A_out_0_BVALID, ap_CS_fsm_state10)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
            A_out_blk_n_B <= m_axi_A_out_0_BVALID;
        else 
            A_out_blk_n_B <= ap_const_logic_1;
        end if; 
    end process;


    A_out_blk_n_W_assign_proc : process(m_axi_A_out_0_WREADY, ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            A_out_blk_n_W <= m_axi_A_out_0_WREADY;
        else 
            A_out_blk_n_W <= ap_const_logic_1;
        end if; 
    end process;

    add_ln127_fu_149_p2 <= std_logic_vector(unsigned(i_fu_68) + unsigned(ap_const_lv9_1));
    add_ln128_fu_161_p2 <= std_logic_vector(unsigned(j_reg_104) + unsigned(ap_const_lv9_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state10_blk_assign_proc : process(m_axi_A_out_0_BVALID)
    begin
        if ((m_axi_A_out_0_BVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state10_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state10_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(m_axi_A_out_0_AWREADY)
    begin
        if ((m_axi_A_out_0_AWREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;

    ap_ST_fsm_state4_blk_assign_proc : process(ap_block_state4)
    begin
        if ((ap_const_boolean_1 = ap_block_state4)) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(m_axi_A_out_0_WREADY)
    begin
        if ((m_axi_A_out_0_WREADY = ap_const_logic_0)) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state6_blk <= ap_const_logic_0;
    ap_ST_fsm_state7_blk <= ap_const_logic_0;
    ap_ST_fsm_state8_blk <= ap_const_logic_0;
    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state1_assign_proc : process(ap_start, ap_done_reg, A_out1_empty_n)
    begin
                ap_block_state1 <= ((ap_const_logic_0 = A_out1_empty_n) or (ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(grid_final_empty_n, icmp_ln128_fu_155_p2)
    begin
                ap_block_state4 <= ((grid_final_empty_n = ap_const_logic_0) and (icmp_ln128_fu_155_p2 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, m_axi_A_out_0_BVALID, ap_CS_fsm_state10)
    begin
        if (((m_axi_A_out_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(m_axi_A_out_0_BVALID, ap_CS_fsm_state10)
    begin
        if (((m_axi_A_out_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    grid_final_blk_n_assign_proc : process(grid_final_empty_n, ap_CS_fsm_state4, icmp_ln128_fu_155_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln128_fu_155_p2 = ap_const_lv1_0))) then 
            grid_final_blk_n <= grid_final_empty_n;
        else 
            grid_final_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    grid_final_read_assign_proc : process(ap_CS_fsm_state4, icmp_ln128_fu_155_p2, ap_block_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (ap_const_boolean_0 = ap_block_state4) and (icmp_ln128_fu_155_p2 = ap_const_lv1_0))) then 
            grid_final_read <= ap_const_logic_1;
        else 
            grid_final_read <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln127_fu_143_p2 <= "1" when (i_fu_68 = ap_const_lv9_100) else "0";
    icmp_ln128_fu_155_p2 <= "1" when (j_reg_104 = ap_const_lv9_100) else "0";
    m_axi_A_out_0_ARADDR <= ap_const_lv64_0;
    m_axi_A_out_0_ARBURST <= ap_const_lv2_0;
    m_axi_A_out_0_ARCACHE <= ap_const_lv4_0;
    m_axi_A_out_0_ARID <= ap_const_lv1_0;
    m_axi_A_out_0_ARLEN <= ap_const_lv32_0;
    m_axi_A_out_0_ARLOCK <= ap_const_lv2_0;
    m_axi_A_out_0_ARPROT <= ap_const_lv3_0;
    m_axi_A_out_0_ARQOS <= ap_const_lv4_0;
    m_axi_A_out_0_ARREGION <= ap_const_lv4_0;
    m_axi_A_out_0_ARSIZE <= ap_const_lv3_0;
    m_axi_A_out_0_ARUSER <= ap_const_lv1_0;
    m_axi_A_out_0_ARVALID <= ap_const_logic_0;
    m_axi_A_out_0_AWADDR <= A_out_addr_reg_182;
    m_axi_A_out_0_AWBURST <= ap_const_lv2_0;
    m_axi_A_out_0_AWCACHE <= ap_const_lv4_0;
    m_axi_A_out_0_AWID <= ap_const_lv1_0;
    m_axi_A_out_0_AWLEN <= ap_const_lv64_10000(32 - 1 downto 0);
    m_axi_A_out_0_AWLOCK <= ap_const_lv2_0;
    m_axi_A_out_0_AWPROT <= ap_const_lv3_0;
    m_axi_A_out_0_AWQOS <= ap_const_lv4_0;
    m_axi_A_out_0_AWREGION <= ap_const_lv4_0;
    m_axi_A_out_0_AWSIZE <= ap_const_lv3_0;
    m_axi_A_out_0_AWUSER <= ap_const_lv1_0;

    m_axi_A_out_0_AWVALID_assign_proc : process(m_axi_A_out_0_AWREADY, ap_CS_fsm_state2)
    begin
        if (((m_axi_A_out_0_AWREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            m_axi_A_out_0_AWVALID <= ap_const_logic_1;
        else 
            m_axi_A_out_0_AWVALID <= ap_const_logic_0;
        end if; 
    end process;


    m_axi_A_out_0_BREADY_assign_proc : process(m_axi_A_out_0_BVALID, ap_CS_fsm_state10)
    begin
        if (((m_axi_A_out_0_BVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state10))) then 
            m_axi_A_out_0_BREADY <= ap_const_logic_1;
        else 
            m_axi_A_out_0_BREADY <= ap_const_logic_0;
        end if; 
    end process;

    m_axi_A_out_0_RREADY <= ap_const_logic_0;
    m_axi_A_out_0_WDATA <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grid_final_read_reg_205),32));
    m_axi_A_out_0_WID <= ap_const_lv1_0;
    m_axi_A_out_0_WLAST <= ap_const_logic_0;
    m_axi_A_out_0_WSTRB <= ap_const_lv4_F;
    m_axi_A_out_0_WUSER <= ap_const_lv1_0;

    m_axi_A_out_0_WVALID_assign_proc : process(m_axi_A_out_0_WREADY, ap_CS_fsm_state5)
    begin
        if (((m_axi_A_out_0_WREADY = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            m_axi_A_out_0_WVALID <= ap_const_logic_1;
        else 
            m_axi_A_out_0_WVALID <= ap_const_logic_0;
        end if; 
    end process;

        sext_ln127_fu_125_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln_fu_115_p4),64));

    trunc_ln_fu_115_p4 <= A_out1_dout(63 downto 2);
end behav;
