

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.in_r_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.K0_U0"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K0_U0.flow_control_loop_pipe_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.K1_U0"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K1_U0.sparsemux_7_2_32_1_1_U7"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K1_U0.flow_control_loop_pipe_U"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.K2_U0"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K2_U0.sparsemux_7_2_32_1_1_U11"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K2_U0.flow_control_loop_pipe_U"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.K3_U0"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K3_U0.mul_34s_31s_64_1_1_U14"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K3_U0.sdiv_50ns_34s_50_54_1_U15"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K3_U0.flow_control_loop_pipe_U"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.K4_U0"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.K4_U0.flow_control_loop_pipe_U"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.out_r_r_c_U"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s0_to_k1_U"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s0_to_k2_U"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s1_to_k3_U"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.k2_to_k3_U"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.s3_to_k4_U"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_K4_U0_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_K1_U0_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_K2_U0_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_K3_U0_U"}]}
set DependenceCheckSize 0
