// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="top_kernel_top_kernel,hls_ip_2025_1_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=2112950,HLS_SYN_TPT=2112941,HLS_SYN_MEM=180,HLS_SYN_DSP=0,HLS_SYN_FF=3088,HLS_SYN_LUT=4854,HLS_VERSION=2025_1_1}" *)

module top_kernel (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_A_in_AWVALID,
        m_axi_A_in_AWREADY,
        m_axi_A_in_AWADDR,
        m_axi_A_in_AWID,
        m_axi_A_in_AWLEN,
        m_axi_A_in_AWSIZE,
        m_axi_A_in_AWBURST,
        m_axi_A_in_AWLOCK,
        m_axi_A_in_AWCACHE,
        m_axi_A_in_AWPROT,
        m_axi_A_in_AWQOS,
        m_axi_A_in_AWREGION,
        m_axi_A_in_AWUSER,
        m_axi_A_in_WVALID,
        m_axi_A_in_WREADY,
        m_axi_A_in_WDATA,
        m_axi_A_in_WSTRB,
        m_axi_A_in_WLAST,
        m_axi_A_in_WID,
        m_axi_A_in_WUSER,
        m_axi_A_in_ARVALID,
        m_axi_A_in_ARREADY,
        m_axi_A_in_ARADDR,
        m_axi_A_in_ARID,
        m_axi_A_in_ARLEN,
        m_axi_A_in_ARSIZE,
        m_axi_A_in_ARBURST,
        m_axi_A_in_ARLOCK,
        m_axi_A_in_ARCACHE,
        m_axi_A_in_ARPROT,
        m_axi_A_in_ARQOS,
        m_axi_A_in_ARREGION,
        m_axi_A_in_ARUSER,
        m_axi_A_in_RVALID,
        m_axi_A_in_RREADY,
        m_axi_A_in_RDATA,
        m_axi_A_in_RLAST,
        m_axi_A_in_RID,
        m_axi_A_in_RUSER,
        m_axi_A_in_RRESP,
        m_axi_A_in_BVALID,
        m_axi_A_in_BREADY,
        m_axi_A_in_BRESP,
        m_axi_A_in_BID,
        m_axi_A_in_BUSER,
        m_axi_A_out_AWVALID,
        m_axi_A_out_AWREADY,
        m_axi_A_out_AWADDR,
        m_axi_A_out_AWID,
        m_axi_A_out_AWLEN,
        m_axi_A_out_AWSIZE,
        m_axi_A_out_AWBURST,
        m_axi_A_out_AWLOCK,
        m_axi_A_out_AWCACHE,
        m_axi_A_out_AWPROT,
        m_axi_A_out_AWQOS,
        m_axi_A_out_AWREGION,
        m_axi_A_out_AWUSER,
        m_axi_A_out_WVALID,
        m_axi_A_out_WREADY,
        m_axi_A_out_WDATA,
        m_axi_A_out_WSTRB,
        m_axi_A_out_WLAST,
        m_axi_A_out_WID,
        m_axi_A_out_WUSER,
        m_axi_A_out_ARVALID,
        m_axi_A_out_ARREADY,
        m_axi_A_out_ARADDR,
        m_axi_A_out_ARID,
        m_axi_A_out_ARLEN,
        m_axi_A_out_ARSIZE,
        m_axi_A_out_ARBURST,
        m_axi_A_out_ARLOCK,
        m_axi_A_out_ARCACHE,
        m_axi_A_out_ARPROT,
        m_axi_A_out_ARQOS,
        m_axi_A_out_ARREGION,
        m_axi_A_out_ARUSER,
        m_axi_A_out_RVALID,
        m_axi_A_out_RREADY,
        m_axi_A_out_RDATA,
        m_axi_A_out_RLAST,
        m_axi_A_out_RID,
        m_axi_A_out_RUSER,
        m_axi_A_out_RRESP,
        m_axi_A_out_BVALID,
        m_axi_A_out_BREADY,
        m_axi_A_out_BRESP,
        m_axi_A_out_BID,
        m_axi_A_out_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_IN_ID_WIDTH = 1;
parameter    C_M_AXI_A_IN_ADDR_WIDTH = 64;
parameter    C_M_AXI_A_IN_DATA_WIDTH = 32;
parameter    C_M_AXI_A_IN_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_IN_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_IN_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_IN_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_IN_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_IN_USER_VALUE = 0;
parameter    C_M_AXI_A_IN_PROT_VALUE = 0;
parameter    C_M_AXI_A_IN_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_A_OUT_ID_WIDTH = 1;
parameter    C_M_AXI_A_OUT_ADDR_WIDTH = 64;
parameter    C_M_AXI_A_OUT_DATA_WIDTH = 32;
parameter    C_M_AXI_A_OUT_AWUSER_WIDTH = 1;
parameter    C_M_AXI_A_OUT_ARUSER_WIDTH = 1;
parameter    C_M_AXI_A_OUT_WUSER_WIDTH = 1;
parameter    C_M_AXI_A_OUT_RUSER_WIDTH = 1;
parameter    C_M_AXI_A_OUT_BUSER_WIDTH = 1;
parameter    C_M_AXI_A_OUT_USER_VALUE = 0;
parameter    C_M_AXI_A_OUT_PROT_VALUE = 0;
parameter    C_M_AXI_A_OUT_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_IN_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_A_OUT_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_A_in_AWVALID;
input   m_axi_A_in_AWREADY;
output  [C_M_AXI_A_IN_ADDR_WIDTH - 1:0] m_axi_A_in_AWADDR;
output  [C_M_AXI_A_IN_ID_WIDTH - 1:0] m_axi_A_in_AWID;
output  [7:0] m_axi_A_in_AWLEN;
output  [2:0] m_axi_A_in_AWSIZE;
output  [1:0] m_axi_A_in_AWBURST;
output  [1:0] m_axi_A_in_AWLOCK;
output  [3:0] m_axi_A_in_AWCACHE;
output  [2:0] m_axi_A_in_AWPROT;
output  [3:0] m_axi_A_in_AWQOS;
output  [3:0] m_axi_A_in_AWREGION;
output  [C_M_AXI_A_IN_AWUSER_WIDTH - 1:0] m_axi_A_in_AWUSER;
output   m_axi_A_in_WVALID;
input   m_axi_A_in_WREADY;
output  [C_M_AXI_A_IN_DATA_WIDTH - 1:0] m_axi_A_in_WDATA;
output  [C_M_AXI_A_IN_WSTRB_WIDTH - 1:0] m_axi_A_in_WSTRB;
output   m_axi_A_in_WLAST;
output  [C_M_AXI_A_IN_ID_WIDTH - 1:0] m_axi_A_in_WID;
output  [C_M_AXI_A_IN_WUSER_WIDTH - 1:0] m_axi_A_in_WUSER;
output   m_axi_A_in_ARVALID;
input   m_axi_A_in_ARREADY;
output  [C_M_AXI_A_IN_ADDR_WIDTH - 1:0] m_axi_A_in_ARADDR;
output  [C_M_AXI_A_IN_ID_WIDTH - 1:0] m_axi_A_in_ARID;
output  [7:0] m_axi_A_in_ARLEN;
output  [2:0] m_axi_A_in_ARSIZE;
output  [1:0] m_axi_A_in_ARBURST;
output  [1:0] m_axi_A_in_ARLOCK;
output  [3:0] m_axi_A_in_ARCACHE;
output  [2:0] m_axi_A_in_ARPROT;
output  [3:0] m_axi_A_in_ARQOS;
output  [3:0] m_axi_A_in_ARREGION;
output  [C_M_AXI_A_IN_ARUSER_WIDTH - 1:0] m_axi_A_in_ARUSER;
input   m_axi_A_in_RVALID;
output   m_axi_A_in_RREADY;
input  [C_M_AXI_A_IN_DATA_WIDTH - 1:0] m_axi_A_in_RDATA;
input   m_axi_A_in_RLAST;
input  [C_M_AXI_A_IN_ID_WIDTH - 1:0] m_axi_A_in_RID;
input  [C_M_AXI_A_IN_RUSER_WIDTH - 1:0] m_axi_A_in_RUSER;
input  [1:0] m_axi_A_in_RRESP;
input   m_axi_A_in_BVALID;
output   m_axi_A_in_BREADY;
input  [1:0] m_axi_A_in_BRESP;
input  [C_M_AXI_A_IN_ID_WIDTH - 1:0] m_axi_A_in_BID;
input  [C_M_AXI_A_IN_BUSER_WIDTH - 1:0] m_axi_A_in_BUSER;
output   m_axi_A_out_AWVALID;
input   m_axi_A_out_AWREADY;
output  [C_M_AXI_A_OUT_ADDR_WIDTH - 1:0] m_axi_A_out_AWADDR;
output  [C_M_AXI_A_OUT_ID_WIDTH - 1:0] m_axi_A_out_AWID;
output  [7:0] m_axi_A_out_AWLEN;
output  [2:0] m_axi_A_out_AWSIZE;
output  [1:0] m_axi_A_out_AWBURST;
output  [1:0] m_axi_A_out_AWLOCK;
output  [3:0] m_axi_A_out_AWCACHE;
output  [2:0] m_axi_A_out_AWPROT;
output  [3:0] m_axi_A_out_AWQOS;
output  [3:0] m_axi_A_out_AWREGION;
output  [C_M_AXI_A_OUT_AWUSER_WIDTH - 1:0] m_axi_A_out_AWUSER;
output   m_axi_A_out_WVALID;
input   m_axi_A_out_WREADY;
output  [C_M_AXI_A_OUT_DATA_WIDTH - 1:0] m_axi_A_out_WDATA;
output  [C_M_AXI_A_OUT_WSTRB_WIDTH - 1:0] m_axi_A_out_WSTRB;
output   m_axi_A_out_WLAST;
output  [C_M_AXI_A_OUT_ID_WIDTH - 1:0] m_axi_A_out_WID;
output  [C_M_AXI_A_OUT_WUSER_WIDTH - 1:0] m_axi_A_out_WUSER;
output   m_axi_A_out_ARVALID;
input   m_axi_A_out_ARREADY;
output  [C_M_AXI_A_OUT_ADDR_WIDTH - 1:0] m_axi_A_out_ARADDR;
output  [C_M_AXI_A_OUT_ID_WIDTH - 1:0] m_axi_A_out_ARID;
output  [7:0] m_axi_A_out_ARLEN;
output  [2:0] m_axi_A_out_ARSIZE;
output  [1:0] m_axi_A_out_ARBURST;
output  [1:0] m_axi_A_out_ARLOCK;
output  [3:0] m_axi_A_out_ARCACHE;
output  [2:0] m_axi_A_out_ARPROT;
output  [3:0] m_axi_A_out_ARQOS;
output  [3:0] m_axi_A_out_ARREGION;
output  [C_M_AXI_A_OUT_ARUSER_WIDTH - 1:0] m_axi_A_out_ARUSER;
input   m_axi_A_out_RVALID;
output   m_axi_A_out_RREADY;
input  [C_M_AXI_A_OUT_DATA_WIDTH - 1:0] m_axi_A_out_RDATA;
input   m_axi_A_out_RLAST;
input  [C_M_AXI_A_OUT_ID_WIDTH - 1:0] m_axi_A_out_RID;
input  [C_M_AXI_A_OUT_RUSER_WIDTH - 1:0] m_axi_A_out_RUSER;
input  [1:0] m_axi_A_out_RRESP;
input   m_axi_A_out_BVALID;
output   m_axi_A_out_BREADY;
input  [1:0] m_axi_A_out_BRESP;
input  [C_M_AXI_A_OUT_ID_WIDTH - 1:0] m_axi_A_out_BID;
input  [C_M_AXI_A_OUT_BUSER_WIDTH - 1:0] m_axi_A_out_BUSER;

 reg    ap_rst_n_inv;
wire   [63:0] A_in_r;
wire   [63:0] A_out_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire    A_in_0_AWREADY;
wire    A_in_0_WREADY;
wire    A_in_0_ARREADY;
wire    A_in_0_RVALID;
wire   [31:0] A_in_0_RDATA;
wire    A_in_0_RLAST;
wire   [0:0] A_in_0_RID;
wire   [8:0] A_in_0_RFIFONUM;
wire   [0:0] A_in_0_RUSER;
wire   [1:0] A_in_0_RRESP;
wire    A_in_0_BVALID;
wire    A_out_0_AWREADY;
wire    A_out_0_WREADY;
wire    A_out_0_ARREADY;
wire    A_out_0_RVALID;
wire   [31:0] A_out_0_RDATA;
wire   [8:0] A_out_0_RFIFONUM;
wire    A_out_0_BVALID;
wire   [1:0] A_out_0_BRESP;
wire   [0:0] A_out_0_BID;
wire   [0:0] A_out_0_BUSER;
wire    entry_proc_U0_ap_start;
wire    entry_proc_U0_ap_done;
wire    entry_proc_U0_ap_continue;
wire    entry_proc_U0_ap_idle;
wire    entry_proc_U0_ap_ready;
wire    entry_proc_U0_start_out;
wire    entry_proc_U0_start_write;
wire   [63:0] entry_proc_U0_A_out_r_c_din;
wire    entry_proc_U0_A_out_r_c_write;
wire    read_input_U0_ap_start;
wire    read_input_U0_ap_done;
wire    read_input_U0_ap_continue;
wire    read_input_U0_ap_idle;
wire    read_input_U0_ap_ready;
wire    read_input_U0_start_out;
wire    read_input_U0_start_write;
wire    read_input_U0_m_axi_A_in_0_AWVALID;
wire   [63:0] read_input_U0_m_axi_A_in_0_AWADDR;
wire   [0:0] read_input_U0_m_axi_A_in_0_AWID;
wire   [31:0] read_input_U0_m_axi_A_in_0_AWLEN;
wire   [2:0] read_input_U0_m_axi_A_in_0_AWSIZE;
wire   [1:0] read_input_U0_m_axi_A_in_0_AWBURST;
wire   [1:0] read_input_U0_m_axi_A_in_0_AWLOCK;
wire   [3:0] read_input_U0_m_axi_A_in_0_AWCACHE;
wire   [2:0] read_input_U0_m_axi_A_in_0_AWPROT;
wire   [3:0] read_input_U0_m_axi_A_in_0_AWQOS;
wire   [3:0] read_input_U0_m_axi_A_in_0_AWREGION;
wire   [0:0] read_input_U0_m_axi_A_in_0_AWUSER;
wire    read_input_U0_m_axi_A_in_0_WVALID;
wire   [31:0] read_input_U0_m_axi_A_in_0_WDATA;
wire   [3:0] read_input_U0_m_axi_A_in_0_WSTRB;
wire    read_input_U0_m_axi_A_in_0_WLAST;
wire   [0:0] read_input_U0_m_axi_A_in_0_WID;
wire   [0:0] read_input_U0_m_axi_A_in_0_WUSER;
wire    read_input_U0_m_axi_A_in_0_ARVALID;
wire   [63:0] read_input_U0_m_axi_A_in_0_ARADDR;
wire   [0:0] read_input_U0_m_axi_A_in_0_ARID;
wire   [31:0] read_input_U0_m_axi_A_in_0_ARLEN;
wire   [2:0] read_input_U0_m_axi_A_in_0_ARSIZE;
wire   [1:0] read_input_U0_m_axi_A_in_0_ARBURST;
wire   [1:0] read_input_U0_m_axi_A_in_0_ARLOCK;
wire   [3:0] read_input_U0_m_axi_A_in_0_ARCACHE;
wire   [2:0] read_input_U0_m_axi_A_in_0_ARPROT;
wire   [3:0] read_input_U0_m_axi_A_in_0_ARQOS;
wire   [3:0] read_input_U0_m_axi_A_in_0_ARREGION;
wire   [0:0] read_input_U0_m_axi_A_in_0_ARUSER;
wire    read_input_U0_m_axi_A_in_0_RREADY;
wire    read_input_U0_m_axi_A_in_0_BREADY;
wire   [23:0] read_input_U0_grid_initial_din;
wire    read_input_U0_grid_initial_write;
wire    compute_U0_ap_start;
wire    compute_U0_ap_done;
wire    compute_U0_ap_continue;
wire    compute_U0_ap_idle;
wire    compute_U0_ap_ready;
wire    compute_U0_grid_initial_read;
wire   [23:0] compute_U0_grid_final_din;
wire    compute_U0_grid_final_write;
wire   [31:0] compute_U0_grid_final_num_data_valid;
wire   [31:0] compute_U0_grid_final_fifo_cap;
wire    write_output_U0_ap_start;
wire    write_output_U0_ap_done;
wire    write_output_U0_ap_continue;
wire    write_output_U0_ap_idle;
wire    write_output_U0_ap_ready;
wire    write_output_U0_A_out1_read;
wire    write_output_U0_m_axi_A_out_0_AWVALID;
wire   [63:0] write_output_U0_m_axi_A_out_0_AWADDR;
wire   [0:0] write_output_U0_m_axi_A_out_0_AWID;
wire   [31:0] write_output_U0_m_axi_A_out_0_AWLEN;
wire   [2:0] write_output_U0_m_axi_A_out_0_AWSIZE;
wire   [1:0] write_output_U0_m_axi_A_out_0_AWBURST;
wire   [1:0] write_output_U0_m_axi_A_out_0_AWLOCK;
wire   [3:0] write_output_U0_m_axi_A_out_0_AWCACHE;
wire   [2:0] write_output_U0_m_axi_A_out_0_AWPROT;
wire   [3:0] write_output_U0_m_axi_A_out_0_AWQOS;
wire   [3:0] write_output_U0_m_axi_A_out_0_AWREGION;
wire   [0:0] write_output_U0_m_axi_A_out_0_AWUSER;
wire    write_output_U0_m_axi_A_out_0_WVALID;
wire   [31:0] write_output_U0_m_axi_A_out_0_WDATA;
wire   [3:0] write_output_U0_m_axi_A_out_0_WSTRB;
wire    write_output_U0_m_axi_A_out_0_WLAST;
wire   [0:0] write_output_U0_m_axi_A_out_0_WID;
wire   [0:0] write_output_U0_m_axi_A_out_0_WUSER;
wire    write_output_U0_m_axi_A_out_0_ARVALID;
wire   [63:0] write_output_U0_m_axi_A_out_0_ARADDR;
wire   [0:0] write_output_U0_m_axi_A_out_0_ARID;
wire   [31:0] write_output_U0_m_axi_A_out_0_ARLEN;
wire   [2:0] write_output_U0_m_axi_A_out_0_ARSIZE;
wire   [1:0] write_output_U0_m_axi_A_out_0_ARBURST;
wire   [1:0] write_output_U0_m_axi_A_out_0_ARLOCK;
wire   [3:0] write_output_U0_m_axi_A_out_0_ARCACHE;
wire   [2:0] write_output_U0_m_axi_A_out_0_ARPROT;
wire   [3:0] write_output_U0_m_axi_A_out_0_ARQOS;
wire   [3:0] write_output_U0_m_axi_A_out_0_ARREGION;
wire   [0:0] write_output_U0_m_axi_A_out_0_ARUSER;
wire    write_output_U0_m_axi_A_out_0_RREADY;
wire    write_output_U0_m_axi_A_out_0_BREADY;
wire    write_output_U0_grid_final_read;
wire    A_out_r_c_full_n;
wire   [63:0] A_out_r_c_dout;
wire    A_out_r_c_empty_n;
wire   [2:0] A_out_r_c_num_data_valid;
wire   [2:0] A_out_r_c_fifo_cap;
wire    grid_initial_full_n;
wire   [23:0] grid_initial_dout;
wire    grid_initial_empty_n;
wire   [2:0] grid_initial_num_data_valid;
wire   [2:0] grid_initial_fifo_cap;
wire    grid_final_full_n;
wire   [23:0] grid_final_dout;
wire    grid_final_empty_n;
wire   [2:0] grid_final_num_data_valid;
wire   [2:0] grid_final_fifo_cap;
wire    ap_sync_ready;
reg    ap_sync_reg_entry_proc_U0_ap_ready;
wire    ap_sync_entry_proc_U0_ap_ready;
reg    ap_sync_reg_read_input_U0_ap_ready;
wire    ap_sync_read_input_U0_ap_ready;
wire   [0:0] start_for_write_output_U0_din;
wire    start_for_write_output_U0_full_n;
wire   [0:0] start_for_write_output_U0_dout;
wire    start_for_write_output_U0_empty_n;
wire   [0:0] start_for_compute_U0_din;
wire    start_for_compute_U0_full_n;
wire   [0:0] start_for_compute_U0_dout;
wire    start_for_compute_U0_empty_n;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_sync_reg_entry_proc_U0_ap_ready = 1'b0;
#0 ap_sync_reg_read_input_U0_ap_ready = 1'b0;
end

top_kernel_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .A_in_r(A_in_r),
    .A_out_r(A_out_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

top_kernel_A_in_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_IN_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_IN_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_IN_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_IN_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_IN_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_IN_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_IN_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_IN_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_A_IN_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_IN_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_IN_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 0 ))
A_in_m_axi_U(
    .AWVALID(m_axi_A_in_AWVALID),
    .AWREADY(m_axi_A_in_AWREADY),
    .AWADDR(m_axi_A_in_AWADDR),
    .AWID(m_axi_A_in_AWID),
    .AWLEN(m_axi_A_in_AWLEN),
    .AWSIZE(m_axi_A_in_AWSIZE),
    .AWBURST(m_axi_A_in_AWBURST),
    .AWLOCK(m_axi_A_in_AWLOCK),
    .AWCACHE(m_axi_A_in_AWCACHE),
    .AWPROT(m_axi_A_in_AWPROT),
    .AWQOS(m_axi_A_in_AWQOS),
    .AWREGION(m_axi_A_in_AWREGION),
    .AWUSER(m_axi_A_in_AWUSER),
    .WVALID(m_axi_A_in_WVALID),
    .WREADY(m_axi_A_in_WREADY),
    .WDATA(m_axi_A_in_WDATA),
    .WSTRB(m_axi_A_in_WSTRB),
    .WLAST(m_axi_A_in_WLAST),
    .WID(m_axi_A_in_WID),
    .WUSER(m_axi_A_in_WUSER),
    .ARVALID(m_axi_A_in_ARVALID),
    .ARREADY(m_axi_A_in_ARREADY),
    .ARADDR(m_axi_A_in_ARADDR),
    .ARID(m_axi_A_in_ARID),
    .ARLEN(m_axi_A_in_ARLEN),
    .ARSIZE(m_axi_A_in_ARSIZE),
    .ARBURST(m_axi_A_in_ARBURST),
    .ARLOCK(m_axi_A_in_ARLOCK),
    .ARCACHE(m_axi_A_in_ARCACHE),
    .ARPROT(m_axi_A_in_ARPROT),
    .ARQOS(m_axi_A_in_ARQOS),
    .ARREGION(m_axi_A_in_ARREGION),
    .ARUSER(m_axi_A_in_ARUSER),
    .RVALID(m_axi_A_in_RVALID),
    .RREADY(m_axi_A_in_RREADY),
    .RDATA(m_axi_A_in_RDATA),
    .RLAST(m_axi_A_in_RLAST),
    .RID(m_axi_A_in_RID),
    .RUSER(m_axi_A_in_RUSER),
    .RRESP(m_axi_A_in_RRESP),
    .BVALID(m_axi_A_in_BVALID),
    .BREADY(m_axi_A_in_BREADY),
    .BRESP(m_axi_A_in_BRESP),
    .BID(m_axi_A_in_BID),
    .BUSER(m_axi_A_in_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(read_input_U0_m_axi_A_in_0_ARVALID),
    .I_CH0_ARREADY(A_in_0_ARREADY),
    .I_CH0_ARADDR(read_input_U0_m_axi_A_in_0_ARADDR),
    .I_CH0_ARLEN(read_input_U0_m_axi_A_in_0_ARLEN),
    .I_CH0_RVALID(A_in_0_RVALID),
    .I_CH0_RREADY(read_input_U0_m_axi_A_in_0_RREADY),
    .I_CH0_RDATA(A_in_0_RDATA),
    .I_CH0_RFIFONUM(A_in_0_RFIFONUM),
    .I_CH0_AWVALID(1'b0),
    .I_CH0_AWREADY(A_in_0_AWREADY),
    .I_CH0_AWADDR(64'd0),
    .I_CH0_AWLEN(32'd0),
    .I_CH0_WVALID(1'b0),
    .I_CH0_WREADY(A_in_0_WREADY),
    .I_CH0_WDATA(32'd0),
    .I_CH0_WSTRB(4'd0),
    .I_CH0_BVALID(A_in_0_BVALID),
    .I_CH0_BREADY(1'b0)
);

top_kernel_A_out_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 4 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_A_OUT_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_A_OUT_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_A_OUT_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_A_OUT_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_A_OUT_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_A_OUT_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_A_OUT_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_A_OUT_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_A_OUT_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_A_OUT_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_A_OUT_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 0 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
A_out_m_axi_U(
    .AWVALID(m_axi_A_out_AWVALID),
    .AWREADY(m_axi_A_out_AWREADY),
    .AWADDR(m_axi_A_out_AWADDR),
    .AWID(m_axi_A_out_AWID),
    .AWLEN(m_axi_A_out_AWLEN),
    .AWSIZE(m_axi_A_out_AWSIZE),
    .AWBURST(m_axi_A_out_AWBURST),
    .AWLOCK(m_axi_A_out_AWLOCK),
    .AWCACHE(m_axi_A_out_AWCACHE),
    .AWPROT(m_axi_A_out_AWPROT),
    .AWQOS(m_axi_A_out_AWQOS),
    .AWREGION(m_axi_A_out_AWREGION),
    .AWUSER(m_axi_A_out_AWUSER),
    .WVALID(m_axi_A_out_WVALID),
    .WREADY(m_axi_A_out_WREADY),
    .WDATA(m_axi_A_out_WDATA),
    .WSTRB(m_axi_A_out_WSTRB),
    .WLAST(m_axi_A_out_WLAST),
    .WID(m_axi_A_out_WID),
    .WUSER(m_axi_A_out_WUSER),
    .ARVALID(m_axi_A_out_ARVALID),
    .ARREADY(m_axi_A_out_ARREADY),
    .ARADDR(m_axi_A_out_ARADDR),
    .ARID(m_axi_A_out_ARID),
    .ARLEN(m_axi_A_out_ARLEN),
    .ARSIZE(m_axi_A_out_ARSIZE),
    .ARBURST(m_axi_A_out_ARBURST),
    .ARLOCK(m_axi_A_out_ARLOCK),
    .ARCACHE(m_axi_A_out_ARCACHE),
    .ARPROT(m_axi_A_out_ARPROT),
    .ARQOS(m_axi_A_out_ARQOS),
    .ARREGION(m_axi_A_out_ARREGION),
    .ARUSER(m_axi_A_out_ARUSER),
    .RVALID(m_axi_A_out_RVALID),
    .RREADY(m_axi_A_out_RREADY),
    .RDATA(m_axi_A_out_RDATA),
    .RLAST(m_axi_A_out_RLAST),
    .RID(m_axi_A_out_RID),
    .RUSER(m_axi_A_out_RUSER),
    .RRESP(m_axi_A_out_RRESP),
    .BVALID(m_axi_A_out_BVALID),
    .BREADY(m_axi_A_out_BREADY),
    .BRESP(m_axi_A_out_BRESP),
    .BID(m_axi_A_out_BID),
    .BUSER(m_axi_A_out_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(1'b0),
    .I_CH0_ARREADY(A_out_0_ARREADY),
    .I_CH0_ARADDR(64'd0),
    .I_CH0_ARLEN(32'd0),
    .I_CH0_RVALID(A_out_0_RVALID),
    .I_CH0_RREADY(1'b0),
    .I_CH0_RDATA(A_out_0_RDATA),
    .I_CH0_RFIFONUM(A_out_0_RFIFONUM),
    .I_CH0_AWVALID(write_output_U0_m_axi_A_out_0_AWVALID),
    .I_CH0_AWREADY(A_out_0_AWREADY),
    .I_CH0_AWADDR(write_output_U0_m_axi_A_out_0_AWADDR),
    .I_CH0_AWLEN(write_output_U0_m_axi_A_out_0_AWLEN),
    .I_CH0_WVALID(write_output_U0_m_axi_A_out_0_WVALID),
    .I_CH0_WREADY(A_out_0_WREADY),
    .I_CH0_WDATA(write_output_U0_m_axi_A_out_0_WDATA),
    .I_CH0_WSTRB(write_output_U0_m_axi_A_out_0_WSTRB),
    .I_CH0_BVALID(A_out_0_BVALID),
    .I_CH0_BREADY(write_output_U0_m_axi_A_out_0_BREADY)
);

top_kernel_entry_proc entry_proc_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(entry_proc_U0_ap_start),
    .start_full_n(start_for_write_output_U0_full_n),
    .ap_done(entry_proc_U0_ap_done),
    .ap_continue(entry_proc_U0_ap_continue),
    .ap_idle(entry_proc_U0_ap_idle),
    .ap_ready(entry_proc_U0_ap_ready),
    .start_out(entry_proc_U0_start_out),
    .start_write(entry_proc_U0_start_write),
    .A_out_r(A_out_r),
    .A_out_r_c_din(entry_proc_U0_A_out_r_c_din),
    .A_out_r_c_full_n(A_out_r_c_full_n),
    .A_out_r_c_write(entry_proc_U0_A_out_r_c_write),
    .A_out_r_c_num_data_valid(A_out_r_c_num_data_valid),
    .A_out_r_c_fifo_cap(A_out_r_c_fifo_cap)
);

top_kernel_read_input read_input_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(read_input_U0_ap_start),
    .start_full_n(start_for_compute_U0_full_n),
    .ap_done(read_input_U0_ap_done),
    .ap_continue(read_input_U0_ap_continue),
    .ap_idle(read_input_U0_ap_idle),
    .ap_ready(read_input_U0_ap_ready),
    .start_out(read_input_U0_start_out),
    .start_write(read_input_U0_start_write),
    .m_axi_A_in_0_AWVALID(read_input_U0_m_axi_A_in_0_AWVALID),
    .m_axi_A_in_0_AWREADY(1'b0),
    .m_axi_A_in_0_AWADDR(read_input_U0_m_axi_A_in_0_AWADDR),
    .m_axi_A_in_0_AWID(read_input_U0_m_axi_A_in_0_AWID),
    .m_axi_A_in_0_AWLEN(read_input_U0_m_axi_A_in_0_AWLEN),
    .m_axi_A_in_0_AWSIZE(read_input_U0_m_axi_A_in_0_AWSIZE),
    .m_axi_A_in_0_AWBURST(read_input_U0_m_axi_A_in_0_AWBURST),
    .m_axi_A_in_0_AWLOCK(read_input_U0_m_axi_A_in_0_AWLOCK),
    .m_axi_A_in_0_AWCACHE(read_input_U0_m_axi_A_in_0_AWCACHE),
    .m_axi_A_in_0_AWPROT(read_input_U0_m_axi_A_in_0_AWPROT),
    .m_axi_A_in_0_AWQOS(read_input_U0_m_axi_A_in_0_AWQOS),
    .m_axi_A_in_0_AWREGION(read_input_U0_m_axi_A_in_0_AWREGION),
    .m_axi_A_in_0_AWUSER(read_input_U0_m_axi_A_in_0_AWUSER),
    .m_axi_A_in_0_WVALID(read_input_U0_m_axi_A_in_0_WVALID),
    .m_axi_A_in_0_WREADY(1'b0),
    .m_axi_A_in_0_WDATA(read_input_U0_m_axi_A_in_0_WDATA),
    .m_axi_A_in_0_WSTRB(read_input_U0_m_axi_A_in_0_WSTRB),
    .m_axi_A_in_0_WLAST(read_input_U0_m_axi_A_in_0_WLAST),
    .m_axi_A_in_0_WID(read_input_U0_m_axi_A_in_0_WID),
    .m_axi_A_in_0_WUSER(read_input_U0_m_axi_A_in_0_WUSER),
    .m_axi_A_in_0_ARVALID(read_input_U0_m_axi_A_in_0_ARVALID),
    .m_axi_A_in_0_ARREADY(A_in_0_ARREADY),
    .m_axi_A_in_0_ARADDR(read_input_U0_m_axi_A_in_0_ARADDR),
    .m_axi_A_in_0_ARID(read_input_U0_m_axi_A_in_0_ARID),
    .m_axi_A_in_0_ARLEN(read_input_U0_m_axi_A_in_0_ARLEN),
    .m_axi_A_in_0_ARSIZE(read_input_U0_m_axi_A_in_0_ARSIZE),
    .m_axi_A_in_0_ARBURST(read_input_U0_m_axi_A_in_0_ARBURST),
    .m_axi_A_in_0_ARLOCK(read_input_U0_m_axi_A_in_0_ARLOCK),
    .m_axi_A_in_0_ARCACHE(read_input_U0_m_axi_A_in_0_ARCACHE),
    .m_axi_A_in_0_ARPROT(read_input_U0_m_axi_A_in_0_ARPROT),
    .m_axi_A_in_0_ARQOS(read_input_U0_m_axi_A_in_0_ARQOS),
    .m_axi_A_in_0_ARREGION(read_input_U0_m_axi_A_in_0_ARREGION),
    .m_axi_A_in_0_ARUSER(read_input_U0_m_axi_A_in_0_ARUSER),
    .m_axi_A_in_0_RVALID(A_in_0_RVALID),
    .m_axi_A_in_0_RREADY(read_input_U0_m_axi_A_in_0_RREADY),
    .m_axi_A_in_0_RDATA(A_in_0_RDATA),
    .m_axi_A_in_0_RLAST(A_in_0_RLAST),
    .m_axi_A_in_0_RID(A_in_0_RID),
    .m_axi_A_in_0_RFIFONUM(A_in_0_RFIFONUM),
    .m_axi_A_in_0_RUSER(A_in_0_RUSER),
    .m_axi_A_in_0_RRESP(A_in_0_RRESP),
    .m_axi_A_in_0_BVALID(1'b0),
    .m_axi_A_in_0_BREADY(read_input_U0_m_axi_A_in_0_BREADY),
    .m_axi_A_in_0_BRESP(2'd0),
    .m_axi_A_in_0_BID(1'd0),
    .m_axi_A_in_0_BUSER(1'd0),
    .A_in1(A_in_r),
    .grid_initial_din(read_input_U0_grid_initial_din),
    .grid_initial_full_n(grid_initial_full_n),
    .grid_initial_write(read_input_U0_grid_initial_write),
    .grid_initial_num_data_valid(grid_initial_num_data_valid),
    .grid_initial_fifo_cap(grid_initial_fifo_cap)
);

top_kernel_compute compute_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(compute_U0_ap_start),
    .ap_done(compute_U0_ap_done),
    .ap_continue(compute_U0_ap_continue),
    .ap_idle(compute_U0_ap_idle),
    .ap_ready(compute_U0_ap_ready),
    .grid_initial_dout(grid_initial_dout),
    .grid_initial_empty_n(grid_initial_empty_n),
    .grid_initial_read(compute_U0_grid_initial_read),
    .grid_initial_num_data_valid(grid_initial_num_data_valid),
    .grid_initial_fifo_cap(grid_initial_fifo_cap),
    .grid_final_din(compute_U0_grid_final_din),
    .grid_final_full_n(grid_final_full_n),
    .grid_final_write(compute_U0_grid_final_write),
    .grid_final_num_data_valid(compute_U0_grid_final_num_data_valid),
    .grid_final_fifo_cap(compute_U0_grid_final_fifo_cap)
);

top_kernel_write_output write_output_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(write_output_U0_ap_start),
    .ap_done(write_output_U0_ap_done),
    .ap_continue(write_output_U0_ap_continue),
    .ap_idle(write_output_U0_ap_idle),
    .ap_ready(write_output_U0_ap_ready),
    .A_out1_dout(A_out_r_c_dout),
    .A_out1_empty_n(A_out_r_c_empty_n),
    .A_out1_read(write_output_U0_A_out1_read),
    .A_out1_num_data_valid(A_out_r_c_num_data_valid),
    .A_out1_fifo_cap(A_out_r_c_fifo_cap),
    .m_axi_A_out_0_AWVALID(write_output_U0_m_axi_A_out_0_AWVALID),
    .m_axi_A_out_0_AWREADY(A_out_0_AWREADY),
    .m_axi_A_out_0_AWADDR(write_output_U0_m_axi_A_out_0_AWADDR),
    .m_axi_A_out_0_AWID(write_output_U0_m_axi_A_out_0_AWID),
    .m_axi_A_out_0_AWLEN(write_output_U0_m_axi_A_out_0_AWLEN),
    .m_axi_A_out_0_AWSIZE(write_output_U0_m_axi_A_out_0_AWSIZE),
    .m_axi_A_out_0_AWBURST(write_output_U0_m_axi_A_out_0_AWBURST),
    .m_axi_A_out_0_AWLOCK(write_output_U0_m_axi_A_out_0_AWLOCK),
    .m_axi_A_out_0_AWCACHE(write_output_U0_m_axi_A_out_0_AWCACHE),
    .m_axi_A_out_0_AWPROT(write_output_U0_m_axi_A_out_0_AWPROT),
    .m_axi_A_out_0_AWQOS(write_output_U0_m_axi_A_out_0_AWQOS),
    .m_axi_A_out_0_AWREGION(write_output_U0_m_axi_A_out_0_AWREGION),
    .m_axi_A_out_0_AWUSER(write_output_U0_m_axi_A_out_0_AWUSER),
    .m_axi_A_out_0_WVALID(write_output_U0_m_axi_A_out_0_WVALID),
    .m_axi_A_out_0_WREADY(A_out_0_WREADY),
    .m_axi_A_out_0_WDATA(write_output_U0_m_axi_A_out_0_WDATA),
    .m_axi_A_out_0_WSTRB(write_output_U0_m_axi_A_out_0_WSTRB),
    .m_axi_A_out_0_WLAST(write_output_U0_m_axi_A_out_0_WLAST),
    .m_axi_A_out_0_WID(write_output_U0_m_axi_A_out_0_WID),
    .m_axi_A_out_0_WUSER(write_output_U0_m_axi_A_out_0_WUSER),
    .m_axi_A_out_0_ARVALID(write_output_U0_m_axi_A_out_0_ARVALID),
    .m_axi_A_out_0_ARREADY(1'b0),
    .m_axi_A_out_0_ARADDR(write_output_U0_m_axi_A_out_0_ARADDR),
    .m_axi_A_out_0_ARID(write_output_U0_m_axi_A_out_0_ARID),
    .m_axi_A_out_0_ARLEN(write_output_U0_m_axi_A_out_0_ARLEN),
    .m_axi_A_out_0_ARSIZE(write_output_U0_m_axi_A_out_0_ARSIZE),
    .m_axi_A_out_0_ARBURST(write_output_U0_m_axi_A_out_0_ARBURST),
    .m_axi_A_out_0_ARLOCK(write_output_U0_m_axi_A_out_0_ARLOCK),
    .m_axi_A_out_0_ARCACHE(write_output_U0_m_axi_A_out_0_ARCACHE),
    .m_axi_A_out_0_ARPROT(write_output_U0_m_axi_A_out_0_ARPROT),
    .m_axi_A_out_0_ARQOS(write_output_U0_m_axi_A_out_0_ARQOS),
    .m_axi_A_out_0_ARREGION(write_output_U0_m_axi_A_out_0_ARREGION),
    .m_axi_A_out_0_ARUSER(write_output_U0_m_axi_A_out_0_ARUSER),
    .m_axi_A_out_0_RVALID(1'b0),
    .m_axi_A_out_0_RREADY(write_output_U0_m_axi_A_out_0_RREADY),
    .m_axi_A_out_0_RDATA(32'd0),
    .m_axi_A_out_0_RLAST(1'b0),
    .m_axi_A_out_0_RID(1'd0),
    .m_axi_A_out_0_RFIFONUM(9'd0),
    .m_axi_A_out_0_RUSER(1'd0),
    .m_axi_A_out_0_RRESP(2'd0),
    .m_axi_A_out_0_BVALID(A_out_0_BVALID),
    .m_axi_A_out_0_BREADY(write_output_U0_m_axi_A_out_0_BREADY),
    .m_axi_A_out_0_BRESP(A_out_0_BRESP),
    .m_axi_A_out_0_BID(A_out_0_BID),
    .m_axi_A_out_0_BUSER(A_out_0_BUSER),
    .grid_final_dout(grid_final_dout),
    .grid_final_empty_n(grid_final_empty_n),
    .grid_final_read(write_output_U0_grid_final_read),
    .grid_final_num_data_valid(grid_final_num_data_valid),
    .grid_final_fifo_cap(grid_final_fifo_cap)
);

top_kernel_fifo_w64_d4_S A_out_r_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(entry_proc_U0_A_out_r_c_din),
    .if_full_n(A_out_r_c_full_n),
    .if_write(entry_proc_U0_A_out_r_c_write),
    .if_dout(A_out_r_c_dout),
    .if_empty_n(A_out_r_c_empty_n),
    .if_read(write_output_U0_A_out1_read),
    .if_num_data_valid(A_out_r_c_num_data_valid),
    .if_fifo_cap(A_out_r_c_fifo_cap)
);

top_kernel_fifo_w24_d2_S grid_initial_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(read_input_U0_grid_initial_din),
    .if_full_n(grid_initial_full_n),
    .if_write(read_input_U0_grid_initial_write),
    .if_dout(grid_initial_dout),
    .if_empty_n(grid_initial_empty_n),
    .if_read(compute_U0_grid_initial_read),
    .if_num_data_valid(grid_initial_num_data_valid),
    .if_fifo_cap(grid_initial_fifo_cap)
);

top_kernel_fifo_w24_d2_S grid_final_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(compute_U0_grid_final_din),
    .if_full_n(grid_final_full_n),
    .if_write(compute_U0_grid_final_write),
    .if_dout(grid_final_dout),
    .if_empty_n(grid_final_empty_n),
    .if_read(write_output_U0_grid_final_read),
    .if_num_data_valid(grid_final_num_data_valid),
    .if_fifo_cap(grid_final_fifo_cap)
);

top_kernel_start_for_write_output_U0 start_for_write_output_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_write_output_U0_din),
    .if_full_n(start_for_write_output_U0_full_n),
    .if_write(entry_proc_U0_start_write),
    .if_dout(start_for_write_output_U0_dout),
    .if_empty_n(start_for_write_output_U0_empty_n),
    .if_read(write_output_U0_ap_ready)
);

top_kernel_start_for_compute_U0 start_for_compute_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_compute_U0_din),
    .if_full_n(start_for_compute_U0_full_n),
    .if_write(read_input_U0_start_write),
    .if_dout(start_for_compute_U0_dout),
    .if_empty_n(start_for_compute_U0_empty_n),
    .if_read(compute_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_entry_proc_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_entry_proc_U0_ap_ready <= ap_sync_entry_proc_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_read_input_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_read_input_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_read_input_U0_ap_ready <= ap_sync_read_input_U0_ap_ready;
        end
    end
end

assign A_in_0_RID = 1'd0;

assign A_in_0_RLAST = 1'b0;

assign A_in_0_RRESP = 2'd0;

assign A_in_0_RUSER = 1'd0;

assign A_out_0_BID = 1'd0;

assign A_out_0_BRESP = 2'd0;

assign A_out_0_BUSER = 1'd0;

assign ap_done = write_output_U0_ap_done;

assign ap_idle = (write_output_U0_ap_idle & read_input_U0_ap_idle & entry_proc_U0_ap_idle & compute_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_entry_proc_U0_ap_ready = (entry_proc_U0_ap_ready | ap_sync_reg_entry_proc_U0_ap_ready);

assign ap_sync_read_input_U0_ap_ready = (read_input_U0_ap_ready | ap_sync_reg_read_input_U0_ap_ready);

assign ap_sync_ready = (ap_sync_read_input_U0_ap_ready & ap_sync_entry_proc_U0_ap_ready);

assign compute_U0_ap_continue = 1'b1;

assign compute_U0_ap_start = start_for_compute_U0_empty_n;

assign compute_U0_grid_final_fifo_cap = grid_final_fifo_cap;

assign compute_U0_grid_final_num_data_valid = grid_final_num_data_valid;

assign entry_proc_U0_ap_continue = 1'b1;

assign entry_proc_U0_ap_start = ((ap_sync_reg_entry_proc_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign read_input_U0_ap_continue = 1'b1;

assign read_input_U0_ap_start = ((ap_sync_reg_read_input_U0_ap_ready ^ 1'b1) & ap_start & 1'b1);

assign start_for_compute_U0_din = 1'b1;

assign start_for_write_output_U0_din = 1'b1;

assign write_output_U0_ap_continue = 1'b1;

assign write_output_U0_ap_start = start_for_write_output_U0_empty_n;

endmodule //top_kernel
