// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_k5_deferred_lighting (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        m_axi_gmem1_0_AWVALID,
        m_axi_gmem1_0_AWREADY,
        m_axi_gmem1_0_AWADDR,
        m_axi_gmem1_0_AWID,
        m_axi_gmem1_0_AWLEN,
        m_axi_gmem1_0_AWSIZE,
        m_axi_gmem1_0_AWBURST,
        m_axi_gmem1_0_AWLOCK,
        m_axi_gmem1_0_AWCACHE,
        m_axi_gmem1_0_AWPROT,
        m_axi_gmem1_0_AWQOS,
        m_axi_gmem1_0_AWREGION,
        m_axi_gmem1_0_AWUSER,
        m_axi_gmem1_0_WVALID,
        m_axi_gmem1_0_WREADY,
        m_axi_gmem1_0_WDATA,
        m_axi_gmem1_0_WSTRB,
        m_axi_gmem1_0_WLAST,
        m_axi_gmem1_0_WID,
        m_axi_gmem1_0_WUSER,
        m_axi_gmem1_0_ARVALID,
        m_axi_gmem1_0_ARREADY,
        m_axi_gmem1_0_ARADDR,
        m_axi_gmem1_0_ARID,
        m_axi_gmem1_0_ARLEN,
        m_axi_gmem1_0_ARSIZE,
        m_axi_gmem1_0_ARBURST,
        m_axi_gmem1_0_ARLOCK,
        m_axi_gmem1_0_ARCACHE,
        m_axi_gmem1_0_ARPROT,
        m_axi_gmem1_0_ARQOS,
        m_axi_gmem1_0_ARREGION,
        m_axi_gmem1_0_ARUSER,
        m_axi_gmem1_0_RVALID,
        m_axi_gmem1_0_RREADY,
        m_axi_gmem1_0_RDATA,
        m_axi_gmem1_0_RLAST,
        m_axi_gmem1_0_RID,
        m_axi_gmem1_0_RFIFONUM,
        m_axi_gmem1_0_RUSER,
        m_axi_gmem1_0_RRESP,
        m_axi_gmem1_0_BVALID,
        m_axi_gmem1_0_BREADY,
        m_axi_gmem1_0_BRESP,
        m_axi_gmem1_0_BID,
        m_axi_gmem1_0_BUSER,
        framebuffer,
        depth_buffer_address0,
        depth_buffer_ce0,
        depth_buffer_q0,
        normal_buffer_x_address0,
        normal_buffer_x_ce0,
        normal_buffer_x_q0,
        normal_buffer_y_address0,
        normal_buffer_y_ce0,
        normal_buffer_y_q0,
        normal_buffer_z_address0,
        normal_buffer_z_ce0,
        normal_buffer_z_q0
);

parameter    ap_ST_fsm_state1 = 13'd1;
parameter    ap_ST_fsm_state2 = 13'd2;
parameter    ap_ST_fsm_state3 = 13'd4;
parameter    ap_ST_fsm_state4 = 13'd8;
parameter    ap_ST_fsm_state5 = 13'd16;
parameter    ap_ST_fsm_state6 = 13'd32;
parameter    ap_ST_fsm_state7 = 13'd64;
parameter    ap_ST_fsm_state8 = 13'd128;
parameter    ap_ST_fsm_state9 = 13'd256;
parameter    ap_ST_fsm_state10 = 13'd512;
parameter    ap_ST_fsm_state11 = 13'd1024;
parameter    ap_ST_fsm_state12 = 13'd2048;
parameter    ap_ST_fsm_state13 = 13'd4096;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output   m_axi_gmem1_0_AWVALID;
input   m_axi_gmem1_0_AWREADY;
output  [63:0] m_axi_gmem1_0_AWADDR;
output  [0:0] m_axi_gmem1_0_AWID;
output  [31:0] m_axi_gmem1_0_AWLEN;
output  [2:0] m_axi_gmem1_0_AWSIZE;
output  [1:0] m_axi_gmem1_0_AWBURST;
output  [1:0] m_axi_gmem1_0_AWLOCK;
output  [3:0] m_axi_gmem1_0_AWCACHE;
output  [2:0] m_axi_gmem1_0_AWPROT;
output  [3:0] m_axi_gmem1_0_AWQOS;
output  [3:0] m_axi_gmem1_0_AWREGION;
output  [0:0] m_axi_gmem1_0_AWUSER;
output   m_axi_gmem1_0_WVALID;
input   m_axi_gmem1_0_WREADY;
output  [31:0] m_axi_gmem1_0_WDATA;
output  [3:0] m_axi_gmem1_0_WSTRB;
output   m_axi_gmem1_0_WLAST;
output  [0:0] m_axi_gmem1_0_WID;
output  [0:0] m_axi_gmem1_0_WUSER;
output   m_axi_gmem1_0_ARVALID;
input   m_axi_gmem1_0_ARREADY;
output  [63:0] m_axi_gmem1_0_ARADDR;
output  [0:0] m_axi_gmem1_0_ARID;
output  [31:0] m_axi_gmem1_0_ARLEN;
output  [2:0] m_axi_gmem1_0_ARSIZE;
output  [1:0] m_axi_gmem1_0_ARBURST;
output  [1:0] m_axi_gmem1_0_ARLOCK;
output  [3:0] m_axi_gmem1_0_ARCACHE;
output  [2:0] m_axi_gmem1_0_ARPROT;
output  [3:0] m_axi_gmem1_0_ARQOS;
output  [3:0] m_axi_gmem1_0_ARREGION;
output  [0:0] m_axi_gmem1_0_ARUSER;
input   m_axi_gmem1_0_RVALID;
output   m_axi_gmem1_0_RREADY;
input  [31:0] m_axi_gmem1_0_RDATA;
input   m_axi_gmem1_0_RLAST;
input  [0:0] m_axi_gmem1_0_RID;
input  [8:0] m_axi_gmem1_0_RFIFONUM;
input  [0:0] m_axi_gmem1_0_RUSER;
input  [1:0] m_axi_gmem1_0_RRESP;
input   m_axi_gmem1_0_BVALID;
output   m_axi_gmem1_0_BREADY;
input  [1:0] m_axi_gmem1_0_BRESP;
input  [0:0] m_axi_gmem1_0_BID;
input  [0:0] m_axi_gmem1_0_BUSER;
input  [63:0] framebuffer;
output  [11:0] depth_buffer_address0;
output   depth_buffer_ce0;
input  [31:0] depth_buffer_q0;
output  [11:0] normal_buffer_x_address0;
output   normal_buffer_x_ce0;
input  [31:0] normal_buffer_x_q0;
output  [11:0] normal_buffer_y_address0;
output   normal_buffer_y_ce0;
input  [31:0] normal_buffer_y_q0;
output  [11:0] normal_buffer_z_address0;
output   normal_buffer_z_ce0;
input  [31:0] normal_buffer_z_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg m_axi_gmem1_0_AWVALID;
reg m_axi_gmem1_0_WVALID;
reg m_axi_gmem1_0_BREADY;

(* fsm_encoding = "none" *) reg   [12:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    gmem1_blk_n_AW;
reg    gmem1_blk_n_W;
wire    ap_CS_fsm_state8;
reg    gmem1_blk_n_B;
wire    ap_CS_fsm_state13;
wire   [6:0] add_ln440_fu_277_p2;
reg   [6:0] add_ln440_reg_1262;
wire    ap_CS_fsm_state2;
wire   [11:0] tmp_4_fu_287_p3;
reg   [11:0] tmp_4_reg_1267;
wire   [6:0] add_ln441_fu_301_p2;
reg   [6:0] add_ln441_reg_1275;
wire    ap_CS_fsm_state3;
wire   [63:0] zext_ln444_1_fu_316_p1;
reg   [63:0] zext_ln444_1_reg_1280;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_ln446_fu_325_p2;
reg   [0:0] icmp_ln446_reg_1307;
wire  signed [31:0] dot_x_fu_571_p3;
reg  signed [31:0] dot_x_reg_1312;
wire    ap_CS_fsm_state5;
wire   [31:0] add_ln460_fu_622_p2;
reg   [31:0] add_ln460_reg_1318;
wire   [0:0] and_ln460_1_fu_684_p2;
reg   [0:0] and_ln460_1_reg_1323;
wire   [0:0] or_ln460_1_fu_708_p2;
reg   [0:0] or_ln460_1_reg_1328;
wire  signed [31:0] dot_z_fu_954_p3;
reg  signed [31:0] dot_z_reg_1333;
wire   [16:0] clamped_intensity_fu_1171_p3;
reg   [16:0] clamped_intensity_reg_1339;
wire    ap_CS_fsm_state6;
wire   [31:0] storemerge2_fu_1239_p3;
reg   [31:0] storemerge2_reg_1345;
wire    ap_CS_fsm_state7;
reg   [6:0] x_reg_226;
wire   [0:0] icmp_ln440_fu_271_p2;
wire   [0:0] icmp_ln441_fu_295_p2;
wire  signed [63:0] sext_ln440_fu_252_p1;
reg   [6:0] y_fu_144;
reg    depth_buffer_ce0_local;
reg    normal_buffer_x_ce0_local;
reg    normal_buffer_y_ce0_local;
reg    normal_buffer_z_ce0_local;
wire  signed [16:0] mul_ln460_fu_237_p1;
wire   [61:0] trunc_ln_fu_242_p4;
wire   [5:0] trunc_ln440_fu_283_p1;
wire   [11:0] zext_ln444_fu_307_p1;
wire   [11:0] add_ln444_fu_311_p2;
wire   [46:0] tmp_fu_331_p3;
wire   [43:0] tmp_1_fu_343_p3;
wire  signed [48:0] sext_ln457_fu_339_p1;
wire  signed [48:0] sext_ln457_1_fu_351_p1;
wire   [41:0] tmp_2_fu_361_p3;
wire   [48:0] add_ln457_1_fu_355_p2;
wire  signed [48:0] sext_ln457_2_fu_369_p1;
wire   [37:0] tmp_3_fu_379_p3;
wire   [48:0] add_ln457_2_fu_373_p2;
wire  signed [48:0] sext_ln457_3_fu_387_p1;
wire   [34:0] tmp_5_fu_397_p3;
wire   [48:0] sub_ln457_fu_391_p2;
wire  signed [48:0] sext_ln457_4_fu_405_p1;
wire   [32:0] tmp_6_fu_415_p3;
wire   [48:0] sub_ln457_1_fu_409_p2;
wire  signed [48:0] sext_ln457_5_fu_423_p1;
wire   [48:0] sub_ln457_2_fu_427_p2;
wire   [0:0] tmp_8_fu_451_p3;
wire   [31:0] trunc_ln1_fu_441_p4;
wire   [31:0] zext_ln457_fu_467_p1;
wire   [31:0] add_ln457_fu_471_p2;
wire   [0:0] tmp_10_fu_477_p3;
wire   [0:0] tmp_9_fu_459_p3;
wire   [0:0] xor_ln457_fu_485_p2;
wire   [0:0] xor_ln457_2_fu_497_p2;
wire   [0:0] tmp_7_fu_433_p3;
wire   [0:0] or_ln457_2_fu_503_p2;
wire   [0:0] xor_ln457_4_fu_509_p2;
wire   [0:0] xor_ln457_3_fu_521_p2;
wire   [0:0] or_ln457_fu_527_p2;
wire   [0:0] xor_ln457_1_fu_515_p2;
wire   [0:0] and_ln457_fu_491_p2;
wire   [0:0] or_ln457_3_fu_539_p2;
wire   [0:0] xor_ln457_5_fu_545_p2;
wire   [0:0] and_ln457_1_fu_533_p2;
wire   [0:0] and_ln457_2_fu_551_p2;
wire   [0:0] or_ln457_1_fu_565_p2;
wire   [31:0] select_ln457_fu_557_p3;
wire   [48:0] mul_ln460_fu_237_p2;
wire   [0:0] tmp_12_fu_602_p3;
wire   [31:0] trunc_ln2_fu_592_p4;
wire   [31:0] zext_ln460_fu_618_p1;
wire   [0:0] tmp_14_fu_628_p3;
wire   [0:0] tmp_13_fu_610_p3;
wire   [0:0] xor_ln460_fu_636_p2;
wire   [0:0] xor_ln460_2_fu_648_p2;
wire   [0:0] tmp_11_fu_584_p3;
wire   [0:0] or_ln460_2_fu_654_p2;
wire   [0:0] xor_ln460_4_fu_660_p2;
wire   [0:0] xor_ln460_3_fu_672_p2;
wire   [0:0] or_ln460_fu_678_p2;
wire   [0:0] xor_ln460_1_fu_666_p2;
wire   [0:0] and_ln460_fu_642_p2;
wire   [0:0] or_ln460_3_fu_690_p2;
wire   [0:0] xor_ln460_5_fu_696_p2;
wire   [0:0] and_ln460_2_fu_702_p2;
wire   [46:0] tmp_15_fu_714_p3;
wire   [43:0] tmp_16_fu_726_p3;
wire  signed [48:0] sext_ln463_fu_722_p1;
wire  signed [48:0] sext_ln463_1_fu_734_p1;
wire   [41:0] tmp_17_fu_744_p3;
wire   [48:0] add_ln463_1_fu_738_p2;
wire  signed [48:0] sext_ln463_2_fu_752_p1;
wire   [37:0] tmp_18_fu_762_p3;
wire   [48:0] add_ln463_2_fu_756_p2;
wire  signed [48:0] sext_ln463_3_fu_770_p1;
wire   [34:0] tmp_19_fu_780_p3;
wire   [48:0] sub_ln463_fu_774_p2;
wire  signed [48:0] sext_ln463_4_fu_788_p1;
wire   [32:0] tmp_20_fu_798_p3;
wire   [48:0] sub_ln463_1_fu_792_p2;
wire  signed [48:0] sext_ln463_5_fu_806_p1;
wire   [48:0] sub_ln463_2_fu_810_p2;
wire   [0:0] tmp_22_fu_834_p3;
wire   [31:0] trunc_ln3_fu_824_p4;
wire   [31:0] zext_ln463_fu_850_p1;
wire   [31:0] add_ln463_fu_854_p2;
wire   [0:0] tmp_24_fu_860_p3;
wire   [0:0] tmp_23_fu_842_p3;
wire   [0:0] xor_ln463_fu_868_p2;
wire   [0:0] xor_ln463_2_fu_880_p2;
wire   [0:0] tmp_21_fu_816_p3;
wire   [0:0] or_ln463_2_fu_886_p2;
wire   [0:0] xor_ln463_4_fu_892_p2;
wire   [0:0] xor_ln463_3_fu_904_p2;
wire   [0:0] or_ln463_fu_910_p2;
wire   [0:0] xor_ln463_1_fu_898_p2;
wire   [0:0] and_ln463_fu_874_p2;
wire   [0:0] or_ln463_3_fu_922_p2;
wire   [0:0] xor_ln463_5_fu_928_p2;
wire   [0:0] and_ln463_1_fu_916_p2;
wire   [0:0] and_ln463_2_fu_934_p2;
wire   [0:0] or_ln463_1_fu_948_p2;
wire   [31:0] select_ln463_fu_940_p3;
wire   [31:0] select_ln460_fu_962_p3;
wire  signed [31:0] dot_y_fu_969_p3;
wire  signed [32:0] sext_ln466_1_fu_978_p1;
wire  signed [32:0] sext_ln466_fu_975_p1;
wire   [32:0] add_ln466_fu_987_p2;
wire   [31:0] add_ln466_1_fu_982_p2;
wire   [0:0] tmp_25_fu_993_p3;
wire   [0:0] tmp_26_fu_1001_p3;
wire   [0:0] xor_ln466_fu_1009_p2;
wire   [0:0] and_ln466_fu_1015_p2;
wire   [0:0] xor_ln466_1_fu_1021_p2;
wire   [31:0] select_ln466_fu_1027_p3;
wire  signed [31:0] diffuse_fu_1035_p3;
wire  signed [32:0] sext_ln467_1_fu_1047_p1;
wire  signed [32:0] sext_ln467_fu_1043_p1;
wire   [32:0] add_ln467_fu_1055_p2;
wire   [31:0] add_ln467_1_fu_1050_p2;
wire   [0:0] tmp_27_fu_1061_p3;
wire   [0:0] tmp_28_fu_1069_p3;
wire   [0:0] xor_ln467_fu_1077_p2;
wire   [0:0] and_ln467_fu_1083_p2;
wire   [0:0] xor_ln467_1_fu_1089_p2;
wire   [31:0] select_ln467_fu_1095_p3;
wire   [31:0] diffuse_1_fu_1103_p3;
wire   [0:0] tmp_29_fu_1115_p3;
wire   [30:0] trunc_ln465_fu_1111_p1;
wire   [30:0] clamped_diffuse_fu_1123_p3;
wire   [31:0] zext_ln479_fu_1131_p1;
wire   [31:0] add_ln479_fu_1135_p2;
wire   [0:0] tmp_30_fu_1145_p3;
wire   [30:0] trunc_ln479_fu_1141_p1;
wire   [30:0] final_intensity_fu_1153_p3;
wire   [0:0] icmp_ln483_fu_1165_p2;
wire   [16:0] trunc_ln478_fu_1161_p1;
wire   [32:0] tmp_31_fu_1186_p3;
wire   [40:0] p_shl_fu_1179_p3;
wire   [40:0] zext_ln491_fu_1193_p1;
wire   [40:0] sub_ln491_fu_1197_p2;
wire   [55:0] zext_ln491_1_fu_1203_p1;
wire   [0:0] tmp_32_fu_1217_p3;
wire   [23:0] trunc_ln5_cast_fu_1207_p4;
wire   [23:0] zext_ln491_2_fu_1225_p1;
wire   [23:0] add_ln491_fu_1229_p2;
wire   [31:0] zext_ln491_3_fu_1235_p1;
reg   [12:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
wire    ap_ST_fsm_state11_blk;
wire    ap_ST_fsm_state12_blk;
reg    ap_ST_fsm_state13_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 13'd1;
#0 y_fu_144 = 7'd0;
end

top_kernel_mul_32s_17s_49_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 17 ),
    .dout_WIDTH( 49 ))
mul_32s_17s_49_1_1_U137(
    .din0(normal_buffer_y_q0),
    .din1(mul_ln460_fu_237_p1),
    .dout(mul_ln460_fu_237_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((m_axi_gmem1_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        x_reg_226 <= add_ln441_reg_1275;
    end else if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln440_fu_271_p2 == 1'd0))) begin
        x_reg_226 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((~((m_axi_gmem1_0_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        y_fu_144 <= 7'd0;
    end else if (((icmp_ln441_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        y_fu_144 <= add_ln440_reg_1262;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln440_reg_1262 <= add_ln440_fu_277_p2;
        tmp_4_reg_1267[11 : 6] <= tmp_4_fu_287_p3[11 : 6];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln441_reg_1275 <= add_ln441_fu_301_p2;
        zext_ln444_1_reg_1280[11 : 0] <= zext_ln444_1_fu_316_p1[11 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln460_reg_1318 <= add_ln460_fu_622_p2;
        and_ln460_1_reg_1323 <= and_ln460_1_fu_684_p2;
        dot_x_reg_1312 <= dot_x_fu_571_p3;
        dot_z_reg_1333 <= dot_z_fu_954_p3;
        or_ln460_1_reg_1328 <= or_ln460_1_fu_708_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        clamped_intensity_reg_1339 <= clamped_intensity_fu_1171_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        icmp_ln446_reg_1307 <= icmp_ln446_fu_325_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        storemerge2_reg_1345[23 : 0] <= storemerge2_fu_1239_p3[23 : 0];
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

assign ap_ST_fsm_state11_blk = 1'b0;

assign ap_ST_fsm_state12_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem1_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state13_blk = 1'b1;
    end else begin
        ap_ST_fsm_state13_blk = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_0_AWREADY == 1'b0) | (ap_start == 1'b0))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((m_axi_gmem1_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((m_axi_gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        depth_buffer_ce0_local = 1'b1;
    end else begin
        depth_buffer_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        gmem1_blk_n_AW = m_axi_gmem1_0_AWREADY;
    end else begin
        gmem1_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state13)) begin
        gmem1_blk_n_B = m_axi_gmem1_0_BVALID;
    end else begin
        gmem1_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        gmem1_blk_n_W = m_axi_gmem1_0_WREADY;
    end else begin
        gmem1_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if ((~((m_axi_gmem1_0_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
        m_axi_gmem1_0_AWVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
        m_axi_gmem1_0_BREADY = 1'b1;
    end else begin
        m_axi_gmem1_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((m_axi_gmem1_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
        m_axi_gmem1_0_WVALID = 1'b1;
    end else begin
        m_axi_gmem1_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        normal_buffer_x_ce0_local = 1'b1;
    end else begin
        normal_buffer_x_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        normal_buffer_y_ce0_local = 1'b1;
    end else begin
        normal_buffer_y_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        normal_buffer_z_ce0_local = 1'b1;
    end else begin
        normal_buffer_z_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((m_axi_gmem1_0_AWREADY == 1'b0) | (ap_start == 1'b0)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (icmp_ln440_fu_271_p2 == 1'd0))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln441_fu_295_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((m_axi_gmem1_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state8))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            if (((m_axi_gmem1_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state13))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln440_fu_277_p2 = (y_fu_144 + 7'd1);

assign add_ln441_fu_301_p2 = (x_reg_226 + 7'd1);

assign add_ln444_fu_311_p2 = (tmp_4_reg_1267 + zext_ln444_fu_307_p1);

assign add_ln457_1_fu_355_p2 = ($signed(sext_ln457_fu_339_p1) + $signed(sext_ln457_1_fu_351_p1));

assign add_ln457_2_fu_373_p2 = ($signed(add_ln457_1_fu_355_p2) + $signed(sext_ln457_2_fu_369_p1));

assign add_ln457_fu_471_p2 = (trunc_ln1_fu_441_p4 + zext_ln457_fu_467_p1);

assign add_ln460_fu_622_p2 = (trunc_ln2_fu_592_p4 + zext_ln460_fu_618_p1);

assign add_ln463_1_fu_738_p2 = ($signed(sext_ln463_fu_722_p1) + $signed(sext_ln463_1_fu_734_p1));

assign add_ln463_2_fu_756_p2 = ($signed(add_ln463_1_fu_738_p2) + $signed(sext_ln463_2_fu_752_p1));

assign add_ln463_fu_854_p2 = (trunc_ln3_fu_824_p4 + zext_ln463_fu_850_p1);

assign add_ln466_1_fu_982_p2 = ($signed(dot_y_fu_969_p3) + $signed(dot_x_reg_1312));

assign add_ln466_fu_987_p2 = ($signed(sext_ln466_1_fu_978_p1) + $signed(sext_ln466_fu_975_p1));

assign add_ln467_1_fu_1050_p2 = ($signed(dot_z_reg_1333) + $signed(diffuse_fu_1035_p3));

assign add_ln467_fu_1055_p2 = ($signed(sext_ln467_1_fu_1047_p1) + $signed(sext_ln467_fu_1043_p1));

assign add_ln479_fu_1135_p2 = (zext_ln479_fu_1131_p1 + 32'd6554);

assign add_ln491_fu_1229_p2 = (trunc_ln5_cast_fu_1207_p4 + zext_ln491_2_fu_1225_p1);

assign and_ln457_1_fu_533_p2 = (xor_ln457_1_fu_515_p2 & or_ln457_fu_527_p2);

assign and_ln457_2_fu_551_p2 = (xor_ln457_5_fu_545_p2 & tmp_7_fu_433_p3);

assign and_ln457_fu_491_p2 = (xor_ln457_fu_485_p2 & tmp_9_fu_459_p3);

assign and_ln460_1_fu_684_p2 = (xor_ln460_1_fu_666_p2 & or_ln460_fu_678_p2);

assign and_ln460_2_fu_702_p2 = (xor_ln460_5_fu_696_p2 & tmp_11_fu_584_p3);

assign and_ln460_fu_642_p2 = (xor_ln460_fu_636_p2 & tmp_13_fu_610_p3);

assign and_ln463_1_fu_916_p2 = (xor_ln463_1_fu_898_p2 & or_ln463_fu_910_p2);

assign and_ln463_2_fu_934_p2 = (xor_ln463_5_fu_928_p2 & tmp_21_fu_816_p3);

assign and_ln463_fu_874_p2 = (xor_ln463_fu_868_p2 & tmp_23_fu_842_p3);

assign and_ln466_fu_1015_p2 = (xor_ln466_fu_1009_p2 & tmp_26_fu_1001_p3);

assign and_ln467_fu_1083_p2 = (xor_ln467_fu_1077_p2 & tmp_28_fu_1069_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign clamped_diffuse_fu_1123_p3 = ((tmp_29_fu_1115_p3[0:0] == 1'b1) ? 31'd0 : trunc_ln465_fu_1111_p1);

assign clamped_intensity_fu_1171_p3 = ((icmp_ln483_fu_1165_p2[0:0] == 1'b1) ? 17'd65536 : trunc_ln478_fu_1161_p1);

assign depth_buffer_address0 = zext_ln444_1_fu_316_p1;

assign depth_buffer_ce0 = depth_buffer_ce0_local;

assign diffuse_1_fu_1103_p3 = ((xor_ln467_1_fu_1089_p2[0:0] == 1'b1) ? select_ln467_fu_1095_p3 : add_ln467_1_fu_1050_p2);

assign diffuse_fu_1035_p3 = ((xor_ln466_1_fu_1021_p2[0:0] == 1'b1) ? select_ln466_fu_1027_p3 : add_ln466_1_fu_982_p2);

assign dot_x_fu_571_p3 = ((or_ln457_1_fu_565_p2[0:0] == 1'b1) ? select_ln457_fu_557_p3 : add_ln457_fu_471_p2);

assign dot_y_fu_969_p3 = ((or_ln460_1_reg_1328[0:0] == 1'b1) ? select_ln460_fu_962_p3 : add_ln460_reg_1318);

assign dot_z_fu_954_p3 = ((or_ln463_1_fu_948_p2[0:0] == 1'b1) ? select_ln463_fu_940_p3 : add_ln463_fu_854_p2);

assign final_intensity_fu_1153_p3 = ((tmp_30_fu_1145_p3[0:0] == 1'b1) ? 31'd2147483647 : trunc_ln479_fu_1141_p1);

assign icmp_ln440_fu_271_p2 = ((y_fu_144 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln441_fu_295_p2 = ((x_reg_226 == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln446_fu_325_p2 = ((depth_buffer_q0 == 32'd655294464) ? 1'b1 : 1'b0);

assign icmp_ln483_fu_1165_p2 = ((final_intensity_fu_1153_p3 > 31'd65536) ? 1'b1 : 1'b0);

assign m_axi_gmem1_0_ARADDR = 64'd0;

assign m_axi_gmem1_0_ARBURST = 2'd0;

assign m_axi_gmem1_0_ARCACHE = 4'd0;

assign m_axi_gmem1_0_ARID = 1'd0;

assign m_axi_gmem1_0_ARLEN = 32'd0;

assign m_axi_gmem1_0_ARLOCK = 2'd0;

assign m_axi_gmem1_0_ARPROT = 3'd0;

assign m_axi_gmem1_0_ARQOS = 4'd0;

assign m_axi_gmem1_0_ARREGION = 4'd0;

assign m_axi_gmem1_0_ARSIZE = 3'd0;

assign m_axi_gmem1_0_ARUSER = 1'd0;

assign m_axi_gmem1_0_ARVALID = 1'b0;

assign m_axi_gmem1_0_AWADDR = sext_ln440_fu_252_p1;

assign m_axi_gmem1_0_AWBURST = 2'd0;

assign m_axi_gmem1_0_AWCACHE = 4'd0;

assign m_axi_gmem1_0_AWID = 1'd0;

assign m_axi_gmem1_0_AWLEN = 64'd4096;

assign m_axi_gmem1_0_AWLOCK = 2'd0;

assign m_axi_gmem1_0_AWPROT = 3'd0;

assign m_axi_gmem1_0_AWQOS = 4'd0;

assign m_axi_gmem1_0_AWREGION = 4'd0;

assign m_axi_gmem1_0_AWSIZE = 3'd0;

assign m_axi_gmem1_0_AWUSER = 1'd0;

assign m_axi_gmem1_0_RREADY = 1'b0;

assign m_axi_gmem1_0_WDATA = storemerge2_reg_1345;

assign m_axi_gmem1_0_WID = 1'd0;

assign m_axi_gmem1_0_WLAST = 1'b0;

assign m_axi_gmem1_0_WSTRB = 4'd15;

assign m_axi_gmem1_0_WUSER = 1'd0;

assign mul_ln460_fu_237_p1 = 49'd562949953383498;

assign normal_buffer_x_address0 = zext_ln444_1_reg_1280;

assign normal_buffer_x_ce0 = normal_buffer_x_ce0_local;

assign normal_buffer_y_address0 = zext_ln444_1_reg_1280;

assign normal_buffer_y_ce0 = normal_buffer_y_ce0_local;

assign normal_buffer_z_address0 = zext_ln444_1_reg_1280;

assign normal_buffer_z_ce0 = normal_buffer_z_ce0_local;

assign or_ln457_1_fu_565_p2 = (and_ln457_2_fu_551_p2 | and_ln457_1_fu_533_p2);

assign or_ln457_2_fu_503_p2 = (xor_ln457_2_fu_497_p2 | tmp_10_fu_477_p3);

assign or_ln457_3_fu_539_p2 = (tmp_10_fu_477_p3 | and_ln457_fu_491_p2);

assign or_ln457_fu_527_p2 = (xor_ln457_3_fu_521_p2 | tmp_10_fu_477_p3);

assign or_ln460_1_fu_708_p2 = (and_ln460_2_fu_702_p2 | and_ln460_1_fu_684_p2);

assign or_ln460_2_fu_654_p2 = (xor_ln460_2_fu_648_p2 | tmp_14_fu_628_p3);

assign or_ln460_3_fu_690_p2 = (tmp_14_fu_628_p3 | and_ln460_fu_642_p2);

assign or_ln460_fu_678_p2 = (xor_ln460_3_fu_672_p2 | tmp_14_fu_628_p3);

assign or_ln463_1_fu_948_p2 = (and_ln463_2_fu_934_p2 | and_ln463_1_fu_916_p2);

assign or_ln463_2_fu_886_p2 = (xor_ln463_2_fu_880_p2 | tmp_24_fu_860_p3);

assign or_ln463_3_fu_922_p2 = (tmp_24_fu_860_p3 | and_ln463_fu_874_p2);

assign or_ln463_fu_910_p2 = (xor_ln463_3_fu_904_p2 | tmp_24_fu_860_p3);

assign p_shl_fu_1179_p3 = {{clamped_intensity_reg_1339}, {24'd0}};

assign select_ln457_fu_557_p3 = ((and_ln457_1_fu_533_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln460_fu_962_p3 = ((and_ln460_1_reg_1323[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln463_fu_940_p3 = ((and_ln463_1_fu_916_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln466_fu_1027_p3 = ((and_ln466_fu_1015_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign select_ln467_fu_1095_p3 = ((and_ln467_fu_1083_p2[0:0] == 1'b1) ? 32'd2147483647 : 32'd2147483648);

assign sext_ln440_fu_252_p1 = $signed(trunc_ln_fu_242_p4);

assign sext_ln457_1_fu_351_p1 = $signed(tmp_1_fu_343_p3);

assign sext_ln457_2_fu_369_p1 = $signed(tmp_2_fu_361_p3);

assign sext_ln457_3_fu_387_p1 = $signed(tmp_3_fu_379_p3);

assign sext_ln457_4_fu_405_p1 = $signed(tmp_5_fu_397_p3);

assign sext_ln457_5_fu_423_p1 = $signed(tmp_6_fu_415_p3);

assign sext_ln457_fu_339_p1 = $signed(tmp_fu_331_p3);

assign sext_ln463_1_fu_734_p1 = $signed(tmp_16_fu_726_p3);

assign sext_ln463_2_fu_752_p1 = $signed(tmp_17_fu_744_p3);

assign sext_ln463_3_fu_770_p1 = $signed(tmp_18_fu_762_p3);

assign sext_ln463_4_fu_788_p1 = $signed(tmp_19_fu_780_p3);

assign sext_ln463_5_fu_806_p1 = $signed(tmp_20_fu_798_p3);

assign sext_ln463_fu_722_p1 = $signed(tmp_15_fu_714_p3);

assign sext_ln466_1_fu_978_p1 = dot_y_fu_969_p3;

assign sext_ln466_fu_975_p1 = dot_x_reg_1312;

assign sext_ln467_1_fu_1047_p1 = dot_z_reg_1333;

assign sext_ln467_fu_1043_p1 = diffuse_fu_1035_p3;

assign storemerge2_fu_1239_p3 = ((icmp_ln446_reg_1307[0:0] == 1'b1) ? 32'd0 : zext_ln491_3_fu_1235_p1);

assign sub_ln457_1_fu_409_p2 = ($signed(sub_ln457_fu_391_p2) - $signed(sext_ln457_4_fu_405_p1));

assign sub_ln457_2_fu_427_p2 = ($signed(sub_ln457_1_fu_409_p2) - $signed(sext_ln457_5_fu_423_p1));

assign sub_ln457_fu_391_p2 = ($signed(add_ln457_2_fu_373_p2) - $signed(sext_ln457_3_fu_387_p1));

assign sub_ln463_1_fu_792_p2 = ($signed(sub_ln463_fu_774_p2) - $signed(sext_ln463_4_fu_788_p1));

assign sub_ln463_2_fu_810_p2 = ($signed(sub_ln463_1_fu_792_p2) - $signed(sext_ln463_5_fu_806_p1));

assign sub_ln463_fu_774_p2 = ($signed(add_ln463_2_fu_756_p2) - $signed(sext_ln463_3_fu_770_p1));

assign sub_ln491_fu_1197_p2 = (p_shl_fu_1179_p3 - zext_ln491_fu_1193_p1);

assign tmp_10_fu_477_p3 = add_ln457_fu_471_p2[32'd31];

assign tmp_11_fu_584_p3 = mul_ln460_fu_237_p2[32'd48];

assign tmp_12_fu_602_p3 = mul_ln460_fu_237_p2[32'd15];

assign tmp_13_fu_610_p3 = mul_ln460_fu_237_p2[32'd47];

assign tmp_14_fu_628_p3 = add_ln460_fu_622_p2[32'd31];

assign tmp_15_fu_714_p3 = {{normal_buffer_z_q0}, {15'd0}};

assign tmp_16_fu_726_p3 = {{normal_buffer_z_q0}, {12'd0}};

assign tmp_17_fu_744_p3 = {{normal_buffer_z_q0}, {10'd0}};

assign tmp_18_fu_762_p3 = {{normal_buffer_z_q0}, {6'd0}};

assign tmp_19_fu_780_p3 = {{normal_buffer_z_q0}, {3'd0}};

assign tmp_1_fu_343_p3 = {{normal_buffer_x_q0}, {12'd0}};

assign tmp_20_fu_798_p3 = {{normal_buffer_z_q0}, {1'd0}};

assign tmp_21_fu_816_p3 = sub_ln463_2_fu_810_p2[32'd48];

assign tmp_22_fu_834_p3 = sub_ln463_2_fu_810_p2[32'd15];

assign tmp_23_fu_842_p3 = sub_ln463_2_fu_810_p2[32'd47];

assign tmp_24_fu_860_p3 = add_ln463_fu_854_p2[32'd31];

assign tmp_25_fu_993_p3 = add_ln466_fu_987_p2[32'd32];

assign tmp_26_fu_1001_p3 = add_ln466_1_fu_982_p2[32'd31];

assign tmp_27_fu_1061_p3 = add_ln467_fu_1055_p2[32'd32];

assign tmp_28_fu_1069_p3 = add_ln467_1_fu_1050_p2[32'd31];

assign tmp_29_fu_1115_p3 = diffuse_1_fu_1103_p3[32'd31];

assign tmp_2_fu_361_p3 = {{normal_buffer_x_q0}, {10'd0}};

assign tmp_30_fu_1145_p3 = add_ln479_fu_1135_p2[32'd31];

assign tmp_31_fu_1186_p3 = {{clamped_intensity_reg_1339}, {16'd0}};

assign tmp_32_fu_1217_p3 = zext_ln491_1_fu_1203_p1[32'd15];

assign tmp_3_fu_379_p3 = {{normal_buffer_x_q0}, {6'd0}};

assign tmp_4_fu_287_p3 = {{trunc_ln440_fu_283_p1}, {6'd0}};

assign tmp_5_fu_397_p3 = {{normal_buffer_x_q0}, {3'd0}};

assign tmp_6_fu_415_p3 = {{normal_buffer_x_q0}, {1'd0}};

assign tmp_7_fu_433_p3 = sub_ln457_2_fu_427_p2[32'd48];

assign tmp_8_fu_451_p3 = sub_ln457_2_fu_427_p2[32'd15];

assign tmp_9_fu_459_p3 = sub_ln457_2_fu_427_p2[32'd47];

assign tmp_fu_331_p3 = {{normal_buffer_x_q0}, {15'd0}};

assign trunc_ln1_fu_441_p4 = {{sub_ln457_2_fu_427_p2[47:16]}};

assign trunc_ln2_fu_592_p4 = {{mul_ln460_fu_237_p2[47:16]}};

assign trunc_ln3_fu_824_p4 = {{sub_ln463_2_fu_810_p2[47:16]}};

assign trunc_ln440_fu_283_p1 = y_fu_144[5:0];

assign trunc_ln465_fu_1111_p1 = diffuse_1_fu_1103_p3[30:0];

assign trunc_ln478_fu_1161_p1 = final_intensity_fu_1153_p3[16:0];

assign trunc_ln479_fu_1141_p1 = add_ln479_fu_1135_p2[30:0];

assign trunc_ln5_cast_fu_1207_p4 = {{sub_ln491_fu_1197_p2[39:16]}};

assign trunc_ln_fu_242_p4 = {{framebuffer[63:2]}};

assign xor_ln457_1_fu_515_p2 = (tmp_7_fu_433_p3 ^ 1'd1);

assign xor_ln457_2_fu_497_p2 = (tmp_9_fu_459_p3 ^ 1'd1);

assign xor_ln457_3_fu_521_p2 = (xor_ln457_4_fu_509_p2 ^ 1'd1);

assign xor_ln457_4_fu_509_p2 = (tmp_7_fu_433_p3 ^ or_ln457_2_fu_503_p2);

assign xor_ln457_5_fu_545_p2 = (or_ln457_3_fu_539_p2 ^ 1'd1);

assign xor_ln457_fu_485_p2 = (tmp_10_fu_477_p3 ^ 1'd1);

assign xor_ln460_1_fu_666_p2 = (tmp_11_fu_584_p3 ^ 1'd1);

assign xor_ln460_2_fu_648_p2 = (tmp_13_fu_610_p3 ^ 1'd1);

assign xor_ln460_3_fu_672_p2 = (xor_ln460_4_fu_660_p2 ^ 1'd1);

assign xor_ln460_4_fu_660_p2 = (tmp_11_fu_584_p3 ^ or_ln460_2_fu_654_p2);

assign xor_ln460_5_fu_696_p2 = (or_ln460_3_fu_690_p2 ^ 1'd1);

assign xor_ln460_fu_636_p2 = (tmp_14_fu_628_p3 ^ 1'd1);

assign xor_ln463_1_fu_898_p2 = (tmp_21_fu_816_p3 ^ 1'd1);

assign xor_ln463_2_fu_880_p2 = (tmp_23_fu_842_p3 ^ 1'd1);

assign xor_ln463_3_fu_904_p2 = (xor_ln463_4_fu_892_p2 ^ 1'd1);

assign xor_ln463_4_fu_892_p2 = (tmp_21_fu_816_p3 ^ or_ln463_2_fu_886_p2);

assign xor_ln463_5_fu_928_p2 = (or_ln463_3_fu_922_p2 ^ 1'd1);

assign xor_ln463_fu_868_p2 = (tmp_24_fu_860_p3 ^ 1'd1);

assign xor_ln466_1_fu_1021_p2 = (tmp_26_fu_1001_p3 ^ tmp_25_fu_993_p3);

assign xor_ln466_fu_1009_p2 = (tmp_25_fu_993_p3 ^ 1'd1);

assign xor_ln467_1_fu_1089_p2 = (tmp_28_fu_1069_p3 ^ tmp_27_fu_1061_p3);

assign xor_ln467_fu_1077_p2 = (tmp_27_fu_1061_p3 ^ 1'd1);

assign zext_ln444_1_fu_316_p1 = add_ln444_fu_311_p2;

assign zext_ln444_fu_307_p1 = x_reg_226;

assign zext_ln457_fu_467_p1 = tmp_8_fu_451_p3;

assign zext_ln460_fu_618_p1 = tmp_12_fu_602_p3;

assign zext_ln463_fu_850_p1 = tmp_22_fu_834_p3;

assign zext_ln479_fu_1131_p1 = clamped_diffuse_fu_1123_p3;

assign zext_ln491_1_fu_1203_p1 = sub_ln491_fu_1197_p2;

assign zext_ln491_2_fu_1225_p1 = tmp_32_fu_1217_p3;

assign zext_ln491_3_fu_1235_p1 = add_ln491_fu_1229_p2;

assign zext_ln491_fu_1193_p1 = tmp_31_fu_1186_p3;

always @ (posedge ap_clk) begin
    tmp_4_reg_1267[5:0] <= 6'b000000;
    zext_ln444_1_reg_1280[63:12] <= 52'b0000000000000000000000000000000000000000000000000000;
    storemerge2_reg_1345[31:24] <= 8'b00000000;
end

endmodule //top_kernel_k5_deferred_lighting
