-- ==============================================================
-- Generated by Vitis HLS v2025.1.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity top_kernel_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    stream_in_address0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    stream_in_ce0 : OUT STD_LOGIC;
    stream_in_q0 : IN STD_LOGIC_VECTOR (23 downto 0);
    cur_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_ce0 : OUT STD_LOGIC;
    cur_we0 : OUT STD_LOGIC;
    cur_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_1_ce0 : OUT STD_LOGIC;
    cur_1_we0 : OUT STD_LOGIC;
    cur_1_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_2_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_2_ce0 : OUT STD_LOGIC;
    cur_2_we0 : OUT STD_LOGIC;
    cur_2_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_3_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_3_ce0 : OUT STD_LOGIC;
    cur_3_we0 : OUT STD_LOGIC;
    cur_3_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_4_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_4_ce0 : OUT STD_LOGIC;
    cur_4_we0 : OUT STD_LOGIC;
    cur_4_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_5_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_5_ce0 : OUT STD_LOGIC;
    cur_5_we0 : OUT STD_LOGIC;
    cur_5_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_6_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_6_ce0 : OUT STD_LOGIC;
    cur_6_we0 : OUT STD_LOGIC;
    cur_6_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_7_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_7_ce0 : OUT STD_LOGIC;
    cur_7_we0 : OUT STD_LOGIC;
    cur_7_d0 : OUT STD_LOGIC_VECTOR (23 downto 0);
    cur_8_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    cur_8_ce0 : OUT STD_LOGIC;
    cur_8_we0 : OUT STD_LOGIC;
    cur_8_d0 : OUT STD_LOGIC_VECTOR (23 downto 0) );
end;


architecture behav of top_kernel_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv17_0 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv17_10000 : STD_LOGIC_VECTOR (16 downto 0) := "10000000000000000";
    constant ap_const_lv17_1 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000001";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_100 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_lv19_2AB : STD_LOGIC_VECTOR (18 downto 0) := "0000000001010101011";
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_12 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010010";
    constant ap_const_lv9_3 : STD_LOGIC_VECTOR (8 downto 0) := "000000011";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv13_56 : STD_LOGIC_VECTOR (12 downto 0) := "0000001010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln27_fu_246_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter1_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln27_fu_276_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459 : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter3_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter4_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter5_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter6_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter7_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter8_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter9_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter10_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_reg_459_pp0_iter11_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal select_ln27_1_fu_284_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal trunc_ln30_fu_292_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471 : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln30_reg_471_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter2_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_52_reg_476_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal zext_ln30_1_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln30_3_fu_400_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_70 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal add_ln28_fu_328_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_74 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    signal indvar_flatten_fu_78 : STD_LOGIC_VECTOR (16 downto 0) := "00000000000000000";
    signal add_ln27_1_fu_252_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal stream_in_ce0_local : STD_LOGIC;
    signal cur_4_we0_local : STD_LOGIC;
    signal trunc_ln27_fu_396_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal trunc_ln28_fu_412_p1 : STD_LOGIC_VECTOR (1 downto 0);
    signal cur_4_ce0_local : STD_LOGIC;
    signal cur_3_we0_local : STD_LOGIC;
    signal cur_3_ce0_local : STD_LOGIC;
    signal cur_5_we0_local : STD_LOGIC;
    signal cur_5_ce0_local : STD_LOGIC;
    signal cur_1_we0_local : STD_LOGIC;
    signal cur_1_ce0_local : STD_LOGIC;
    signal cur_we0_local : STD_LOGIC;
    signal cur_ce0_local : STD_LOGIC;
    signal cur_2_we0_local : STD_LOGIC;
    signal cur_2_ce0_local : STD_LOGIC;
    signal cur_7_we0_local : STD_LOGIC;
    signal cur_7_ce0_local : STD_LOGIC;
    signal cur_6_we0_local : STD_LOGIC;
    signal cur_6_ce0_local : STD_LOGIC;
    signal cur_8_we0_local : STD_LOGIC;
    signal cur_8_ce0_local : STD_LOGIC;
    signal icmp_ln28_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln27_fu_264_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln27_fu_300_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln27_fu_300_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln27_fu_300_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal grp_fu_316_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal grp_fu_322_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_fu_352_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln30_fu_359_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln30_fu_362_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln28_fu_376_p0 : STD_LOGIC_VECTOR (8 downto 0);
    signal mul_ln28_fu_376_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln28_fu_376_p2 : STD_LOGIC_VECTOR (18 downto 0);
    signal tmp_53_fu_382_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_316_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_425_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_322_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal grp_fu_425_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_425_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal grp_fu_425_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal grp_fu_425_p00 : STD_LOGIC_VECTOR (12 downto 0);
    signal grp_fu_425_p20 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln27_fu_300_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal mul_ln28_fu_376_p00 : STD_LOGIC_VECTOR (18 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component top_kernel_mul_9ns_11ns_19_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (18 downto 0) );
    end component;


    component top_kernel_urem_9ns_3ns_2_13_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (8 downto 0);
        din1 : IN STD_LOGIC_VECTOR (2 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (1 downto 0) );
    end component;


    component top_kernel_mac_muladd_8ns_7ns_8ns_13_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (6 downto 0);
        din2 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (12 downto 0) );
    end component;


    component top_kernel_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mul_9ns_11ns_19_1_1_U6 : component top_kernel_mul_9ns_11ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln27_fu_300_p0,
        din1 => mul_ln27_fu_300_p1,
        dout => mul_ln27_fu_300_p2);

    urem_9ns_3ns_2_13_1_U7 : component top_kernel_urem_9ns_3ns_2_13_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln27_1_fu_284_p3,
        din1 => grp_fu_316_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_316_p2);

    urem_9ns_3ns_2_13_1_U8 : component top_kernel_urem_9ns_3ns_2_13_1
    generic map (
        ID => 1,
        NUM_STAGE => 13,
        din0_WIDTH => 9,
        din1_WIDTH => 3,
        dout_WIDTH => 2)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => select_ln27_fu_276_p3,
        din1 => grp_fu_322_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_322_p2);

    mul_9ns_11ns_19_1_1_U9 : component top_kernel_mul_9ns_11ns_19_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 9,
        din1_WIDTH => 11,
        dout_WIDTH => 19)
    port map (
        din0 => mul_ln28_fu_376_p0,
        din1 => mul_ln28_fu_376_p1,
        dout => mul_ln28_fu_376_p2);

    mac_muladd_8ns_7ns_8ns_13_4_1_U10 : component top_kernel_mac_muladd_8ns_7ns_8ns_13_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 7,
        din2_WIDTH => 8,
        dout_WIDTH => 13)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_425_p0,
        din1 => grp_fu_425_p1,
        din2 => grp_fu_425_p2,
        ce => ap_const_logic_1,
        dout => grp_fu_425_p3);

    flow_control_loop_pipe_sequential_init_U : component top_kernel_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter1_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter1_stage0)) then 
                    ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    i_fu_74_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_74 <= ap_const_lv9_0;
                elsif (((icmp_ln27_fu_246_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    i_fu_74 <= select_ln27_1_fu_284_p3;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten_fu_78_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten_fu_78 <= ap_const_lv17_0;
                elsif (((icmp_ln27_fu_246_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    indvar_flatten_fu_78 <= add_ln27_1_fu_252_p2;
                end if;
            end if; 
        end if;
    end process;

    j_fu_70_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_70 <= ap_const_lv9_0;
                elsif (((icmp_ln27_fu_246_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1))) then 
                    j_fu_70 <= add_ln28_fu_328_p2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                select_ln27_reg_459_pp0_iter10_reg <= select_ln27_reg_459_pp0_iter9_reg;
                select_ln27_reg_459_pp0_iter11_reg <= select_ln27_reg_459_pp0_iter10_reg;
                select_ln27_reg_459_pp0_iter2_reg <= select_ln27_reg_459;
                select_ln27_reg_459_pp0_iter3_reg <= select_ln27_reg_459_pp0_iter2_reg;
                select_ln27_reg_459_pp0_iter4_reg <= select_ln27_reg_459_pp0_iter3_reg;
                select_ln27_reg_459_pp0_iter5_reg <= select_ln27_reg_459_pp0_iter4_reg;
                select_ln27_reg_459_pp0_iter6_reg <= select_ln27_reg_459_pp0_iter5_reg;
                select_ln27_reg_459_pp0_iter7_reg <= select_ln27_reg_459_pp0_iter6_reg;
                select_ln27_reg_459_pp0_iter8_reg <= select_ln27_reg_459_pp0_iter7_reg;
                select_ln27_reg_459_pp0_iter9_reg <= select_ln27_reg_459_pp0_iter8_reg;
                tmp_52_reg_476_pp0_iter2_reg <= tmp_52_reg_476;
                tmp_52_reg_476_pp0_iter3_reg <= tmp_52_reg_476_pp0_iter2_reg;
                tmp_52_reg_476_pp0_iter4_reg <= tmp_52_reg_476_pp0_iter3_reg;
                tmp_52_reg_476_pp0_iter5_reg <= tmp_52_reg_476_pp0_iter4_reg;
                tmp_52_reg_476_pp0_iter6_reg <= tmp_52_reg_476_pp0_iter5_reg;
                tmp_52_reg_476_pp0_iter7_reg <= tmp_52_reg_476_pp0_iter6_reg;
                tmp_52_reg_476_pp0_iter8_reg <= tmp_52_reg_476_pp0_iter7_reg;
                tmp_52_reg_476_pp0_iter9_reg <= tmp_52_reg_476_pp0_iter8_reg;
                trunc_ln30_reg_471_pp0_iter10_reg <= trunc_ln30_reg_471_pp0_iter9_reg;
                trunc_ln30_reg_471_pp0_iter11_reg <= trunc_ln30_reg_471_pp0_iter10_reg;
                trunc_ln30_reg_471_pp0_iter2_reg <= trunc_ln30_reg_471;
                trunc_ln30_reg_471_pp0_iter3_reg <= trunc_ln30_reg_471_pp0_iter2_reg;
                trunc_ln30_reg_471_pp0_iter4_reg <= trunc_ln30_reg_471_pp0_iter3_reg;
                trunc_ln30_reg_471_pp0_iter5_reg <= trunc_ln30_reg_471_pp0_iter4_reg;
                trunc_ln30_reg_471_pp0_iter6_reg <= trunc_ln30_reg_471_pp0_iter5_reg;
                trunc_ln30_reg_471_pp0_iter7_reg <= trunc_ln30_reg_471_pp0_iter6_reg;
                trunc_ln30_reg_471_pp0_iter8_reg <= trunc_ln30_reg_471_pp0_iter7_reg;
                trunc_ln30_reg_471_pp0_iter9_reg <= trunc_ln30_reg_471_pp0_iter8_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
                select_ln27_reg_459 <= select_ln27_fu_276_p3;
                tmp_52_reg_476 <= mul_ln27_fu_300_p2(18 downto 11);
                trunc_ln30_reg_471 <= trunc_ln30_fu_292_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln27_1_fu_252_p2 <= std_logic_vector(unsigned(indvar_flatten_fu_78) + unsigned(ap_const_lv17_1));
    add_ln27_fu_264_p2 <= std_logic_vector(unsigned(i_fu_74) + unsigned(ap_const_lv9_1));
    add_ln28_fu_328_p2 <= std_logic_vector(unsigned(select_ln27_fu_276_p3) + unsigned(ap_const_lv9_1));
    add_ln30_fu_362_p2 <= std_logic_vector(unsigned(tmp_fu_352_p3) + unsigned(zext_ln30_fu_359_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter1_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_subdone, icmp_ln27_fu_246_p2)
    begin
        if (((icmp_ln27_fu_246_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter1_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter1_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;

    cur_1_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_1_ce0 <= cur_1_ce0_local;

    cur_1_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_1_ce0_local <= ap_const_logic_1;
        else 
            cur_1_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_1_d0 <= stream_in_q0;
    cur_1_we0 <= cur_1_we0_local;

    cur_1_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_1) and (trunc_ln27_fu_396_p1 = ap_const_lv2_0))) then 
            cur_1_we0_local <= ap_const_logic_1;
        else 
            cur_1_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_2_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_2_ce0 <= cur_2_ce0_local;

    cur_2_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_2_ce0_local <= ap_const_logic_1;
        else 
            cur_2_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_2_d0 <= stream_in_q0;
    cur_2_we0 <= cur_2_we0_local;

    cur_2_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if ((not((trunc_ln28_fu_412_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_412_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln27_fu_396_p1 = ap_const_lv2_0))) then 
            cur_2_we0_local <= ap_const_logic_1;
        else 
            cur_2_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_3_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_3_ce0 <= cur_3_ce0_local;

    cur_3_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_3_ce0_local <= ap_const_logic_1;
        else 
            cur_3_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_3_d0 <= stream_in_q0;
    cur_3_we0 <= cur_3_we0_local;

    cur_3_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_0) and (trunc_ln27_fu_396_p1 = ap_const_lv2_1))) then 
            cur_3_we0_local <= ap_const_logic_1;
        else 
            cur_3_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_4_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_4_ce0 <= cur_4_ce0_local;

    cur_4_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_4_ce0_local <= ap_const_logic_1;
        else 
            cur_4_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_4_d0 <= stream_in_q0;
    cur_4_we0 <= cur_4_we0_local;

    cur_4_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_1) and (trunc_ln27_fu_396_p1 = ap_const_lv2_1))) then 
            cur_4_we0_local <= ap_const_logic_1;
        else 
            cur_4_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_5_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_5_ce0 <= cur_5_ce0_local;

    cur_5_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_5_ce0_local <= ap_const_logic_1;
        else 
            cur_5_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_5_d0 <= stream_in_q0;
    cur_5_we0 <= cur_5_we0_local;

    cur_5_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if ((not((trunc_ln28_fu_412_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_412_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln27_fu_396_p1 = ap_const_lv2_1))) then 
            cur_5_we0_local <= ap_const_logic_1;
        else 
            cur_5_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_6_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_6_ce0 <= cur_6_ce0_local;

    cur_6_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_6_ce0_local <= ap_const_logic_1;
        else 
            cur_6_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_6_d0 <= stream_in_q0;
    cur_6_we0 <= cur_6_we0_local;

    cur_6_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if ((not((trunc_ln27_fu_396_p1 = ap_const_lv2_0)) and not((trunc_ln27_fu_396_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_0))) then 
            cur_6_we0_local <= ap_const_logic_1;
        else 
            cur_6_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_7_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_7_ce0 <= cur_7_ce0_local;

    cur_7_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_7_ce0_local <= ap_const_logic_1;
        else 
            cur_7_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_7_d0 <= stream_in_q0;
    cur_7_we0 <= cur_7_we0_local;

    cur_7_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if ((not((trunc_ln27_fu_396_p1 = ap_const_lv2_0)) and not((trunc_ln27_fu_396_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_1))) then 
            cur_7_we0_local <= ap_const_logic_1;
        else 
            cur_7_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_8_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_8_ce0 <= cur_8_ce0_local;

    cur_8_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_8_ce0_local <= ap_const_logic_1;
        else 
            cur_8_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_8_d0 <= stream_in_q0;
    cur_8_we0 <= cur_8_we0_local;

    cur_8_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if ((not((trunc_ln27_fu_396_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_412_p1 = ap_const_lv2_0)) and not((trunc_ln28_fu_412_p1 = ap_const_lv2_1)) and not((trunc_ln27_fu_396_p1 = ap_const_lv2_1)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_8_we0_local <= ap_const_logic_1;
        else 
            cur_8_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_address0 <= zext_ln30_3_fu_400_p1(13 - 1 downto 0);
    cur_ce0 <= cur_ce0_local;

    cur_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            cur_ce0_local <= ap_const_logic_1;
        else 
            cur_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    cur_d0 <= stream_in_q0;
    cur_we0 <= cur_we0_local;

    cur_we0_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln27_fu_396_p1, trunc_ln28_fu_412_p1)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln28_fu_412_p1 = ap_const_lv2_0) and (trunc_ln27_fu_396_p1 = ap_const_lv2_0))) then 
            cur_we0_local <= ap_const_logic_1;
        else 
            cur_we0_local <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_316_p1 <= ap_const_lv9_3(3 - 1 downto 0);
    grp_fu_322_p1 <= ap_const_lv9_3(3 - 1 downto 0);
    grp_fu_425_p0 <= grp_fu_425_p00(8 - 1 downto 0);
    grp_fu_425_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_52_reg_476_pp0_iter9_reg),13));
    grp_fu_425_p1 <= ap_const_lv13_56(7 - 1 downto 0);
    grp_fu_425_p2 <= grp_fu_425_p20(8 - 1 downto 0);
    grp_fu_425_p20 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_53_fu_382_p4),13));
    icmp_ln27_fu_246_p2 <= "1" when (indvar_flatten_fu_78 = ap_const_lv17_10000) else "0";
    icmp_ln28_fu_270_p2 <= "1" when (j_fu_70 = ap_const_lv9_100) else "0";
    mul_ln27_fu_300_p0 <= mul_ln27_fu_300_p00(9 - 1 downto 0);
    mul_ln27_fu_300_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_1_fu_284_p3),19));
    mul_ln27_fu_300_p1 <= ap_const_lv19_2AB(11 - 1 downto 0);
    mul_ln28_fu_376_p0 <= mul_ln28_fu_376_p00(9 - 1 downto 0);
    mul_ln28_fu_376_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_reg_459_pp0_iter11_reg),19));
    mul_ln28_fu_376_p1 <= ap_const_lv19_2AB(11 - 1 downto 0);
    select_ln27_1_fu_284_p3 <= 
        add_ln27_fu_264_p2 when (icmp_ln28_fu_270_p2(0) = '1') else 
        i_fu_74;
    select_ln27_fu_276_p3 <= 
        ap_const_lv9_0 when (icmp_ln28_fu_270_p2(0) = '1') else 
        j_fu_70;
    stream_in_address0 <= zext_ln30_1_fu_368_p1(16 - 1 downto 0);
    stream_in_ce0 <= stream_in_ce0_local;

    stream_in_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter12, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter12 = ap_const_logic_1))) then 
            stream_in_ce0_local <= ap_const_logic_1;
        else 
            stream_in_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    tmp_53_fu_382_p4 <= mul_ln28_fu_376_p2(18 downto 11);
    tmp_fu_352_p3 <= (trunc_ln30_reg_471_pp0_iter11_reg & ap_const_lv8_0);
    trunc_ln27_fu_396_p1 <= grp_fu_316_p2(2 - 1 downto 0);
    trunc_ln28_fu_412_p1 <= grp_fu_322_p2(2 - 1 downto 0);
    trunc_ln30_fu_292_p1 <= select_ln27_1_fu_284_p3(8 - 1 downto 0);
    zext_ln30_1_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln30_fu_362_p2),64));
    zext_ln30_3_fu_400_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(grp_fu_425_p3),64));
    zext_ln30_fu_359_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln27_reg_459_pp0_iter11_reg),16));
end behav;
