-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1.1 (lin64) Build 6233196 Thu Sep 11 21:27:11 MDT 2025
-- Date        : Fri Feb 20 10:24:03 2026
-- Host        : ece-linlabsrv01 running 64-bit Red Hat Enterprise Linux release 8.10 (Ootpa)
-- Command     : write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix
--               decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_A_in_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_in_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_in_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_in_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_in_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_ARREADY : in STD_LOGIC;
    m_axi_A_in_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_in_ARVALID : out STD_LOGIC;
    m_axi_A_in_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_in_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_in_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_in_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_in_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_AWREADY : in STD_LOGIC;
    m_axi_A_in_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_in_AWVALID : out STD_LOGIC;
    m_axi_A_in_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_in_BREADY : out STD_LOGIC;
    m_axi_A_in_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_BVALID : in STD_LOGIC;
    m_axi_A_in_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_in_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_in_RLAST : in STD_LOGIC;
    m_axi_A_in_RREADY : out STD_LOGIC;
    m_axi_A_in_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_in_RVALID : in STD_LOGIC;
    m_axi_A_in_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_in_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_in_WLAST : out STD_LOGIC;
    m_axi_A_in_WREADY : in STD_LOGIC;
    m_axi_A_in_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_in_WVALID : out STD_LOGIC;
    m_axi_A_out_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_out_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_out_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_out_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_out_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_ARREADY : in STD_LOGIC;
    m_axi_A_out_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_out_ARVALID : out STD_LOGIC;
    m_axi_A_out_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_A_out_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_out_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_A_out_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_out_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_AWREADY : in STD_LOGIC;
    m_axi_A_out_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_A_out_AWVALID : out STD_LOGIC;
    m_axi_A_out_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_out_BREADY : out STD_LOGIC;
    m_axi_A_out_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_BVALID : in STD_LOGIC;
    m_axi_A_out_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_out_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_out_RLAST : in STD_LOGIC;
    m_axi_A_out_RREADY : out STD_LOGIC;
    m_axi_A_out_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_A_out_RVALID : in STD_LOGIC;
    m_axi_A_out_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_A_out_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_A_out_WLAST : out STD_LOGIC;
    m_axi_A_out_WREADY : in STD_LOGIC;
    m_axi_A_out_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_A_out_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,top_kernel,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "bd_0_hls_inst_0,top_kernel,{x_ipProduct=Vivado 2025.1.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=top_kernel,x_ipVersion=1.0,x_ipCoreRevision=2114488821,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_A_IN_ID_WIDTH=1,C_M_AXI_A_IN_ADDR_WIDTH=64,C_M_AXI_A_IN_DATA_WIDTH=32,C_M_AXI_A_IN_AWUSER_WIDTH=1,C_M_AXI_A_IN_ARUSER_WIDTH=1,C_M_AXI_A_IN_WUSER_WIDTH=1,C_M_AXI_A_IN_RUSER_WIDTH=1,C_M_AXI_A_IN_BUSER_WIDTH=1,C_M_AXI_A_IN_USER_VALUE=0x00000000,C_M_AXI_A_IN_PROT_VALUE=000,C_M_AXI_A_IN_CACHE_VALUE=0011,C_M_AXI_A_OUT_ID_WIDTH=1,C_M_AXI_A_OUT_ADDR_WIDTH=64,C_M_AXI_A_OUT_DATA_WIDTH=32,C_M_AXI_A_OUT_AWUSER_WIDTH=1,C_M_AXI_A_OUT_ARUSER_WIDTH=1,C_M_AXI_A_OUT_WUSER_WIDTH=1,C_M_AXI_A_OUT_RUSER_WIDTH=1,C_M_AXI_A_OUT_BUSER_WIDTH=1,C_M_AXI_A_OUT_USER_VALUE=0x00000000,C_M_AXI_A_OUT_PROT_VALUE=000,C_M_AXI_A_OUT_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix : entity is "yes";
end decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix;

architecture stub of decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_A_in_ARADDR[63:0],m_axi_A_in_ARBURST[1:0],m_axi_A_in_ARCACHE[3:0],m_axi_A_in_ARID[0:0],m_axi_A_in_ARLEN[7:0],m_axi_A_in_ARLOCK[1:0],m_axi_A_in_ARPROT[2:0],m_axi_A_in_ARQOS[3:0],m_axi_A_in_ARREADY,m_axi_A_in_ARREGION[3:0],m_axi_A_in_ARSIZE[2:0],m_axi_A_in_ARVALID,m_axi_A_in_AWADDR[63:0],m_axi_A_in_AWBURST[1:0],m_axi_A_in_AWCACHE[3:0],m_axi_A_in_AWID[0:0],m_axi_A_in_AWLEN[7:0],m_axi_A_in_AWLOCK[1:0],m_axi_A_in_AWPROT[2:0],m_axi_A_in_AWQOS[3:0],m_axi_A_in_AWREADY,m_axi_A_in_AWREGION[3:0],m_axi_A_in_AWSIZE[2:0],m_axi_A_in_AWVALID,m_axi_A_in_BID[0:0],m_axi_A_in_BREADY,m_axi_A_in_BRESP[1:0],m_axi_A_in_BVALID,m_axi_A_in_RDATA[31:0],m_axi_A_in_RID[0:0],m_axi_A_in_RLAST,m_axi_A_in_RREADY,m_axi_A_in_RRESP[1:0],m_axi_A_in_RVALID,m_axi_A_in_WDATA[31:0],m_axi_A_in_WID[0:0],m_axi_A_in_WLAST,m_axi_A_in_WREADY,m_axi_A_in_WSTRB[3:0],m_axi_A_in_WVALID,m_axi_A_out_ARADDR[63:0],m_axi_A_out_ARBURST[1:0],m_axi_A_out_ARCACHE[3:0],m_axi_A_out_ARID[0:0],m_axi_A_out_ARLEN[7:0],m_axi_A_out_ARLOCK[1:0],m_axi_A_out_ARPROT[2:0],m_axi_A_out_ARQOS[3:0],m_axi_A_out_ARREADY,m_axi_A_out_ARREGION[3:0],m_axi_A_out_ARSIZE[2:0],m_axi_A_out_ARVALID,m_axi_A_out_AWADDR[63:0],m_axi_A_out_AWBURST[1:0],m_axi_A_out_AWCACHE[3:0],m_axi_A_out_AWID[0:0],m_axi_A_out_AWLEN[7:0],m_axi_A_out_AWLOCK[1:0],m_axi_A_out_AWPROT[2:0],m_axi_A_out_AWQOS[3:0],m_axi_A_out_AWREADY,m_axi_A_out_AWREGION[3:0],m_axi_A_out_AWSIZE[2:0],m_axi_A_out_AWVALID,m_axi_A_out_BID[0:0],m_axi_A_out_BREADY,m_axi_A_out_BRESP[1:0],m_axi_A_out_BVALID,m_axi_A_out_RDATA[31:0],m_axi_A_out_RID[0:0],m_axi_A_out_RLAST,m_axi_A_out_RREADY,m_axi_A_out_RRESP[1:0],m_axi_A_out_RVALID,m_axi_A_out_WDATA[31:0],m_axi_A_out_WID[0:0],m_axi_A_out_WLAST,m_axi_A_out_WREADY,m_axi_A_out_WSTRB[3:0],m_axi_A_out_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000.0, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_A_in:m_axi_A_out, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARADDR";
  attribute X_INTERFACE_MODE of m_axi_A_in_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_A_in_ARADDR : signal is "XIL_INTERFACENAME m_axi_A_in, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARBURST";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARID";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARLEN";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARPROT";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARQOS";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARREADY";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARREGION";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_in_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in ARVALID";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWADDR";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWBURST";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWID";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWLEN";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWPROT";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWQOS";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWREADY";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWREGION";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_in_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in AWVALID";
  attribute X_INTERFACE_INFO of m_axi_A_in_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in BID";
  attribute X_INTERFACE_INFO of m_axi_A_in_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in BREADY";
  attribute X_INTERFACE_INFO of m_axi_A_in_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in BRESP";
  attribute X_INTERFACE_INFO of m_axi_A_in_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in BVALID";
  attribute X_INTERFACE_INFO of m_axi_A_in_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RDATA";
  attribute X_INTERFACE_INFO of m_axi_A_in_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RID";
  attribute X_INTERFACE_INFO of m_axi_A_in_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RLAST";
  attribute X_INTERFACE_INFO of m_axi_A_in_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RREADY";
  attribute X_INTERFACE_INFO of m_axi_A_in_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RRESP";
  attribute X_INTERFACE_INFO of m_axi_A_in_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in RVALID";
  attribute X_INTERFACE_INFO of m_axi_A_in_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WDATA";
  attribute X_INTERFACE_INFO of m_axi_A_in_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WID";
  attribute X_INTERFACE_INFO of m_axi_A_in_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WLAST";
  attribute X_INTERFACE_INFO of m_axi_A_in_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WREADY";
  attribute X_INTERFACE_INFO of m_axi_A_in_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WSTRB";
  attribute X_INTERFACE_INFO of m_axi_A_in_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_in WVALID";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARADDR";
  attribute X_INTERFACE_MODE of m_axi_A_out_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_A_out_ARADDR : signal is "XIL_INTERFACENAME m_axi_A_out, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARBURST";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARID";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARLEN";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARPROT";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARQOS";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARREADY";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARREGION";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_out_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out ARVALID";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWADDR";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWBURST";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWID";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWLEN";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWPROT";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWQOS";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWREADY";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWREGION";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_A_out_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out AWVALID";
  attribute X_INTERFACE_INFO of m_axi_A_out_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out BID";
  attribute X_INTERFACE_INFO of m_axi_A_out_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out BREADY";
  attribute X_INTERFACE_INFO of m_axi_A_out_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out BRESP";
  attribute X_INTERFACE_INFO of m_axi_A_out_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out BVALID";
  attribute X_INTERFACE_INFO of m_axi_A_out_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RDATA";
  attribute X_INTERFACE_INFO of m_axi_A_out_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RID";
  attribute X_INTERFACE_INFO of m_axi_A_out_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RLAST";
  attribute X_INTERFACE_INFO of m_axi_A_out_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RREADY";
  attribute X_INTERFACE_INFO of m_axi_A_out_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RRESP";
  attribute X_INTERFACE_INFO of m_axi_A_out_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out RVALID";
  attribute X_INTERFACE_INFO of m_axi_A_out_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WDATA";
  attribute X_INTERFACE_INFO of m_axi_A_out_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WID";
  attribute X_INTERFACE_INFO of m_axi_A_out_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WLAST";
  attribute X_INTERFACE_INFO of m_axi_A_out_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WREADY";
  attribute X_INTERFACE_INFO of m_axi_A_out_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WSTRB";
  attribute X_INTERFACE_INFO of m_axi_A_out_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_A_out WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "top_kernel,Vivado 2025.1.1";
begin
end;
