// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_compute_Pipeline_VITIS_LOOP_60_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        bufferA_address0,
        bufferA_ce0,
        bufferA_we0,
        bufferA_d0,
        bufferA_address1,
        bufferA_ce1,
        bufferA_q1,
        bufferA_1_address0,
        bufferA_1_ce0,
        bufferA_1_we0,
        bufferA_1_d0,
        bufferA_1_address1,
        bufferA_1_ce1,
        bufferA_1_q1,
        bufferA_2_address0,
        bufferA_2_ce0,
        bufferA_2_we0,
        bufferA_2_d0,
        bufferA_2_address1,
        bufferA_2_ce1,
        bufferA_2_q1,
        bufferA_3_address0,
        bufferA_3_ce0,
        bufferA_3_we0,
        bufferA_3_d0,
        bufferA_3_address1,
        bufferA_3_ce1,
        bufferA_3_q1,
        bufferB_address0,
        bufferB_ce0,
        bufferB_we0,
        bufferB_d0,
        bufferB_address1,
        bufferB_ce1,
        bufferB_q1,
        bufferB_1_address0,
        bufferB_1_ce0,
        bufferB_1_we0,
        bufferB_1_d0,
        bufferB_1_address1,
        bufferB_1_ce1,
        bufferB_1_q1,
        bufferB_2_address0,
        bufferB_2_ce0,
        bufferB_2_we0,
        bufferB_2_d0,
        bufferB_2_address1,
        bufferB_2_ce1,
        bufferB_2_q1,
        bufferB_3_address0,
        bufferB_3_ce0,
        bufferB_3_we0,
        bufferB_3_d0,
        bufferB_3_address1,
        bufferB_3_ce1,
        bufferB_3_q1,
        empty
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] bufferA_address0;
output   bufferA_ce0;
output   bufferA_we0;
output  [23:0] bufferA_d0;
output  [13:0] bufferA_address1;
output   bufferA_ce1;
input  [23:0] bufferA_q1;
output  [13:0] bufferA_1_address0;
output   bufferA_1_ce0;
output   bufferA_1_we0;
output  [23:0] bufferA_1_d0;
output  [13:0] bufferA_1_address1;
output   bufferA_1_ce1;
input  [23:0] bufferA_1_q1;
output  [13:0] bufferA_2_address0;
output   bufferA_2_ce0;
output   bufferA_2_we0;
output  [23:0] bufferA_2_d0;
output  [13:0] bufferA_2_address1;
output   bufferA_2_ce1;
input  [23:0] bufferA_2_q1;
output  [13:0] bufferA_3_address0;
output   bufferA_3_ce0;
output   bufferA_3_we0;
output  [23:0] bufferA_3_d0;
output  [13:0] bufferA_3_address1;
output   bufferA_3_ce1;
input  [23:0] bufferA_3_q1;
output  [13:0] bufferB_address0;
output   bufferB_ce0;
output   bufferB_we0;
output  [23:0] bufferB_d0;
output  [13:0] bufferB_address1;
output   bufferB_ce1;
input  [23:0] bufferB_q1;
output  [13:0] bufferB_1_address0;
output   bufferB_1_ce0;
output   bufferB_1_we0;
output  [23:0] bufferB_1_d0;
output  [13:0] bufferB_1_address1;
output   bufferB_1_ce1;
input  [23:0] bufferB_1_q1;
output  [13:0] bufferB_2_address0;
output   bufferB_2_ce0;
output   bufferB_2_we0;
output  [23:0] bufferB_2_d0;
output  [13:0] bufferB_2_address1;
output   bufferB_2_ce1;
input  [23:0] bufferB_2_q1;
output  [13:0] bufferB_3_address0;
output   bufferB_3_ce0;
output   bufferB_3_we0;
output  [23:0] bufferB_3_d0;
output  [13:0] bufferB_3_address1;
output   bufferB_3_ce1;
input  [23:0] bufferB_3_q1;
input  [0:0] empty;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln60_fu_208_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] tmp_reg_314;
wire    ap_block_pp0_stage0_11001;
wire   [0:0] trunc_ln60_fu_220_p1;
reg   [0:0] trunc_ln60_reg_321;
reg   [13:0] bufferA_addr_reg_329;
reg   [13:0] bufferA_1_addr_reg_335;
reg   [13:0] bufferA_2_addr_reg_341;
reg   [13:0] bufferA_3_addr_reg_347;
reg   [13:0] bufferB_addr_1_reg_353;
reg   [13:0] bufferB_1_addr_1_reg_359;
reg   [13:0] bufferB_2_addr_1_reg_365;
reg   [13:0] bufferB_3_addr_1_reg_371;
wire   [63:0] zext_ln66_fu_242_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln67_fu_258_p1;
reg   [8:0] i_fu_54;
wire   [8:0] add_ln60_fu_214_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_2;
reg    bufferA_ce1_local;
reg    bufferA_we0_local;
wire   [23:0] select_ln66_fu_289_p3;
reg    bufferA_ce0_local;
reg    bufferA_2_ce1_local;
reg    bufferA_2_we0_local;
reg    bufferA_2_ce0_local;
reg    bufferA_1_ce1_local;
reg    bufferA_1_we0_local;
wire   [23:0] select_ln67_fu_298_p3;
reg    bufferA_1_ce0_local;
reg    bufferA_3_ce1_local;
reg    bufferA_3_we0_local;
reg    bufferA_3_ce0_local;
reg    bufferB_ce1_local;
reg    bufferB_we0_local;
wire   [23:0] select_ln63_fu_271_p3;
reg    bufferB_ce0_local;
reg    bufferB_2_ce1_local;
reg    bufferB_2_we0_local;
reg    bufferB_2_ce0_local;
reg    bufferB_1_ce1_local;
reg    bufferB_1_we0_local;
wire   [23:0] select_ln64_fu_280_p3;
reg    bufferB_1_ce0_local;
reg    bufferB_3_ce1_local;
reg    bufferB_3_we0_local;
reg    bufferB_3_ce0_local;
wire   [6:0] lshr_ln3_fu_224_p4;
wire   [13:0] tmp_s_fu_234_p3;
wire   [13:0] tmp_14_fu_250_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_54 = 9'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln60_fu_208_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_54 <= add_ln60_fu_214_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_1_addr_reg_335[13 : 7] <= zext_ln67_fu_258_p1[13 : 7];
        bufferA_2_addr_reg_341[13 : 7] <= zext_ln66_fu_242_p1[13 : 7];
        bufferA_3_addr_reg_347[13 : 7] <= zext_ln67_fu_258_p1[13 : 7];
        bufferA_addr_reg_329[13 : 7] <= zext_ln66_fu_242_p1[13 : 7];
        bufferB_1_addr_1_reg_359[13 : 7] <= zext_ln67_fu_258_p1[13 : 7];
        bufferB_2_addr_1_reg_365[13 : 7] <= zext_ln66_fu_242_p1[13 : 7];
        bufferB_3_addr_1_reg_371[13 : 7] <= zext_ln67_fu_258_p1[13 : 7];
        bufferB_addr_1_reg_353[13 : 7] <= zext_ln66_fu_242_p1[13 : 7];
        trunc_ln60_reg_321 <= trunc_ln60_fu_220_p1;
    end
end

always @ (*) begin
    if (((icmp_ln60_fu_208_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_54;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_1_ce0_local = 1'b1;
    end else begin
        bufferA_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_1_ce1_local = 1'b1;
    end else begin
        bufferA_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd0) & (tmp_reg_314 == 1'd1))) begin
        bufferA_1_we0_local = 1'b1;
    end else begin
        bufferA_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_2_ce0_local = 1'b1;
    end else begin
        bufferA_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_2_ce1_local = 1'b1;
    end else begin
        bufferA_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd1) & (tmp_reg_314 == 1'd1))) begin
        bufferA_2_we0_local = 1'b1;
    end else begin
        bufferA_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_3_ce0_local = 1'b1;
    end else begin
        bufferA_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_3_ce1_local = 1'b1;
    end else begin
        bufferA_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd1) & (tmp_reg_314 == 1'd1))) begin
        bufferA_3_we0_local = 1'b1;
    end else begin
        bufferA_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_ce0_local = 1'b1;
    end else begin
        bufferA_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferA_ce1_local = 1'b1;
    end else begin
        bufferA_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd0) & (tmp_reg_314 == 1'd1))) begin
        bufferA_we0_local = 1'b1;
    end else begin
        bufferA_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_1_ce0_local = 1'b1;
    end else begin
        bufferB_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_1_ce1_local = 1'b1;
    end else begin
        bufferB_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd0) & (tmp_reg_314 == 1'd0))) begin
        bufferB_1_we0_local = 1'b1;
    end else begin
        bufferB_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_2_ce0_local = 1'b1;
    end else begin
        bufferB_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_2_ce1_local = 1'b1;
    end else begin
        bufferB_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd1) & (tmp_reg_314 == 1'd0))) begin
        bufferB_2_we0_local = 1'b1;
    end else begin
        bufferB_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_3_ce0_local = 1'b1;
    end else begin
        bufferB_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_3_ce1_local = 1'b1;
    end else begin
        bufferB_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd1) & (tmp_reg_314 == 1'd0))) begin
        bufferB_3_we0_local = 1'b1;
    end else begin
        bufferB_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_ce0_local = 1'b1;
    end else begin
        bufferB_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        bufferB_ce1_local = 1'b1;
    end else begin
        bufferB_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (trunc_ln60_reg_321 == 1'd0) & (tmp_reg_314 == 1'd0))) begin
        bufferB_we0_local = 1'b1;
    end else begin
        bufferB_we0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln60_fu_214_p2 = (ap_sig_allocacmp_i_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign bufferA_1_address0 = bufferA_1_addr_reg_335;

assign bufferA_1_address1 = zext_ln67_fu_258_p1;

assign bufferA_1_ce0 = bufferA_1_ce0_local;

assign bufferA_1_ce1 = bufferA_1_ce1_local;

assign bufferA_1_d0 = select_ln67_fu_298_p3;

assign bufferA_1_we0 = bufferA_1_we0_local;

assign bufferA_2_address0 = bufferA_2_addr_reg_341;

assign bufferA_2_address1 = zext_ln66_fu_242_p1;

assign bufferA_2_ce0 = bufferA_2_ce0_local;

assign bufferA_2_ce1 = bufferA_2_ce1_local;

assign bufferA_2_d0 = select_ln66_fu_289_p3;

assign bufferA_2_we0 = bufferA_2_we0_local;

assign bufferA_3_address0 = bufferA_3_addr_reg_347;

assign bufferA_3_address1 = zext_ln67_fu_258_p1;

assign bufferA_3_ce0 = bufferA_3_ce0_local;

assign bufferA_3_ce1 = bufferA_3_ce1_local;

assign bufferA_3_d0 = select_ln67_fu_298_p3;

assign bufferA_3_we0 = bufferA_3_we0_local;

assign bufferA_address0 = bufferA_addr_reg_329;

assign bufferA_address1 = zext_ln66_fu_242_p1;

assign bufferA_ce0 = bufferA_ce0_local;

assign bufferA_ce1 = bufferA_ce1_local;

assign bufferA_d0 = select_ln66_fu_289_p3;

assign bufferA_we0 = bufferA_we0_local;

assign bufferB_1_address0 = bufferB_1_addr_1_reg_359;

assign bufferB_1_address1 = zext_ln67_fu_258_p1;

assign bufferB_1_ce0 = bufferB_1_ce0_local;

assign bufferB_1_ce1 = bufferB_1_ce1_local;

assign bufferB_1_d0 = select_ln64_fu_280_p3;

assign bufferB_1_we0 = bufferB_1_we0_local;

assign bufferB_2_address0 = bufferB_2_addr_1_reg_365;

assign bufferB_2_address1 = zext_ln66_fu_242_p1;

assign bufferB_2_ce0 = bufferB_2_ce0_local;

assign bufferB_2_ce1 = bufferB_2_ce1_local;

assign bufferB_2_d0 = select_ln63_fu_271_p3;

assign bufferB_2_we0 = bufferB_2_we0_local;

assign bufferB_3_address0 = bufferB_3_addr_1_reg_371;

assign bufferB_3_address1 = zext_ln67_fu_258_p1;

assign bufferB_3_ce0 = bufferB_3_ce0_local;

assign bufferB_3_ce1 = bufferB_3_ce1_local;

assign bufferB_3_d0 = select_ln64_fu_280_p3;

assign bufferB_3_we0 = bufferB_3_we0_local;

assign bufferB_address0 = bufferB_addr_1_reg_353;

assign bufferB_address1 = zext_ln66_fu_242_p1;

assign bufferB_ce0 = bufferB_ce0_local;

assign bufferB_ce1 = bufferB_ce1_local;

assign bufferB_d0 = select_ln63_fu_271_p3;

assign bufferB_we0 = bufferB_we0_local;

assign icmp_ln60_fu_208_p2 = ((ap_sig_allocacmp_i_2 == 9'd256) ? 1'b1 : 1'b0);

assign lshr_ln3_fu_224_p4 = {{ap_sig_allocacmp_i_2[7:1]}};

assign select_ln63_fu_271_p3 = ((trunc_ln60_reg_321[0:0] == 1'b1) ? bufferA_2_q1 : bufferA_q1);

assign select_ln64_fu_280_p3 = ((trunc_ln60_reg_321[0:0] == 1'b1) ? bufferA_3_q1 : bufferA_1_q1);

assign select_ln66_fu_289_p3 = ((trunc_ln60_reg_321[0:0] == 1'b1) ? bufferB_2_q1 : bufferB_q1);

assign select_ln67_fu_298_p3 = ((trunc_ln60_reg_321[0:0] == 1'b1) ? bufferB_3_q1 : bufferB_1_q1);

assign tmp_14_fu_250_p3 = {{lshr_ln3_fu_224_p4}, {7'd127}};

assign tmp_reg_314 = empty;

assign tmp_s_fu_234_p3 = {{lshr_ln3_fu_224_p4}, {7'd0}};

assign trunc_ln60_fu_220_p1 = ap_sig_allocacmp_i_2[0:0];

assign zext_ln66_fu_242_p1 = tmp_s_fu_234_p3;

assign zext_ln67_fu_258_p1 = tmp_14_fu_250_p3;

always @ (posedge ap_clk) begin
    bufferA_addr_reg_329[6:0] <= 7'b0000000;
    bufferA_1_addr_reg_335[6:0] <= 7'b1111111;
    bufferA_2_addr_reg_341[6:0] <= 7'b0000000;
    bufferA_3_addr_reg_347[6:0] <= 7'b1111111;
    bufferB_addr_1_reg_353[6:0] <= 7'b0000000;
    bufferB_1_addr_1_reg_359[6:0] <= 7'b1111111;
    bufferB_2_addr_1_reg_365[6:0] <= 7'b0000000;
    bufferB_3_addr_1_reg_371[6:0] <= 7'b1111111;
end

endmodule //top_kernel_compute_Pipeline_VITIS_LOOP_60_5
