

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "63", "70", "71", "82", "84", "85", "86", "87"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "gmem0", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "gmem2", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "82", "SubInstance" : "grp_k5_deferred_lighting_fu_406", "Port" : "gmem1", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "in_tris", "Type" : "None", "Direction" : "I"},
			{"Name" : "mvp_matrix", "Type" : "None", "Direction" : "I"},
			{"Name" : "out_pixels", "Type" : "None", "Direction" : "I"},
			{"Name" : "clip_tris_v0_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v0_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v0_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v0_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v0_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v0_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v0_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v0_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v0_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v0_w", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v0_w", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v0_w", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v1_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v1_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v1_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v1_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v1_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v1_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v1_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v1_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v1_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v1_w", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v1_w", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v1_w", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v2_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v2_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v2_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v2_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v2_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v2_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v2_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v2_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v2_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_v2_w", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_v2_w", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_v2_w", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n0_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n0_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n0_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n0_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n0_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n0_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n0_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n0_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n0_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n1_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n1_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n1_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n1_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n1_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n1_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n1_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n1_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n1_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n2_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n2_x", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n2_x", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n2_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n2_y", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n2_y", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_n2_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_n2_z", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_n2_z", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "clip_tris_is_active", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "50", "SubInstance" : "grp_k1_vertex_transform_fu_180", "Port" : "clip_tris_is_active", "Inst_start_state" : "1", "Inst_end_state" : "2"},
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "clip_tris_is_active", "Inst_start_state" : "3", "Inst_end_state" : "4"}]},
			{"Name" : "screen_tris_v0_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v0_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v0_x", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v0_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v0_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v0_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v0_y", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v0_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v0_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v0_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v0_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v1_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v1_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v1_x", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v1_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v1_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v1_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v1_y", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v1_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v1_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v1_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v1_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v2_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v2_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v2_x", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v2_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v2_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v2_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_v2_y", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v2_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_v2_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_v2_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_v2_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n0_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n0_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n0_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n0_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n0_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n0_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n0_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n0_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n0_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n1_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n1_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n1_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n1_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n1_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n1_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n1_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n1_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n1_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n2_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n2_x", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n2_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n2_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n2_y", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n2_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_n2_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_n2_z", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_n2_z", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "screen_tris_is_active", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "63", "SubInstance" : "grp_k2_perspective_divide_fu_236", "Port" : "screen_tris_is_active", "Inst_start_state" : "3", "Inst_end_state" : "4"},
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "screen_tris_is_active", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "screen_tris_is_active", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "bounds_min_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "bounds_min_x", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "bounds_min_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "bounds_max_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "bounds_max_x", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "bounds_max_x", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "bounds_min_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "bounds_min_y", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "bounds_min_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "bounds_max_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "70", "SubInstance" : "grp_k3_bounding_box_fu_322", "Port" : "bounds_max_y", "Inst_start_state" : "5", "Inst_end_state" : "6"},
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "bounds_max_y", "Inst_start_state" : "7", "Inst_end_state" : "8"}]},
			{"Name" : "depth_buffer", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "depth_buffer", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "82", "SubInstance" : "grp_k5_deferred_lighting_fu_406", "Port" : "depth_buffer", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "normal_buffer_x", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "normal_buffer_x", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "82", "SubInstance" : "grp_k5_deferred_lighting_fu_406", "Port" : "normal_buffer_x", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "normal_buffer_y", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "normal_buffer_y", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "82", "SubInstance" : "grp_k5_deferred_lighting_fu_406", "Port" : "normal_buffer_y", "Inst_start_state" : "9", "Inst_end_state" : "10"}]},
			{"Name" : "normal_buffer_z", "Type" : "Memory", "Direction" : "IO",
				"SubConnect" : [
					{"ID" : "71", "SubInstance" : "grp_k4_rasterize_fu_348", "Port" : "normal_buffer_z", "Inst_start_state" : "7", "Inst_end_state" : "8"},
					{"ID" : "82", "SubInstance" : "grp_k5_deferred_lighting_fu_406", "Port" : "normal_buffer_z", "Inst_start_state" : "9", "Inst_end_state" : "10"}]}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v0_x_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v0_y_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v0_z_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v0_w_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v1_x_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v1_y_U", "Parent" : "0"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v1_z_U", "Parent" : "0"},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v1_w_U", "Parent" : "0"},
	{"ID" : "9", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v2_x_U", "Parent" : "0"},
	{"ID" : "10", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v2_y_U", "Parent" : "0"},
	{"ID" : "11", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v2_z_U", "Parent" : "0"},
	{"ID" : "12", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_v2_w_U", "Parent" : "0"},
	{"ID" : "13", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n0_x_U", "Parent" : "0"},
	{"ID" : "14", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n0_y_U", "Parent" : "0"},
	{"ID" : "15", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n0_z_U", "Parent" : "0"},
	{"ID" : "16", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n1_x_U", "Parent" : "0"},
	{"ID" : "17", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n1_y_U", "Parent" : "0"},
	{"ID" : "18", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n1_z_U", "Parent" : "0"},
	{"ID" : "19", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n2_x_U", "Parent" : "0"},
	{"ID" : "20", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n2_y_U", "Parent" : "0"},
	{"ID" : "21", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_n2_z_U", "Parent" : "0"},
	{"ID" : "22", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.clip_tris_is_active_U", "Parent" : "0"},
	{"ID" : "23", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v0_x_U", "Parent" : "0"},
	{"ID" : "24", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v0_y_U", "Parent" : "0"},
	{"ID" : "25", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v0_z_U", "Parent" : "0"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v1_x_U", "Parent" : "0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v1_y_U", "Parent" : "0"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v1_z_U", "Parent" : "0"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v2_x_U", "Parent" : "0"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v2_y_U", "Parent" : "0"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_v2_z_U", "Parent" : "0"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n0_x_U", "Parent" : "0"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n0_y_U", "Parent" : "0"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n0_z_U", "Parent" : "0"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n1_x_U", "Parent" : "0"},
	{"ID" : "36", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n1_y_U", "Parent" : "0"},
	{"ID" : "37", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n1_z_U", "Parent" : "0"},
	{"ID" : "38", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n2_x_U", "Parent" : "0"},
	{"ID" : "39", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n2_y_U", "Parent" : "0"},
	{"ID" : "40", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_n2_z_U", "Parent" : "0"},
	{"ID" : "41", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.screen_tris_is_active_U", "Parent" : "0"},
	{"ID" : "42", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bounds_min_x_U", "Parent" : "0"},
	{"ID" : "43", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bounds_max_x_U", "Parent" : "0"},
	{"ID" : "44", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bounds_min_y_U", "Parent" : "0"},
	{"ID" : "45", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.bounds_max_y_U", "Parent" : "0"},
	{"ID" : "46", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.depth_buffer_U", "Parent" : "0"},
	{"ID" : "47", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.normal_buffer_x_U", "Parent" : "0"},
	{"ID" : "48", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.normal_buffer_y_U", "Parent" : "0"},
	{"ID" : "49", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.normal_buffer_z_U", "Parent" : "0"},
	{"ID" : "50", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180", "Parent" : "0", "Child" : ["51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62"],
		"CDFG" : "k1_vertex_transform",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "2817", "EstimateLatencyMax" : "6017",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem0", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem0_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem0_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "in_tris", "Type" : "None", "Direction" : "I"},
			{"Name" : "gmem2", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "gmem2_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "gmem2_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "mvp", "Type" : "None", "Direction" : "I"},
			{"Name" : "clip_tris_v0_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v0_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v0_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v0_w", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v1_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v1_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v1_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v1_w", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v2_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v2_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v2_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_v2_w", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n0_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n0_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n0_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n1_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n1_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n1_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n2_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n2_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_n2_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "clip_tris_is_active", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_10_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "48", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state48"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "51", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U1", "Parent" : "50"},
	{"ID" : "52", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U2", "Parent" : "50"},
	{"ID" : "53", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U3", "Parent" : "50"},
	{"ID" : "54", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U4", "Parent" : "50"},
	{"ID" : "55", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U5", "Parent" : "50"},
	{"ID" : "56", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U6", "Parent" : "50"},
	{"ID" : "57", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U7", "Parent" : "50"},
	{"ID" : "58", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U8", "Parent" : "50"},
	{"ID" : "59", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U9", "Parent" : "50"},
	{"ID" : "60", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U10", "Parent" : "50"},
	{"ID" : "61", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U11", "Parent" : "50"},
	{"ID" : "62", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k1_vertex_transform_fu_180.mul_32s_32s_64_1_1_U12", "Parent" : "50"},
	{"ID" : "63", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236", "Parent" : "0", "Child" : ["64", "65", "66", "67", "68", "69"],
		"CDFG" : "k2_perspective_divide",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "385", "EstimateLatencyMax" : "15233",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "clip_tris_v0_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v0_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v0_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v0_w", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v1_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v1_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v1_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v1_w", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v2_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v2_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v2_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_v2_w", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n0_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n0_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n0_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n1_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n1_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n1_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n2_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n2_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_n2_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "clip_tris_is_active", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v0_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v0_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v1_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v1_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v1_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v2_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v2_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_v2_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n0_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n0_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n0_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n1_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n1_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n1_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n2_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n2_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_n2_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_is_active", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_116_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "120", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state120"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "64", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.mul_32s_32s_64_1_1_U40", "Parent" : "63"},
	{"ID" : "65", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.mul_32s_32s_64_1_1_U41", "Parent" : "63"},
	{"ID" : "66", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.mul_32s_32s_64_1_1_U42", "Parent" : "63"},
	{"ID" : "67", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.sdiv_34ns_32s_34_38_seq_1_U43", "Parent" : "63"},
	{"ID" : "68", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.sdiv_34ns_32s_34_38_seq_1_U44", "Parent" : "63"},
	{"ID" : "69", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k2_perspective_divide_fu_236.sdiv_34ns_32s_34_38_seq_1_U45", "Parent" : "63"},
	{"ID" : "70", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_k3_bounding_box_fu_322", "Parent" : "0",
		"CDFG" : "k3_bounding_box",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "385", "EstimateLatencyMax" : "513",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "screen_tris_is_active", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v1_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v2_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v1_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v2_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bounds_min_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bounds_max_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bounds_min_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "bounds_max_y", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_203_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "5", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state5"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "71", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348", "Parent" : "0", "Child" : ["72", "73", "74", "75", "76", "77", "78", "79", "80", "81"],
		"CDFG" : "k4_rasterize",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "-1", "EstimateLatencyMax" : "-1",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "depth_buffer", "Type" : "Memory", "Direction" : "IO"},
			{"Name" : "normal_buffer_x", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "normal_buffer_y", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "normal_buffer_z", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "screen_tris_is_active", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v1_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v1_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v2_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v2_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bounds_min_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bounds_max_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bounds_min_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "bounds_max_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v0_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v1_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_v2_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n0_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n1_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n2_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n0_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n1_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n2_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n0_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n1_z", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "screen_tris_n2_z", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_301_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "53", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "1", "OneStateBlock": "ap_ST_fsm_state3_blk"}},
			{"Name" : "VITIS_LOOP_300_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "53", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state4"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_339_5", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "53", "FirstState" : "ap_ST_fsm_state47", "LastState" : ["ap_ST_fsm_state53"], "QuitState" : ["ap_ST_fsm_state47"], "PreState" : ["ap_ST_fsm_state46"], "PostState" : ["ap_ST_fsm_state46"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_338_4", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "53", "FirstState" : "ap_ST_fsm_state46", "LastState" : ["ap_ST_fsm_state47"], "QuitState" : ["ap_ST_fsm_state46"], "PreState" : ["ap_ST_fsm_state5", "ap_ST_fsm_state8", "ap_ST_fsm_state45"], "PostState" : ["ap_ST_fsm_state4"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_309_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "53", "FirstState" : "ap_ST_fsm_state4", "LastState" : ["ap_ST_fsm_state46"], "QuitState" : ["ap_ST_fsm_state4"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "72", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32ns_32s_63_1_1_U99", "Parent" : "71"},
	{"ID" : "73", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32ns_32s_63_1_1_U100", "Parent" : "71"},
	{"ID" : "74", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32ns_32s_63_1_1_U101", "Parent" : "71"},
	{"ID" : "75", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U102", "Parent" : "71"},
	{"ID" : "76", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U103", "Parent" : "71"},
	{"ID" : "77", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U104", "Parent" : "71"},
	{"ID" : "78", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U105", "Parent" : "71"},
	{"ID" : "79", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U106", "Parent" : "71"},
	{"ID" : "80", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.mul_32s_32s_64_1_1_U107", "Parent" : "71"},
	{"ID" : "81", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k4_rasterize_fu_348.sdiv_34ns_32s_34_38_seq_1_U108", "Parent" : "71"},
	{"ID" : "82", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grp_k5_deferred_lighting_fu_406", "Parent" : "0", "Child" : ["83"],
		"CDFG" : "k5_deferred_lighting",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "24710", "EstimateLatencyMax" : "24710",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "gmem1", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "gmem1_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "gmem1_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "framebuffer", "Type" : "None", "Direction" : "I"},
			{"Name" : "depth_buffer", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "normal_buffer_x", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "normal_buffer_y", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "normal_buffer_z", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_441_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "13", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state8"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state2"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_440_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "13", "FirstState" : "ap_ST_fsm_state2", "LastState" : ["ap_ST_fsm_state3"], "QuitState" : ["ap_ST_fsm_state2"], "PreState" : ["ap_ST_fsm_state1"], "PostState" : ["ap_ST_fsm_state9"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "83", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.grp_k5_deferred_lighting_fu_406.mul_32s_17s_49_1_1_U137", "Parent" : "82"},
	{"ID" : "84", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "85", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem0_m_axi_U", "Parent" : "0"},
	{"ID" : "86", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem1_m_axi_U", "Parent" : "0"},
	{"ID" : "87", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.gmem2_m_axi_U", "Parent" : "0"}]}
