// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_0_0_01171_lcssa_lcssa70,
        p_0_0_01172_lcssa_lcssa68,
        p_0_0_01173_lcssa_lcssa66,
        tmp_18,
        zext_ln52,
        empty,
        buffer_r_address0,
        buffer_r_ce0,
        buffer_r_we0,
        buffer_r_d0,
        buffer_r_address1,
        buffer_r_ce1,
        buffer_r_q1,
        buffer_1_address0,
        buffer_1_ce0,
        buffer_1_we0,
        buffer_1_d0,
        buffer_1_address1,
        buffer_1_ce1,
        buffer_1_q1,
        buffer_2_address0,
        buffer_2_ce0,
        buffer_2_we0,
        buffer_2_d0,
        buffer_2_address1,
        buffer_2_ce1,
        buffer_2_q1,
        buffer_3_address0,
        buffer_3_ce0,
        buffer_3_we0,
        buffer_3_d0,
        buffer_3_address1,
        buffer_3_ce1,
        buffer_3_q1,
        p_0_0_01178_252_out,
        p_0_0_01178_252_out_ap_vld,
        p_0_0_01178_251_out_i,
        p_0_0_01178_251_out_o,
        p_0_0_01178_251_out_o_ap_vld,
        p_0_0_01178_150_out,
        p_0_0_01178_150_out_ap_vld,
        p_0_0_01178_149_out_i,
        p_0_0_01178_149_out_o,
        p_0_0_01178_149_out_o_ap_vld,
        p_0_0_0117848_out,
        p_0_0_0117848_out_ap_vld,
        p_0_0_0117847_out_i,
        p_0_0_0117847_out_o,
        p_0_0_0117847_out_o_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] p_0_0_01171_lcssa_lcssa70;
input  [23:0] p_0_0_01172_lcssa_lcssa68;
input  [23:0] p_0_0_01173_lcssa_lcssa66;
input  [0:0] tmp_18;
input  [7:0] zext_ln52;
input  [0:0] empty;
output  [14:0] buffer_r_address0;
output   buffer_r_ce0;
output   buffer_r_we0;
output  [23:0] buffer_r_d0;
output  [14:0] buffer_r_address1;
output   buffer_r_ce1;
input  [23:0] buffer_r_q1;
output  [14:0] buffer_1_address0;
output   buffer_1_ce0;
output   buffer_1_we0;
output  [23:0] buffer_1_d0;
output  [14:0] buffer_1_address1;
output   buffer_1_ce1;
input  [23:0] buffer_1_q1;
output  [14:0] buffer_2_address0;
output   buffer_2_ce0;
output   buffer_2_we0;
output  [23:0] buffer_2_d0;
output  [14:0] buffer_2_address1;
output   buffer_2_ce1;
input  [23:0] buffer_2_q1;
output  [14:0] buffer_3_address0;
output   buffer_3_ce0;
output   buffer_3_we0;
output  [23:0] buffer_3_d0;
output  [14:0] buffer_3_address1;
output   buffer_3_ce1;
input  [23:0] buffer_3_q1;
output  [23:0] p_0_0_01178_252_out;
output   p_0_0_01178_252_out_ap_vld;
input  [23:0] p_0_0_01178_251_out_i;
output  [23:0] p_0_0_01178_251_out_o;
output   p_0_0_01178_251_out_o_ap_vld;
output  [23:0] p_0_0_01178_150_out;
output   p_0_0_01178_150_out_ap_vld;
input  [23:0] p_0_0_01178_149_out_i;
output  [23:0] p_0_0_01178_149_out_o;
output   p_0_0_01178_149_out_o_ap_vld;
output  [23:0] p_0_0_0117848_out;
output   p_0_0_0117848_out_ap_vld;
input  [23:0] p_0_0_0117847_out_i;
output  [23:0] p_0_0_0117847_out_o;
output   p_0_0_0117847_out_o_ap_vld;

reg ap_idle;
reg p_0_0_01178_252_out_ap_vld;
reg[23:0] p_0_0_01178_251_out_o;
reg p_0_0_01178_251_out_o_ap_vld;
reg p_0_0_01178_150_out_ap_vld;
reg[23:0] p_0_0_01178_149_out_o;
reg p_0_0_01178_149_out_o_ap_vld;
reg p_0_0_0117848_out_ap_vld;
reg[23:0] p_0_0_0117847_out_o;
reg p_0_0_0117847_out_o_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln62_fu_402_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln62_reg_1250;
reg   [0:0] icmp_ln62_reg_1250_pp0_iter2_reg;
wire   [0:0] trunc_ln62_fu_448_p1;
reg   [0:0] trunc_ln62_reg_1254;
reg   [0:0] trunc_ln62_reg_1254_pp0_iter2_reg;
reg   [0:0] trunc_ln62_reg_1254_pp0_iter3_reg;
wire   [0:0] xor_ln102_5_fu_492_p2;
reg   [0:0] xor_ln102_5_reg_1259;
reg   [0:0] xor_ln102_5_reg_1259_pp0_iter2_reg;
reg   [0:0] xor_ln102_5_reg_1259_pp0_iter3_reg;
wire   [0:0] trunc_ln63_1_fu_512_p1;
reg   [0:0] trunc_ln63_1_reg_1264;
reg   [0:0] trunc_ln63_1_reg_1264_pp0_iter2_reg;
reg   [0:0] trunc_ln63_1_reg_1264_pp0_iter3_reg;
reg   [7:0] line_buf_addr_reg_1290;
reg   [7:0] line_buf_1_addr_reg_1296;
wire   [0:0] and_ln87_fu_569_p2;
reg   [0:0] and_ln87_reg_1302;
reg   [0:0] and_ln87_reg_1302_pp0_iter2_reg;
reg   [0:0] and_ln87_reg_1302_pp0_iter3_reg;
reg   [6:0] lshr_ln5_reg_1306;
reg   [6:0] lshr_ln5_reg_1306_pp0_iter2_reg;
reg   [6:0] lshr_ln5_reg_1306_pp0_iter3_reg;
reg   [6:0] tmp_35_cast_reg_1311;
reg   [6:0] tmp_35_cast_reg_1311_pp0_iter2_reg;
reg   [6:0] tmp_35_cast_reg_1311_pp0_iter3_reg;
reg  signed [23:0] p_0_0_0117848_load_reg_1316;
reg   [23:0] p_0_0_01178_150_load_reg_1321;
reg  signed [23:0] p_0_0_01178_252_load_reg_1327;
wire   [38:0] sum_axis_fu_717_p2;
reg  signed [38:0] sum_axis_reg_1332;
wire   [38:0] sum_diag_fu_775_p2;
reg  signed [38:0] sum_diag_reg_1337;
reg   [0:0] tmp_8_reg_1342;
reg   [37:0] out_reg_1348;
reg   [0:0] tmp_9_reg_1353;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [7:0] line_buf_1_address1;
wire   [23:0] line_buf_1_q1;
wire   [7:0] line_buf_address1;
wire   [23:0] line_buf_q1;
wire   [63:0] zext_ln73_fu_545_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln63_fu_502_p1;
wire   [63:0] zext_ln102_1_fu_890_p1;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [8:0] j_fu_158;
wire   [8:0] add_ln63_fu_601_p2;
wire    ap_loop_init;
reg   [8:0] i_fu_162;
wire   [8:0] select_ln62_1_fu_440_p3;
reg   [16:0] indvar_flatten6_fu_166;
wire   [16:0] add_ln62_1_fu_408_p2;
reg   [23:0] p_0_0_0117848_fu_170;
reg   [23:0] p_0_0_01178_150_fu_174;
reg   [23:0] p_0_0_01178_252_fu_178;
wire   [23:0] select_ln84_2_fu_645_p3;
reg    buffer_r_ce1_local;
reg    buffer_r_we0_local;
wire   [23:0] select_ln102_3_fu_1166_p3;
reg    buffer_r_ce0_local;
reg    buffer_1_ce1_local;
reg    buffer_1_we0_local;
reg    buffer_1_ce0_local;
reg    buffer_2_ce1_local;
reg    buffer_2_we0_local;
reg    buffer_2_ce0_local;
reg    buffer_3_ce1_local;
reg    buffer_3_we0_local;
reg    buffer_3_ce0_local;
reg    line_buf_ce1_local;
reg    line_buf_we0_local;
reg    line_buf_ce0_local;
reg    line_buf_1_ce1_local;
reg    line_buf_1_we0_local;
reg    line_buf_1_ce0_local;
wire   [23:0] mul_ln99_1_fu_359_p1;
wire   [25:0] mul_ln99_fu_364_p1;
wire   [0:0] icmp_ln63_fu_426_p2;
wire   [8:0] add_ln62_fu_420_p2;
wire   [7:0] tmp_1_fu_452_p4;
wire   [8:0] empty_37_fu_468_p2;
wire   [0:0] tmp_2_fu_484_p3;
wire   [7:0] lshr_ln4_fu_474_p4;
wire   [8:0] select_ln62_fu_432_p3;
wire   [6:0] tmp_s_fu_526_p4;
wire   [6:0] lshr_ln63_1_fu_516_p4;
wire   [14:0] tmp_3_fu_536_p4;
wire   [7:0] tmp_4_fu_553_p4;
wire   [0:0] icmp_fu_462_p2;
wire   [0:0] icmp_ln87_fu_563_p2;
wire   [7:0] trunc_ln63_fu_508_p1;
wire   [7:0] add_ln89_fu_575_p2;
wire   [7:0] add_ln102_1_fu_497_p2;
wire   [23:0] select_ln84_1_fu_638_p3;
wire   [23:0] select_ln84_fu_631_p3;
wire  signed [23:0] p_0_0_01178_252_cast_fu_665_p0;
wire  signed [23:0] p_0_0_01178_149_cast_fu_669_p0;
wire  signed [23:0] p_0_0_0117848_cast_fu_673_p0;
wire  signed [24:0] p_0_0_01178_149_cast_fu_669_p1;
wire  signed [24:0] p_0_0_01178_252_cast_fu_665_p1;
wire   [24:0] empty_38_fu_677_p2;
wire  signed [25:0] sext_ln91_fu_683_p1;
wire  signed [25:0] p_0_0_0117848_cast_fu_673_p1;
wire   [25:0] add_ln91_fu_687_p2;
wire   [37:0] tmp_6_fu_693_p3;
wire   [35:0] shl_ln_fu_705_p3;
wire  signed [38:0] sext_ln92_fu_701_p1;
wire  signed [38:0] sext_ln92_1_fu_713_p1;
wire  signed [23:0] p_0_0_01178_251_cast_fu_723_p0;
wire  signed [23:0] p_0_0_0117847_cast_fu_727_p0;
wire  signed [23:0] line_buf_load_cast_fu_731_p0;
wire  signed [24:0] p_0_0_0117847_cast_fu_727_p1;
wire  signed [24:0] p_0_0_01178_251_cast_fu_723_p1;
wire   [24:0] empty_39_fu_735_p2;
wire  signed [25:0] sext_ln94_fu_741_p1;
wire  signed [25:0] line_buf_load_cast_fu_731_p1;
wire   [25:0] add_ln94_fu_745_p2;
wire   [37:0] tmp_7_fu_751_p3;
wire   [35:0] shl_ln1_fu_763_p3;
wire  signed [38:0] sext_ln95_fu_759_p1;
wire  signed [38:0] sext_ln95_1_fu_771_p1;
wire   [62:0] shl_ln2_fu_814_p3;
wire   [64:0] mul_ln99_fu_364_p2;
wire   [62:0] mul_ln99_1_fu_359_p2;
wire  signed [63:0] sext_ln99_1_fu_825_p1;
wire  signed [63:0] sext_ln99_4_fu_837_p1;
wire   [63:0] add_ln99_fu_841_p2;
wire  signed [65:0] sext_ln99_5_fu_847_p1;
wire  signed [65:0] sext_ln99_2_fu_829_p1;
wire   [65:0] add_ln99_1_fu_851_p2;
wire   [14:0] tmp_5_fu_883_p4;
wire  signed [38:0] sext_ln99_6_fu_898_p1;
wire   [38:0] zext_ln99_fu_901_p1;
wire  signed [38:0] out_1_fu_904_p2;
wire   [0:0] tmp_10_fu_914_p3;
wire   [0:0] xor_ln99_fu_922_p2;
wire   [0:0] or_ln99_1_fu_927_p2;
wire   [0:0] xor_ln99_1_fu_933_p2;
wire   [0:0] xor_ln99_2_fu_938_p2;
wire   [0:0] or_ln99_fu_944_p2;
wire   [0:0] and_ln99_fu_950_p2;
wire  signed [39:0] sext_ln99_7_fu_910_p1;
wire   [39:0] out_2_fu_956_p3;
wire   [0:0] tmp_14_fu_982_p3;
wire   [23:0] trunc_ln1_fu_972_p4;
wire   [23:0] zext_ln102_fu_998_p1;
wire   [23:0] add_ln102_fu_1002_p2;
wire   [0:0] tmp_16_fu_1008_p3;
wire   [0:0] tmp_15_fu_990_p3;
wire   [0:0] xor_ln102_fu_1016_p2;
wire   [2:0] tmp_12_fu_1036_p3;
wire   [3:0] tmp_13_fu_1050_p3;
wire   [0:0] and_ln102_fu_1022_p2;
wire   [0:0] icmp_ln102_1_fu_1058_p2;
wire   [0:0] icmp_ln102_2_fu_1064_p2;
wire   [0:0] tmp_17_fu_1028_p3;
wire   [0:0] icmp_ln102_fu_1044_p2;
wire   [0:0] xor_ln102_1_fu_1078_p2;
wire   [0:0] and_ln102_1_fu_1084_p2;
wire   [0:0] select_ln102_fu_1070_p3;
wire   [0:0] xor_ln102_2_fu_1104_p2;
wire   [0:0] tmp_11_fu_964_p3;
wire   [0:0] or_ln102_fu_1110_p2;
wire   [0:0] xor_ln102_3_fu_1116_p2;
wire   [0:0] select_ln102_1_fu_1090_p3;
wire   [0:0] and_ln102_2_fu_1098_p2;
wire   [0:0] and_ln102_4_fu_1128_p2;
wire   [0:0] or_ln102_2_fu_1134_p2;
wire   [0:0] xor_ln102_4_fu_1140_p2;
wire   [0:0] and_ln102_3_fu_1122_p2;
wire   [0:0] and_ln102_5_fu_1146_p2;
wire   [0:0] or_ln102_1_fu_1160_p2;
wire   [23:0] select_ln102_2_fu_1152_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 j_fu_158 = 9'd0;
#0 i_fu_162 = 9'd0;
#0 indvar_flatten6_fu_166 = 17'd0;
#0 p_0_0_0117848_fu_170 = 24'd0;
#0 p_0_0_01178_150_fu_174 = 24'd0;
#0 p_0_0_01178_252_fu_178 = 24'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_line_buf_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_1_addr_reg_1296),
    .ce0(line_buf_1_ce0_local),
    .we0(line_buf_1_we0_local),
    .d0(select_ln84_2_fu_645_p3),
    .address1(line_buf_1_address1),
    .ce1(line_buf_1_ce1_local),
    .q1(line_buf_1_q1)
);

top_kernel_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_line_buf_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_addr_reg_1290),
    .ce0(line_buf_ce0_local),
    .we0(line_buf_we0_local),
    .d0(line_buf_1_q1),
    .address1(line_buf_address1),
    .ce1(line_buf_ce1_local),
    .q1(line_buf_q1)
);

top_kernel_mul_39s_24ns_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 39 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 63 ))
mul_39s_24ns_63_1_1_U23(
    .din0(sum_diag_reg_1337),
    .din1(mul_ln99_1_fu_359_p1),
    .dout(mul_ln99_1_fu_359_p2)
);

top_kernel_mul_39s_26ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 39 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 65 ))
mul_39s_26ns_65_1_1_U24(
    .din0(sum_axis_reg_1332),
    .din1(mul_ln99_fu_364_p1),
    .dout(mul_ln99_fu_364_p2)
);

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_162 <= 9'd0;
        end else if (((icmp_ln62_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_162 <= select_ln62_1_fu_440_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_166 <= 17'd0;
        end else if (((icmp_ln62_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten6_fu_166 <= add_ln62_1_fu_408_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_158 <= 9'd0;
        end else if (((icmp_ln62_fu_402_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_158 <= add_ln63_fu_601_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0117848_fu_170 <= p_0_0_01173_lcssa_lcssa66;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
            p_0_0_0117848_fu_170 <= line_buf_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01178_150_fu_174 <= p_0_0_01172_lcssa_lcssa68;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
            p_0_0_01178_150_fu_174 <= line_buf_1_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01178_252_fu_178 <= p_0_0_01171_lcssa_lcssa70;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
            p_0_0_01178_252_fu_178 <= select_ln84_2_fu_645_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln87_reg_1302 <= and_ln87_fu_569_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln62_reg_1250 <= icmp_ln62_fu_402_p2;
        line_buf_1_addr_reg_1296 <= zext_ln63_fu_502_p1;
        line_buf_addr_reg_1290 <= zext_ln63_fu_502_p1;
        lshr_ln5_reg_1306 <= {{add_ln89_fu_575_p2[7:1]}};
        tmp_35_cast_reg_1311 <= {{add_ln102_1_fu_497_p2[7:1]}};
        trunc_ln62_reg_1254 <= trunc_ln62_fu_448_p1;
        trunc_ln63_1_reg_1264 <= trunc_ln63_1_fu_512_p1;
        xor_ln102_5_reg_1259 <= xor_ln102_5_fu_492_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln87_reg_1302_pp0_iter2_reg <= and_ln87_reg_1302;
        and_ln87_reg_1302_pp0_iter3_reg <= and_ln87_reg_1302_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        icmp_ln62_reg_1250_pp0_iter2_reg <= icmp_ln62_reg_1250;
        lshr_ln5_reg_1306_pp0_iter2_reg <= lshr_ln5_reg_1306;
        lshr_ln5_reg_1306_pp0_iter3_reg <= lshr_ln5_reg_1306_pp0_iter2_reg;
        out_reg_1348 <= {{add_ln99_1_fu_851_p2[65:28]}};
        sum_axis_reg_1332[38 : 12] <= sum_axis_fu_717_p2[38 : 12];
        sum_diag_reg_1337[38 : 12] <= sum_diag_fu_775_p2[38 : 12];
        tmp_35_cast_reg_1311_pp0_iter2_reg <= tmp_35_cast_reg_1311;
        tmp_35_cast_reg_1311_pp0_iter3_reg <= tmp_35_cast_reg_1311_pp0_iter2_reg;
        tmp_8_reg_1342 <= add_ln99_1_fu_851_p2[32'd65];
        tmp_9_reg_1353 <= add_ln99_1_fu_851_p2[32'd27];
        trunc_ln62_reg_1254_pp0_iter2_reg <= trunc_ln62_reg_1254;
        trunc_ln62_reg_1254_pp0_iter3_reg <= trunc_ln62_reg_1254_pp0_iter2_reg;
        trunc_ln63_1_reg_1264_pp0_iter2_reg <= trunc_ln63_1_reg_1264;
        trunc_ln63_1_reg_1264_pp0_iter3_reg <= trunc_ln63_1_reg_1264_pp0_iter2_reg;
        xor_ln102_5_reg_1259_pp0_iter2_reg <= xor_ln102_5_reg_1259;
        xor_ln102_5_reg_1259_pp0_iter3_reg <= xor_ln102_5_reg_1259_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0117848_load_reg_1316 <= p_0_0_0117848_fu_170;
        p_0_0_01178_150_load_reg_1321 <= p_0_0_01178_150_fu_174;
        p_0_0_01178_252_load_reg_1327 <= p_0_0_01178_252_fu_178;
    end
end

always @ (*) begin
    if (((icmp_ln62_fu_402_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_1_ce0_local = 1'b1;
    end else begin
        buffer_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_1_ce1_local = 1'b1;
    end else begin
        buffer_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln87_reg_1302_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln63_1_reg_1264_pp0_iter3_reg == 1'd0) & (trunc_ln62_reg_1254_pp0_iter3_reg == 1'd1))) begin
        buffer_1_we0_local = 1'b1;
    end else begin
        buffer_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_2_ce0_local = 1'b1;
    end else begin
        buffer_2_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_2_ce1_local = 1'b1;
    end else begin
        buffer_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln87_reg_1302_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln63_1_reg_1264_pp0_iter3_reg == 1'd1) & (trunc_ln62_reg_1254_pp0_iter3_reg == 1'd0))) begin
        buffer_2_we0_local = 1'b1;
    end else begin
        buffer_2_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_3_ce0_local = 1'b1;
    end else begin
        buffer_3_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_3_ce1_local = 1'b1;
    end else begin
        buffer_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln87_reg_1302_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln63_1_reg_1264_pp0_iter3_reg == 1'd0) & (trunc_ln62_reg_1254_pp0_iter3_reg == 1'd0))) begin
        buffer_3_we0_local = 1'b1;
    end else begin
        buffer_3_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        buffer_r_ce0_local = 1'b1;
    end else begin
        buffer_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        buffer_r_ce1_local = 1'b1;
    end else begin
        buffer_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln87_reg_1302_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1) & (trunc_ln63_1_reg_1264_pp0_iter3_reg == 1'd1) & (trunc_ln62_reg_1254_pp0_iter3_reg == 1'd1))) begin
        buffer_r_we0_local = 1'b1;
    end else begin
        buffer_r_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buf_1_ce0_local = 1'b1;
    end else begin
        line_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce1_local = 1'b1;
    end else begin
        line_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        line_buf_1_we0_local = 1'b1;
    end else begin
        line_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buf_ce0_local = 1'b1;
    end else begin
        line_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_ce1_local = 1'b1;
    end else begin
        line_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        line_buf_we0_local = 1'b1;
    end else begin
        line_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_0117847_out_o = p_0_0_0117848_fu_170;
    end else begin
        p_0_0_0117847_out_o = p_0_0_0117847_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_0117847_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_0117847_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln62_reg_1250_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0117848_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0117848_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_01178_149_out_o = p_0_0_01178_150_fu_174;
    end else begin
        p_0_0_01178_149_out_o = p_0_0_01178_149_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_01178_149_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_149_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln62_reg_1250_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01178_150_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_150_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_01178_251_out_o = p_0_0_01178_252_fu_178;
    end else begin
        p_0_0_01178_251_out_o = p_0_0_01178_251_out_i;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln62_reg_1250 == 1'd0))) begin
        p_0_0_01178_251_out_o_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_251_out_o_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln62_reg_1250_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01178_252_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01178_252_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln102_1_fu_497_p2 = (zext_ln52 + lshr_ln4_fu_474_p4);

assign add_ln102_fu_1002_p2 = (trunc_ln1_fu_972_p4 + zext_ln102_fu_998_p1);

assign add_ln62_1_fu_408_p2 = (indvar_flatten6_fu_166 + 17'd1);

assign add_ln62_fu_420_p2 = (i_fu_162 + 9'd1);

assign add_ln63_fu_601_p2 = (select_ln62_fu_432_p3 + 9'd1);

assign add_ln89_fu_575_p2 = ($signed(trunc_ln63_fu_508_p1) + $signed(8'd255));

assign add_ln91_fu_687_p2 = ($signed(sext_ln91_fu_683_p1) + $signed(p_0_0_0117848_cast_fu_673_p1));

assign add_ln94_fu_745_p2 = ($signed(sext_ln94_fu_741_p1) + $signed(line_buf_load_cast_fu_731_p1));

assign add_ln99_1_fu_851_p2 = ($signed(sext_ln99_5_fu_847_p1) + $signed(sext_ln99_2_fu_829_p1));

assign add_ln99_fu_841_p2 = ($signed(sext_ln99_1_fu_825_p1) + $signed(sext_ln99_4_fu_837_p1));

assign and_ln102_1_fu_1084_p2 = (xor_ln102_1_fu_1078_p2 & icmp_ln102_fu_1044_p2);

assign and_ln102_2_fu_1098_p2 = (icmp_ln102_1_fu_1058_p2 & and_ln102_fu_1022_p2);

assign and_ln102_3_fu_1122_p2 = (xor_ln102_3_fu_1116_p2 & or_ln102_fu_1110_p2);

assign and_ln102_4_fu_1128_p2 = (tmp_16_fu_1008_p3 & select_ln102_1_fu_1090_p3);

assign and_ln102_5_fu_1146_p2 = (xor_ln102_4_fu_1140_p2 & tmp_11_fu_964_p3);

assign and_ln102_fu_1022_p2 = (xor_ln102_fu_1016_p2 & tmp_15_fu_990_p3);

assign and_ln87_fu_569_p2 = (icmp_ln87_fu_563_p2 & icmp_fu_462_p2);

assign and_ln99_fu_950_p2 = (xor_ln99_fu_922_p2 & or_ln99_fu_944_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign buffer_1_address0 = zext_ln102_1_fu_890_p1;

assign buffer_1_address1 = zext_ln73_fu_545_p1;

assign buffer_1_ce0 = buffer_1_ce0_local;

assign buffer_1_ce1 = buffer_1_ce1_local;

assign buffer_1_d0 = select_ln102_3_fu_1166_p3;

assign buffer_1_we0 = buffer_1_we0_local;

assign buffer_2_address0 = zext_ln102_1_fu_890_p1;

assign buffer_2_address1 = zext_ln73_fu_545_p1;

assign buffer_2_ce0 = buffer_2_ce0_local;

assign buffer_2_ce1 = buffer_2_ce1_local;

assign buffer_2_d0 = select_ln102_3_fu_1166_p3;

assign buffer_2_we0 = buffer_2_we0_local;

assign buffer_3_address0 = zext_ln102_1_fu_890_p1;

assign buffer_3_address1 = zext_ln73_fu_545_p1;

assign buffer_3_ce0 = buffer_3_ce0_local;

assign buffer_3_ce1 = buffer_3_ce1_local;

assign buffer_3_d0 = select_ln102_3_fu_1166_p3;

assign buffer_3_we0 = buffer_3_we0_local;

assign buffer_r_address0 = zext_ln102_1_fu_890_p1;

assign buffer_r_address1 = zext_ln73_fu_545_p1;

assign buffer_r_ce0 = buffer_r_ce0_local;

assign buffer_r_ce1 = buffer_r_ce1_local;

assign buffer_r_d0 = select_ln102_3_fu_1166_p3;

assign buffer_r_we0 = buffer_r_we0_local;

assign empty_37_fu_468_p2 = ($signed(select_ln62_1_fu_440_p3) + $signed(9'd511));

assign empty_38_fu_677_p2 = ($signed(p_0_0_01178_149_cast_fu_669_p1) + $signed(p_0_0_01178_252_cast_fu_665_p1));

assign empty_39_fu_735_p2 = ($signed(p_0_0_0117847_cast_fu_727_p1) + $signed(p_0_0_01178_251_cast_fu_723_p1));

assign icmp_fu_462_p2 = ((tmp_1_fu_452_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_1_fu_1058_p2 = ((tmp_13_fu_1050_p3 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln102_2_fu_1064_p2 = ((tmp_13_fu_1050_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln102_fu_1044_p2 = ((tmp_12_fu_1036_p3 == 3'd7) ? 1'b1 : 1'b0);

assign icmp_ln62_fu_402_p2 = ((indvar_flatten6_fu_166 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln63_fu_426_p2 = ((j_fu_158 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln87_fu_563_p2 = ((tmp_4_fu_553_p4 != 8'd0) ? 1'b1 : 1'b0);

assign line_buf_1_address1 = zext_ln63_fu_502_p1;

assign line_buf_address1 = zext_ln63_fu_502_p1;

assign line_buf_load_cast_fu_731_p0 = line_buf_q1;

assign line_buf_load_cast_fu_731_p1 = line_buf_load_cast_fu_731_p0;

assign lshr_ln4_fu_474_p4 = {{empty_37_fu_468_p2[8:1]}};

assign lshr_ln63_1_fu_516_p4 = {{select_ln62_fu_432_p3[7:1]}};

assign mul_ln99_1_fu_359_p1 = 63'd6709248;

assign mul_ln99_fu_364_p1 = 65'd26845184;

assign or_ln102_1_fu_1160_p2 = (and_ln102_5_fu_1146_p2 | and_ln102_3_fu_1122_p2);

assign or_ln102_2_fu_1134_p2 = (and_ln102_4_fu_1128_p2 | and_ln102_2_fu_1098_p2);

assign or_ln102_fu_1110_p2 = (xor_ln102_2_fu_1104_p2 | tmp_16_fu_1008_p3);

assign or_ln99_1_fu_927_p2 = (xor_ln99_fu_922_p2 | tmp_10_fu_914_p3);

assign or_ln99_fu_944_p2 = (xor_ln99_2_fu_938_p2 | tmp_10_fu_914_p3);

assign out_1_fu_904_p2 = ($signed(sext_ln99_6_fu_898_p1) + $signed(zext_ln99_fu_901_p1));

assign out_2_fu_956_p3 = ((and_ln99_fu_950_p2[0:0] == 1'b1) ? 40'd549755813887 : sext_ln99_7_fu_910_p1);

assign p_0_0_0117847_cast_fu_727_p0 = p_0_0_0117847_out_i;

assign p_0_0_0117847_cast_fu_727_p1 = p_0_0_0117847_cast_fu_727_p0;

assign p_0_0_0117848_cast_fu_673_p0 = p_0_0_0117848_fu_170;

assign p_0_0_0117848_cast_fu_673_p1 = p_0_0_0117848_cast_fu_673_p0;

assign p_0_0_0117848_out = p_0_0_0117848_load_reg_1316;

assign p_0_0_01178_149_cast_fu_669_p0 = p_0_0_01178_149_out_i;

assign p_0_0_01178_149_cast_fu_669_p1 = p_0_0_01178_149_cast_fu_669_p0;

assign p_0_0_01178_150_out = p_0_0_01178_150_load_reg_1321;

assign p_0_0_01178_251_cast_fu_723_p0 = p_0_0_01178_251_out_i;

assign p_0_0_01178_251_cast_fu_723_p1 = p_0_0_01178_251_cast_fu_723_p0;

assign p_0_0_01178_252_cast_fu_665_p0 = p_0_0_01178_252_fu_178;

assign p_0_0_01178_252_cast_fu_665_p1 = p_0_0_01178_252_cast_fu_665_p0;

assign p_0_0_01178_252_out = p_0_0_01178_252_load_reg_1327;

assign select_ln102_1_fu_1090_p3 = ((and_ln102_fu_1022_p2[0:0] == 1'b1) ? and_ln102_1_fu_1084_p2 : icmp_ln102_1_fu_1058_p2);

assign select_ln102_2_fu_1152_p3 = ((and_ln102_3_fu_1122_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln102_3_fu_1166_p3 = ((or_ln102_1_fu_1160_p2[0:0] == 1'b1) ? select_ln102_2_fu_1152_p3 : add_ln102_fu_1002_p2);

assign select_ln102_fu_1070_p3 = ((and_ln102_fu_1022_p2[0:0] == 1'b1) ? icmp_ln102_1_fu_1058_p2 : icmp_ln102_2_fu_1064_p2);

assign select_ln62_1_fu_440_p3 = ((icmp_ln63_fu_426_p2[0:0] == 1'b1) ? add_ln62_fu_420_p2 : i_fu_162);

assign select_ln62_fu_432_p3 = ((icmp_ln63_fu_426_p2[0:0] == 1'b1) ? 9'd0 : j_fu_158);

assign select_ln84_1_fu_638_p3 = ((trunc_ln63_1_reg_1264[0:0] == 1'b1) ? buffer_3_q1 : buffer_2_q1);

assign select_ln84_2_fu_645_p3 = ((trunc_ln62_reg_1254[0:0] == 1'b1) ? select_ln84_1_fu_638_p3 : select_ln84_fu_631_p3);

assign select_ln84_fu_631_p3 = ((trunc_ln63_1_reg_1264[0:0] == 1'b1) ? buffer_1_q1 : buffer_r_q1);

assign sext_ln91_fu_683_p1 = $signed(empty_38_fu_677_p2);

assign sext_ln92_1_fu_713_p1 = $signed(shl_ln_fu_705_p3);

assign sext_ln92_fu_701_p1 = $signed(tmp_6_fu_693_p3);

assign sext_ln94_fu_741_p1 = $signed(empty_39_fu_735_p2);

assign sext_ln95_1_fu_771_p1 = $signed(shl_ln1_fu_763_p3);

assign sext_ln95_fu_759_p1 = $signed(tmp_7_fu_751_p3);

assign sext_ln99_1_fu_825_p1 = $signed(shl_ln2_fu_814_p3);

assign sext_ln99_2_fu_829_p1 = $signed(mul_ln99_fu_364_p2);

assign sext_ln99_4_fu_837_p1 = $signed(mul_ln99_1_fu_359_p2);

assign sext_ln99_5_fu_847_p1 = $signed(add_ln99_fu_841_p2);

assign sext_ln99_6_fu_898_p1 = $signed(out_reg_1348);

assign sext_ln99_7_fu_910_p1 = out_1_fu_904_p2;

assign shl_ln1_fu_763_p3 = {{select_ln84_2_fu_645_p3}, {12'd0}};

assign shl_ln2_fu_814_p3 = {{p_0_0_01178_150_load_reg_1321}, {39'd0}};

assign shl_ln_fu_705_p3 = {{line_buf_1_q1}, {12'd0}};

assign sum_axis_fu_717_p2 = ($signed(sext_ln92_fu_701_p1) + $signed(sext_ln92_1_fu_713_p1));

assign sum_diag_fu_775_p2 = ($signed(sext_ln95_fu_759_p1) + $signed(sext_ln95_1_fu_771_p1));

assign tmp_10_fu_914_p3 = out_1_fu_904_p2[32'd38];

assign tmp_11_fu_964_p3 = out_2_fu_956_p3[32'd39];

assign tmp_12_fu_1036_p3 = {{out_2_fu_956_p3[39:37]}};

assign tmp_13_fu_1050_p3 = {{out_2_fu_956_p3[39:36]}};

assign tmp_14_fu_982_p3 = out_2_fu_956_p3[32'd11];

assign tmp_15_fu_990_p3 = out_2_fu_956_p3[32'd35];

assign tmp_16_fu_1008_p3 = add_ln102_fu_1002_p2[32'd23];

assign tmp_17_fu_1028_p3 = out_2_fu_956_p3[32'd36];

assign tmp_1_fu_452_p4 = {{select_ln62_1_fu_440_p3[8:1]}};

assign tmp_2_fu_484_p3 = empty_37_fu_468_p2[32'd1];

assign tmp_3_fu_536_p4 = {{{empty}, {tmp_s_fu_526_p4}}, {lshr_ln63_1_fu_516_p4}};

assign tmp_4_fu_553_p4 = {{select_ln62_fu_432_p3[8:1]}};

assign tmp_5_fu_883_p4 = {{{tmp_35_cast_reg_1311_pp0_iter3_reg}, {xor_ln102_5_reg_1259_pp0_iter3_reg}}, {lshr_ln5_reg_1306_pp0_iter3_reg}};

assign tmp_6_fu_693_p3 = {{add_ln91_fu_687_p2}, {12'd0}};

assign tmp_7_fu_751_p3 = {{add_ln94_fu_745_p2}, {12'd0}};

assign tmp_s_fu_526_p4 = {{select_ln62_1_fu_440_p3[7:1]}};

assign trunc_ln1_fu_972_p4 = {{out_2_fu_956_p3[35:12]}};

assign trunc_ln62_fu_448_p1 = select_ln62_1_fu_440_p3[0:0];

assign trunc_ln63_1_fu_512_p1 = select_ln62_fu_432_p3[0:0];

assign trunc_ln63_fu_508_p1 = select_ln62_fu_432_p3[7:0];

assign xor_ln102_1_fu_1078_p2 = (tmp_17_fu_1028_p3 ^ 1'd1);

assign xor_ln102_2_fu_1104_p2 = (select_ln102_fu_1070_p3 ^ 1'd1);

assign xor_ln102_3_fu_1116_p2 = (tmp_11_fu_964_p3 ^ 1'd1);

assign xor_ln102_4_fu_1140_p2 = (or_ln102_2_fu_1134_p2 ^ 1'd1);

assign xor_ln102_5_fu_492_p2 = (tmp_2_fu_484_p3 ^ tmp_18);

assign xor_ln102_fu_1016_p2 = (tmp_16_fu_1008_p3 ^ 1'd1);

assign xor_ln99_1_fu_933_p2 = (tmp_8_reg_1342 ^ or_ln99_1_fu_927_p2);

assign xor_ln99_2_fu_938_p2 = (xor_ln99_1_fu_933_p2 ^ 1'd1);

assign xor_ln99_fu_922_p2 = (tmp_8_reg_1342 ^ 1'd1);

assign zext_ln102_1_fu_890_p1 = tmp_5_fu_883_p4;

assign zext_ln102_fu_998_p1 = tmp_14_fu_982_p3;

assign zext_ln63_fu_502_p1 = select_ln62_fu_432_p3;

assign zext_ln73_fu_545_p1 = tmp_3_fu_536_p4;

assign zext_ln99_fu_901_p1 = tmp_9_reg_1353;

always @ (posedge ap_clk) begin
    sum_axis_reg_1332[11:0] <= 12'b000000000000;
    sum_diag_reg_1337[11:0] <= 12'b000000000000;
end

endmodule //top_kernel_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7
