// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_compute_Pipeline_VITIS_LOOP_51_5 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cur_address0,
        cur_ce0,
        cur_q0,
        cur_address1,
        cur_ce1,
        cur_q1,
        nxt_address0,
        nxt_ce0,
        nxt_we0,
        nxt_d0,
        nxt_address1,
        nxt_ce1,
        nxt_we1,
        nxt_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [15:0] cur_address0;
output   cur_ce0;
input  [23:0] cur_q0;
output  [15:0] cur_address1;
output   cur_ce1;
input  [23:0] cur_q1;
output  [15:0] nxt_address0;
output   nxt_ce0;
output   nxt_we0;
output  [23:0] nxt_d0;
output  [15:0] nxt_address1;
output   nxt_ce1;
output   nxt_we1;
output  [23:0] nxt_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln51_fu_98_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln53_fu_122_p1;
reg   [63:0] zext_ln53_reg_155;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln54_fu_135_p1;
reg   [63:0] zext_ln54_reg_165;
wire    ap_block_pp0_stage0;
reg   [8:0] i_fu_34;
wire   [8:0] add_ln51_fu_104_p2;
wire    ap_loop_init;
reg   [8:0] ap_sig_allocacmp_i_2;
reg    cur_ce1_local;
reg    cur_ce0_local;
reg    nxt_we1_local;
reg    nxt_ce1_local;
reg    nxt_we0_local;
reg    nxt_ce0_local;
wire   [7:0] trunc_ln51_fu_110_p1;
wire   [15:0] tmp_s_fu_114_p3;
wire   [15:0] tmp_14_fu_127_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 i_fu_34 = 9'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln51_fu_98_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_34 <= add_ln51_fu_104_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_34 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        zext_ln53_reg_155[15 : 8] <= zext_ln53_fu_122_p1[15 : 8];
        zext_ln54_reg_165[15 : 8] <= zext_ln54_fu_135_p1[15 : 8];
    end
end

always @ (*) begin
    if (((icmp_ln51_fu_98_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_2 = 9'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_34;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_ce0_local = 1'b1;
    end else begin
        cur_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_ce1_local = 1'b1;
    end else begin
        cur_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nxt_ce0_local = 1'b1;
    end else begin
        nxt_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nxt_ce1_local = 1'b1;
    end else begin
        nxt_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nxt_we0_local = 1'b1;
    end else begin
        nxt_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        nxt_we1_local = 1'b1;
    end else begin
        nxt_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln51_fu_104_p2 = (ap_sig_allocacmp_i_2 + 9'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign cur_address0 = zext_ln54_fu_135_p1;

assign cur_address1 = zext_ln53_fu_122_p1;

assign cur_ce0 = cur_ce0_local;

assign cur_ce1 = cur_ce1_local;

assign icmp_ln51_fu_98_p2 = ((ap_sig_allocacmp_i_2 == 9'd256) ? 1'b1 : 1'b0);

assign nxt_address0 = zext_ln54_reg_165;

assign nxt_address1 = zext_ln53_reg_155;

assign nxt_ce0 = nxt_ce0_local;

assign nxt_ce1 = nxt_ce1_local;

assign nxt_d0 = cur_q0;

assign nxt_d1 = cur_q1;

assign nxt_we0 = nxt_we0_local;

assign nxt_we1 = nxt_we1_local;

assign tmp_14_fu_127_p3 = {{trunc_ln51_fu_110_p1}, {8'd255}};

assign tmp_s_fu_114_p3 = {{trunc_ln51_fu_110_p1}, {8'd0}};

assign trunc_ln51_fu_110_p1 = ap_sig_allocacmp_i_2[7:0];

assign zext_ln53_fu_122_p1 = tmp_s_fu_114_p3;

assign zext_ln54_fu_135_p1 = tmp_14_fu_127_p3;

always @ (posedge ap_clk) begin
    zext_ln53_reg_155[7:0] <= 8'b00000000;
    zext_ln53_reg_155[63:16] <= 48'b000000000000000000000000000000000000000000000000;
    zext_ln54_reg_165[7:0] <= 8'b11111111;
    zext_ln54_reg_165[63:16] <= 48'b000000000000000000000000000000000000000000000000;
end

endmodule //top_kernel_compute_Pipeline_VITIS_LOOP_51_5
