// ==============================================================
// Generated by Vitis HLS v2025.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module top_kernel_compute_Pipeline_VITIS_LOOP_57_6_VITIS_LOOP_58_7 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_0_0_01162_lcssa_lcssa72,
        p_0_0_01169_2_lcssa_lcssa71,
        p_0_0_01163_lcssa_lcssa70,
        p_0_0_01169_1_lcssa_lcssa69,
        p_0_0_01164_lcssa_lcssa68,
        p_0_0_01169_lcssa_lcssa67,
        cur_address0,
        cur_ce0,
        cur_q0,
        nxt_address0,
        nxt_ce0,
        nxt_we0,
        nxt_d0,
        p_0_0_01169_254_out,
        p_0_0_01169_254_out_ap_vld,
        p_0_0_01169_253_out,
        p_0_0_01169_253_out_ap_vld,
        p_0_0_01169_152_out,
        p_0_0_01169_152_out_ap_vld,
        p_0_0_01169_151_out,
        p_0_0_01169_151_out_ap_vld,
        p_0_0_0116950_out,
        p_0_0_0116950_out_ap_vld,
        p_0_0_0116949_out,
        p_0_0_0116949_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [23:0] p_0_0_01162_lcssa_lcssa72;
input  [23:0] p_0_0_01169_2_lcssa_lcssa71;
input  [23:0] p_0_0_01163_lcssa_lcssa70;
input  [23:0] p_0_0_01169_1_lcssa_lcssa69;
input  [23:0] p_0_0_01164_lcssa_lcssa68;
input  [23:0] p_0_0_01169_lcssa_lcssa67;
output  [15:0] cur_address0;
output   cur_ce0;
input  [23:0] cur_q0;
output  [15:0] nxt_address0;
output   nxt_ce0;
output   nxt_we0;
output  [23:0] nxt_d0;
output  [23:0] p_0_0_01169_254_out;
output   p_0_0_01169_254_out_ap_vld;
output  [23:0] p_0_0_01169_253_out;
output   p_0_0_01169_253_out_ap_vld;
output  [23:0] p_0_0_01169_152_out;
output   p_0_0_01169_152_out_ap_vld;
output  [23:0] p_0_0_01169_151_out;
output   p_0_0_01169_151_out_ap_vld;
output  [23:0] p_0_0_0116950_out;
output   p_0_0_0116950_out_ap_vld;
output  [23:0] p_0_0_0116949_out;
output   p_0_0_0116949_out_ap_vld;

reg ap_idle;
reg p_0_0_01169_254_out_ap_vld;
reg p_0_0_01169_253_out_ap_vld;
reg p_0_0_01169_152_out_ap_vld;
reg p_0_0_01169_151_out_ap_vld;
reg p_0_0_0116950_out_ap_vld;
reg p_0_0_0116949_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln57_fu_380_p2;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln57_reg_1132;
reg   [0:0] icmp_ln57_reg_1132_pp0_iter2_reg;
wire   [7:0] trunc_ln69_fu_426_p1;
reg   [7:0] trunc_ln69_reg_1136;
wire   [7:0] trunc_ln58_fu_475_p1;
reg   [7:0] trunc_ln58_reg_1146;
reg   [7:0] trunc_ln58_reg_1146_pp0_iter2_reg;
reg   [7:0] trunc_ln58_reg_1146_pp0_iter3_reg;
reg   [7:0] line_buf_addr_reg_1151;
reg   [7:0] line_buf_1_addr_reg_1157;
wire   [0:0] and_ln83_fu_495_p2;
reg   [0:0] and_ln83_reg_1163;
reg   [0:0] and_ln83_reg_1163_pp0_iter2_reg;
reg   [0:0] and_ln83_reg_1163_pp0_iter3_reg;
reg  signed [23:0] p_0_0_0116950_load_reg_1167;
reg   [23:0] p_0_0_01169_152_load_reg_1172;
reg  signed [23:0] p_0_0_01169_254_load_reg_1178;
wire   [7:0] empty_fu_531_p2;
reg   [7:0] empty_reg_1183;
reg   [7:0] empty_reg_1183_pp0_iter3_reg;
wire   [38:0] sum_axis_fu_597_p2;
reg  signed [38:0] sum_axis_reg_1188;
wire   [38:0] sum_diag_fu_655_p2;
reg  signed [38:0] sum_diag_reg_1193;
reg   [0:0] tmp_5_reg_1198;
reg   [37:0] out_reg_1204;
reg   [0:0] tmp_6_reg_1209;
reg    ap_condition_exit_pp0_iter2_stage0;
wire   [7:0] line_buf_1_address1;
wire   [23:0] line_buf_1_q1;
wire   [7:0] line_buf_address1;
wire   [23:0] line_buf_q1;
wire   [63:0] zext_ln69_1_fu_470_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln58_fu_454_p1;
wire   [63:0] zext_ln99_1_fu_772_p1;
reg   [23:0] p_0_0_0116949_fu_140;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg   [23:0] p_0_0_01169_151_fu_144;
reg   [23:0] p_0_0_01169_253_fu_148;
reg   [8:0] j_fu_152;
wire   [8:0] add_ln58_fu_501_p2;
reg   [8:0] i_fu_156;
wire   [8:0] select_ln57_1_fu_418_p3;
reg   [16:0] indvar_flatten_fu_160;
wire   [16:0] add_ln57_1_fu_386_p2;
reg   [23:0] p_0_0_0116950_fu_164;
reg   [23:0] p_0_0_01169_152_fu_168;
reg   [23:0] p_0_0_01169_254_fu_172;
wire    ap_block_pp0_stage0_01001;
reg    cur_ce0_local;
reg    line_buf_ce1_local;
reg    line_buf_we0_local;
reg    line_buf_ce0_local;
reg    line_buf_1_ce1_local;
reg    line_buf_1_we0_local;
reg    line_buf_1_ce0_local;
reg    nxt_we0_local;
wire   [23:0] select_ln99_3_fu_1045_p3;
reg    nxt_ce0_local;
wire   [23:0] mul_ln96_1_fu_322_p1;
wire   [25:0] mul_ln96_fu_327_p1;
wire   [0:0] icmp_ln58_fu_404_p2;
wire   [8:0] add_ln57_fu_398_p2;
wire   [7:0] tmp_fu_438_p4;
wire   [8:0] select_ln57_fu_410_p3;
wire   [15:0] tmp_s_fu_430_p3;
wire   [15:0] zext_ln69_fu_460_p1;
wire   [15:0] add_ln69_fu_464_p2;
wire   [7:0] tmp_1_fu_479_p4;
wire   [0:0] icmp_fu_448_p2;
wire   [0:0] icmp_ln83_fu_489_p2;
wire  signed [23:0] p_0_0_01169_254_cast_fu_545_p0;
wire  signed [23:0] p_0_0_01169_151_cast_fu_549_p0;
wire  signed [23:0] p_0_0_0116950_cast_fu_553_p0;
wire  signed [24:0] p_0_0_01169_151_cast_fu_549_p1;
wire  signed [24:0] p_0_0_01169_254_cast_fu_545_p1;
wire   [24:0] empty_41_fu_557_p2;
wire  signed [25:0] sext_ln88_fu_563_p1;
wire  signed [25:0] p_0_0_0116950_cast_fu_553_p1;
wire   [25:0] add_ln88_fu_567_p2;
wire   [37:0] tmp_3_fu_573_p3;
wire   [35:0] shl_ln_fu_585_p3;
wire  signed [38:0] sext_ln89_fu_581_p1;
wire  signed [38:0] sext_ln89_1_fu_593_p1;
wire  signed [23:0] p_0_0_01169_253_cast_fu_603_p0;
wire  signed [23:0] p_0_0_0116949_cast_fu_607_p0;
wire  signed [23:0] line_buf_load_cast_fu_611_p0;
wire  signed [24:0] p_0_0_0116949_cast_fu_607_p1;
wire  signed [24:0] p_0_0_01169_253_cast_fu_603_p1;
wire   [24:0] empty_42_fu_615_p2;
wire  signed [25:0] sext_ln91_fu_621_p1;
wire  signed [25:0] line_buf_load_cast_fu_611_p1;
wire   [25:0] add_ln91_fu_625_p2;
wire   [37:0] tmp_4_fu_631_p3;
wire   [35:0] shl_ln1_fu_643_p3;
wire  signed [38:0] sext_ln92_fu_639_p1;
wire  signed [38:0] sext_ln92_1_fu_651_p1;
wire   [62:0] shl_ln2_fu_691_p3;
wire   [64:0] mul_ln96_fu_327_p2;
wire   [62:0] mul_ln96_1_fu_322_p2;
wire  signed [63:0] sext_ln96_1_fu_702_p1;
wire  signed [63:0] sext_ln96_4_fu_714_p1;
wire   [63:0] add_ln96_fu_718_p2;
wire  signed [65:0] sext_ln96_5_fu_724_p1;
wire  signed [65:0] sext_ln96_2_fu_706_p1;
wire   [65:0] add_ln96_1_fu_728_p2;
wire   [7:0] add_ln86_fu_760_p2;
wire   [15:0] tmp_2_fu_765_p3;
wire  signed [38:0] sext_ln96_6_fu_777_p1;
wire   [38:0] zext_ln96_fu_780_p1;
wire  signed [38:0] out_1_fu_783_p2;
wire   [0:0] tmp_7_fu_793_p3;
wire   [0:0] xor_ln96_fu_801_p2;
wire   [0:0] or_ln96_1_fu_806_p2;
wire   [0:0] xor_ln96_1_fu_812_p2;
wire   [0:0] xor_ln96_2_fu_817_p2;
wire   [0:0] or_ln96_fu_823_p2;
wire   [0:0] and_ln96_fu_829_p2;
wire  signed [39:0] sext_ln96_7_fu_789_p1;
wire   [39:0] out_2_fu_835_p3;
wire   [0:0] tmp_9_fu_861_p3;
wire   [23:0] trunc_ln2_fu_851_p4;
wire   [23:0] zext_ln99_fu_877_p1;
wire   [23:0] add_ln99_fu_881_p2;
wire   [0:0] tmp_11_fu_887_p3;
wire   [0:0] tmp_10_fu_869_p3;
wire   [0:0] xor_ln99_fu_895_p2;
wire   [2:0] tmp_12_fu_915_p3;
wire   [3:0] tmp_13_fu_929_p3;
wire   [0:0] and_ln99_fu_901_p2;
wire   [0:0] icmp_ln99_1_fu_937_p2;
wire   [0:0] icmp_ln99_2_fu_943_p2;
wire   [0:0] tmp_14_fu_907_p3;
wire   [0:0] icmp_ln99_fu_923_p2;
wire   [0:0] xor_ln99_1_fu_957_p2;
wire   [0:0] and_ln99_1_fu_963_p2;
wire   [0:0] select_ln99_fu_949_p3;
wire   [0:0] xor_ln99_2_fu_983_p2;
wire   [0:0] tmp_8_fu_843_p3;
wire   [0:0] or_ln99_fu_989_p2;
wire   [0:0] xor_ln99_3_fu_995_p2;
wire   [0:0] select_ln99_1_fu_969_p3;
wire   [0:0] and_ln99_2_fu_977_p2;
wire   [0:0] and_ln99_4_fu_1007_p2;
wire   [0:0] or_ln99_2_fu_1013_p2;
wire   [0:0] xor_ln99_4_fu_1019_p2;
wire   [0:0] and_ln99_3_fu_1001_p2;
wire   [0:0] and_ln99_5_fu_1025_p2;
wire   [0:0] or_ln99_1_fu_1039_p2;
wire   [23:0] select_ln99_2_fu_1031_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 p_0_0_0116949_fu_140 = 24'd0;
#0 p_0_0_01169_151_fu_144 = 24'd0;
#0 p_0_0_01169_253_fu_148 = 24'd0;
#0 j_fu_152 = 9'd0;
#0 i_fu_156 = 9'd0;
#0 indvar_flatten_fu_160 = 17'd0;
#0 p_0_0_0116950_fu_164 = 24'd0;
#0 p_0_0_01169_152_fu_168 = 24'd0;
#0 p_0_0_01169_254_fu_172 = 24'd0;
#0 ap_done_reg = 1'b0;
end

top_kernel_compute_Pipeline_VITIS_LOOP_57_6_VITIS_LOOP_58_7_line_buf_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_1_addr_reg_1157),
    .ce0(line_buf_1_ce0_local),
    .we0(line_buf_1_we0_local),
    .d0(cur_q0),
    .address1(line_buf_1_address1),
    .ce1(line_buf_1_ce1_local),
    .q1(line_buf_1_q1)
);

top_kernel_compute_Pipeline_VITIS_LOOP_57_6_VITIS_LOOP_58_7_line_buf_1_RAM_AUTO_1R1W #(
    .DataWidth( 24 ),
    .AddressRange( 256 ),
    .AddressWidth( 8 ))
line_buf_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(line_buf_addr_reg_1151),
    .ce0(line_buf_ce0_local),
    .we0(line_buf_we0_local),
    .d0(line_buf_1_q1),
    .address1(line_buf_address1),
    .ce1(line_buf_ce1_local),
    .q1(line_buf_q1)
);

top_kernel_mul_39s_24ns_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 39 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 63 ))
mul_39s_24ns_63_1_1_U6(
    .din0(sum_diag_reg_1193),
    .din1(mul_ln96_1_fu_322_p1),
    .dout(mul_ln96_1_fu_322_p2)
);

top_kernel_mul_39s_26ns_65_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 39 ),
    .din1_WIDTH( 26 ),
    .dout_WIDTH( 65 ))
mul_39s_26ns_65_1_1_U7(
    .din0(sum_axis_reg_1188),
    .din1(mul_ln96_fu_327_p1),
    .dout(mul_ln96_fu_327_p2)
);

top_kernel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter2_stage0)) begin
            ap_enable_reg_pp0_iter3 <= 1'b0;
        end else if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_156 <= 9'd0;
        end else if (((icmp_ln57_fu_380_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_156 <= select_ln57_1_fu_418_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_160 <= 17'd0;
        end else if (((icmp_ln57_fu_380_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            indvar_flatten_fu_160 <= add_ln57_1_fu_386_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            j_fu_152 <= 9'd0;
        end else if (((icmp_ln57_fu_380_p2 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            j_fu_152 <= add_ln58_fu_501_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116949_fu_140 <= p_0_0_01169_lcssa_lcssa67;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_0116949_fu_140 <= p_0_0_0116950_fu_164;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_0116950_fu_164 <= p_0_0_01164_lcssa_lcssa68;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_0116950_fu_164 <= line_buf_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01169_151_fu_144 <= p_0_0_01169_1_lcssa_lcssa69;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_01169_151_fu_144 <= p_0_0_01169_152_fu_168;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01169_152_fu_168 <= p_0_0_01163_lcssa_lcssa70;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_01169_152_fu_168 <= line_buf_1_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01169_253_fu_148 <= p_0_0_01169_2_lcssa_lcssa71;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_01169_253_fu_148 <= p_0_0_01169_254_fu_172;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            p_0_0_01169_254_fu_172 <= p_0_0_01162_lcssa_lcssa72;
        end else if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
            p_0_0_01169_254_fu_172 <= cur_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        and_ln83_reg_1163 <= and_ln83_fu_495_p2;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready;
        icmp_ln57_reg_1132 <= icmp_ln57_fu_380_p2;
        line_buf_1_addr_reg_1157 <= zext_ln58_fu_454_p1;
        line_buf_addr_reg_1151 <= zext_ln58_fu_454_p1;
        trunc_ln58_reg_1146 <= trunc_ln58_fu_475_p1;
        trunc_ln69_reg_1136 <= trunc_ln69_fu_426_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        and_ln83_reg_1163_pp0_iter2_reg <= and_ln83_reg_1163;
        and_ln83_reg_1163_pp0_iter3_reg <= and_ln83_reg_1163_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        empty_reg_1183 <= empty_fu_531_p2;
        empty_reg_1183_pp0_iter3_reg <= empty_reg_1183;
        icmp_ln57_reg_1132_pp0_iter2_reg <= icmp_ln57_reg_1132;
        out_reg_1204 <= {{add_ln96_1_fu_728_p2[65:28]}};
        sum_axis_reg_1188[38 : 12] <= sum_axis_fu_597_p2[38 : 12];
        sum_diag_reg_1193[38 : 12] <= sum_diag_fu_655_p2[38 : 12];
        tmp_5_reg_1198 <= add_ln96_1_fu_728_p2[32'd65];
        tmp_6_reg_1209 <= add_ln96_1_fu_728_p2[32'd27];
        trunc_ln58_reg_1146_pp0_iter2_reg <= trunc_ln58_reg_1146;
        trunc_ln58_reg_1146_pp0_iter3_reg <= trunc_ln58_reg_1146_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        p_0_0_0116950_load_reg_1167 <= p_0_0_0116950_fu_164;
        p_0_0_01169_152_load_reg_1172 <= p_0_0_01169_152_fu_168;
        p_0_0_01169_254_load_reg_1178 <= p_0_0_01169_254_fu_172;
    end
end

always @ (*) begin
    if (((icmp_ln57_fu_380_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd1))) begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter2_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        cur_ce0_local = 1'b1;
    end else begin
        cur_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buf_1_ce0_local = 1'b1;
    end else begin
        line_buf_1_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_1_ce1_local = 1'b1;
    end else begin
        line_buf_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
        line_buf_1_we0_local = 1'b1;
    end else begin
        line_buf_1_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        line_buf_ce0_local = 1'b1;
    end else begin
        line_buf_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        line_buf_ce1_local = 1'b1;
    end else begin
        line_buf_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln57_reg_1132 == 1'd0))) begin
        line_buf_we0_local = 1'b1;
    end else begin
        line_buf_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nxt_ce0_local = 1'b1;
    end else begin
        nxt_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'd1 == and_ln83_reg_1163_pp0_iter3_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        nxt_we0_local = 1'b1;
    end else begin
        nxt_we0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0116949_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116949_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_0116950_out_ap_vld = 1'b1;
    end else begin
        p_0_0_0116950_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01169_151_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01169_151_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01169_152_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01169_152_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01169_253_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01169_253_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_exit_ready_pp0_iter3_reg == 1'b1) & (icmp_ln57_reg_1132_pp0_iter2_reg == 1'd1))) begin
        p_0_0_01169_254_out_ap_vld = 1'b1;
    end else begin
        p_0_0_01169_254_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln57_1_fu_386_p2 = (indvar_flatten_fu_160 + 17'd1);

assign add_ln57_fu_398_p2 = (i_fu_156 + 9'd1);

assign add_ln58_fu_501_p2 = (select_ln57_fu_410_p3 + 9'd1);

assign add_ln69_fu_464_p2 = (tmp_s_fu_430_p3 + zext_ln69_fu_460_p1);

assign add_ln86_fu_760_p2 = ($signed(trunc_ln58_reg_1146_pp0_iter3_reg) + $signed(8'd255));

assign add_ln88_fu_567_p2 = ($signed(sext_ln88_fu_563_p1) + $signed(p_0_0_0116950_cast_fu_553_p1));

assign add_ln91_fu_625_p2 = ($signed(sext_ln91_fu_621_p1) + $signed(line_buf_load_cast_fu_611_p1));

assign add_ln96_1_fu_728_p2 = ($signed(sext_ln96_5_fu_724_p1) + $signed(sext_ln96_2_fu_706_p1));

assign add_ln96_fu_718_p2 = ($signed(sext_ln96_1_fu_702_p1) + $signed(sext_ln96_4_fu_714_p1));

assign add_ln99_fu_881_p2 = (trunc_ln2_fu_851_p4 + zext_ln99_fu_877_p1);

assign and_ln83_fu_495_p2 = (icmp_ln83_fu_489_p2 & icmp_fu_448_p2);

assign and_ln96_fu_829_p2 = (xor_ln96_fu_801_p2 & or_ln96_fu_823_p2);

assign and_ln99_1_fu_963_p2 = (xor_ln99_1_fu_957_p2 & icmp_ln99_fu_923_p2);

assign and_ln99_2_fu_977_p2 = (icmp_ln99_1_fu_937_p2 & and_ln99_fu_901_p2);

assign and_ln99_3_fu_1001_p2 = (xor_ln99_3_fu_995_p2 & or_ln99_fu_989_p2);

assign and_ln99_4_fu_1007_p2 = (tmp_11_fu_887_p3 & select_ln99_1_fu_969_p3);

assign and_ln99_5_fu_1025_p2 = (xor_ln99_4_fu_1019_p2 & tmp_8_fu_843_p3);

assign and_ln99_fu_901_p2 = (xor_ln99_fu_895_p2 & tmp_10_fu_869_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign ap_ready = ap_ready_sig;

assign cur_address0 = zext_ln69_1_fu_470_p1;

assign cur_ce0 = cur_ce0_local;

assign empty_41_fu_557_p2 = ($signed(p_0_0_01169_151_cast_fu_549_p1) + $signed(p_0_0_01169_254_cast_fu_545_p1));

assign empty_42_fu_615_p2 = ($signed(p_0_0_0116949_cast_fu_607_p1) + $signed(p_0_0_01169_253_cast_fu_603_p1));

assign empty_fu_531_p2 = ($signed(trunc_ln69_reg_1136) + $signed(8'd255));

assign icmp_fu_448_p2 = ((tmp_fu_438_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln57_fu_380_p2 = ((indvar_flatten_fu_160 == 17'd65536) ? 1'b1 : 1'b0);

assign icmp_ln58_fu_404_p2 = ((j_fu_152 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln83_fu_489_p2 = ((tmp_1_fu_479_p4 != 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln99_1_fu_937_p2 = ((tmp_13_fu_929_p3 == 4'd15) ? 1'b1 : 1'b0);

assign icmp_ln99_2_fu_943_p2 = ((tmp_13_fu_929_p3 == 4'd0) ? 1'b1 : 1'b0);

assign icmp_ln99_fu_923_p2 = ((tmp_12_fu_915_p3 == 3'd7) ? 1'b1 : 1'b0);

assign line_buf_1_address1 = zext_ln58_fu_454_p1;

assign line_buf_address1 = zext_ln58_fu_454_p1;

assign line_buf_load_cast_fu_611_p0 = line_buf_q1;

assign line_buf_load_cast_fu_611_p1 = line_buf_load_cast_fu_611_p0;

assign mul_ln96_1_fu_322_p1 = 63'd6709248;

assign mul_ln96_fu_327_p1 = 65'd26845184;

assign nxt_address0 = zext_ln99_1_fu_772_p1;

assign nxt_ce0 = nxt_ce0_local;

assign nxt_d0 = select_ln99_3_fu_1045_p3;

assign nxt_we0 = nxt_we0_local;

assign or_ln96_1_fu_806_p2 = (xor_ln96_fu_801_p2 | tmp_7_fu_793_p3);

assign or_ln96_fu_823_p2 = (xor_ln96_2_fu_817_p2 | tmp_7_fu_793_p3);

assign or_ln99_1_fu_1039_p2 = (and_ln99_5_fu_1025_p2 | and_ln99_3_fu_1001_p2);

assign or_ln99_2_fu_1013_p2 = (and_ln99_4_fu_1007_p2 | and_ln99_2_fu_977_p2);

assign or_ln99_fu_989_p2 = (xor_ln99_2_fu_983_p2 | tmp_11_fu_887_p3);

assign out_1_fu_783_p2 = ($signed(sext_ln96_6_fu_777_p1) + $signed(zext_ln96_fu_780_p1));

assign out_2_fu_835_p3 = ((and_ln96_fu_829_p2[0:0] == 1'b1) ? 40'd549755813887 : sext_ln96_7_fu_789_p1);

assign p_0_0_0116949_cast_fu_607_p0 = p_0_0_0116949_fu_140;

assign p_0_0_0116949_cast_fu_607_p1 = p_0_0_0116949_cast_fu_607_p0;

assign p_0_0_0116949_out = p_0_0_0116949_fu_140;

assign p_0_0_0116950_cast_fu_553_p0 = p_0_0_0116950_fu_164;

assign p_0_0_0116950_cast_fu_553_p1 = p_0_0_0116950_cast_fu_553_p0;

assign p_0_0_0116950_out = p_0_0_0116950_load_reg_1167;

assign p_0_0_01169_151_cast_fu_549_p0 = p_0_0_01169_151_fu_144;

assign p_0_0_01169_151_cast_fu_549_p1 = p_0_0_01169_151_cast_fu_549_p0;

assign p_0_0_01169_151_out = p_0_0_01169_151_fu_144;

assign p_0_0_01169_152_out = p_0_0_01169_152_load_reg_1172;

assign p_0_0_01169_253_cast_fu_603_p0 = p_0_0_01169_253_fu_148;

assign p_0_0_01169_253_cast_fu_603_p1 = p_0_0_01169_253_cast_fu_603_p0;

assign p_0_0_01169_253_out = p_0_0_01169_253_fu_148;

assign p_0_0_01169_254_cast_fu_545_p0 = p_0_0_01169_254_fu_172;

assign p_0_0_01169_254_cast_fu_545_p1 = p_0_0_01169_254_cast_fu_545_p0;

assign p_0_0_01169_254_out = p_0_0_01169_254_load_reg_1178;

assign select_ln57_1_fu_418_p3 = ((icmp_ln58_fu_404_p2[0:0] == 1'b1) ? add_ln57_fu_398_p2 : i_fu_156);

assign select_ln57_fu_410_p3 = ((icmp_ln58_fu_404_p2[0:0] == 1'b1) ? 9'd0 : j_fu_152);

assign select_ln99_1_fu_969_p3 = ((and_ln99_fu_901_p2[0:0] == 1'b1) ? and_ln99_1_fu_963_p2 : icmp_ln99_1_fu_937_p2);

assign select_ln99_2_fu_1031_p3 = ((and_ln99_3_fu_1001_p2[0:0] == 1'b1) ? 24'd8388607 : 24'd8388608);

assign select_ln99_3_fu_1045_p3 = ((or_ln99_1_fu_1039_p2[0:0] == 1'b1) ? select_ln99_2_fu_1031_p3 : add_ln99_fu_881_p2);

assign select_ln99_fu_949_p3 = ((and_ln99_fu_901_p2[0:0] == 1'b1) ? icmp_ln99_1_fu_937_p2 : icmp_ln99_2_fu_943_p2);

assign sext_ln88_fu_563_p1 = $signed(empty_41_fu_557_p2);

assign sext_ln89_1_fu_593_p1 = $signed(shl_ln_fu_585_p3);

assign sext_ln89_fu_581_p1 = $signed(tmp_3_fu_573_p3);

assign sext_ln91_fu_621_p1 = $signed(empty_42_fu_615_p2);

assign sext_ln92_1_fu_651_p1 = $signed(shl_ln1_fu_643_p3);

assign sext_ln92_fu_639_p1 = $signed(tmp_4_fu_631_p3);

assign sext_ln96_1_fu_702_p1 = $signed(shl_ln2_fu_691_p3);

assign sext_ln96_2_fu_706_p1 = $signed(mul_ln96_fu_327_p2);

assign sext_ln96_4_fu_714_p1 = $signed(mul_ln96_1_fu_322_p2);

assign sext_ln96_5_fu_724_p1 = $signed(add_ln96_fu_718_p2);

assign sext_ln96_6_fu_777_p1 = $signed(out_reg_1204);

assign sext_ln96_7_fu_789_p1 = out_1_fu_783_p2;

assign shl_ln1_fu_643_p3 = {{cur_q0}, {12'd0}};

assign shl_ln2_fu_691_p3 = {{p_0_0_01169_152_load_reg_1172}, {39'd0}};

assign shl_ln_fu_585_p3 = {{line_buf_1_q1}, {12'd0}};

assign sum_axis_fu_597_p2 = ($signed(sext_ln89_fu_581_p1) + $signed(sext_ln89_1_fu_593_p1));

assign sum_diag_fu_655_p2 = ($signed(sext_ln92_fu_639_p1) + $signed(sext_ln92_1_fu_651_p1));

assign tmp_10_fu_869_p3 = out_2_fu_835_p3[32'd35];

assign tmp_11_fu_887_p3 = add_ln99_fu_881_p2[32'd23];

assign tmp_12_fu_915_p3 = {{out_2_fu_835_p3[39:37]}};

assign tmp_13_fu_929_p3 = {{out_2_fu_835_p3[39:36]}};

assign tmp_14_fu_907_p3 = out_2_fu_835_p3[32'd36];

assign tmp_1_fu_479_p4 = {{select_ln57_fu_410_p3[8:1]}};

assign tmp_2_fu_765_p3 = {{empty_reg_1183_pp0_iter3_reg}, {add_ln86_fu_760_p2}};

assign tmp_3_fu_573_p3 = {{add_ln88_fu_567_p2}, {12'd0}};

assign tmp_4_fu_631_p3 = {{add_ln91_fu_625_p2}, {12'd0}};

assign tmp_7_fu_793_p3 = out_1_fu_783_p2[32'd38];

assign tmp_8_fu_843_p3 = out_2_fu_835_p3[32'd39];

assign tmp_9_fu_861_p3 = out_2_fu_835_p3[32'd11];

assign tmp_fu_438_p4 = {{select_ln57_1_fu_418_p3[8:1]}};

assign tmp_s_fu_430_p3 = {{trunc_ln69_fu_426_p1}, {8'd0}};

assign trunc_ln2_fu_851_p4 = {{out_2_fu_835_p3[35:12]}};

assign trunc_ln58_fu_475_p1 = select_ln57_fu_410_p3[7:0];

assign trunc_ln69_fu_426_p1 = select_ln57_1_fu_418_p3[7:0];

assign xor_ln96_1_fu_812_p2 = (tmp_5_reg_1198 ^ or_ln96_1_fu_806_p2);

assign xor_ln96_2_fu_817_p2 = (xor_ln96_1_fu_812_p2 ^ 1'd1);

assign xor_ln96_fu_801_p2 = (tmp_5_reg_1198 ^ 1'd1);

assign xor_ln99_1_fu_957_p2 = (tmp_14_fu_907_p3 ^ 1'd1);

assign xor_ln99_2_fu_983_p2 = (select_ln99_fu_949_p3 ^ 1'd1);

assign xor_ln99_3_fu_995_p2 = (tmp_8_fu_843_p3 ^ 1'd1);

assign xor_ln99_4_fu_1019_p2 = (or_ln99_2_fu_1013_p2 ^ 1'd1);

assign xor_ln99_fu_895_p2 = (tmp_11_fu_887_p3 ^ 1'd1);

assign zext_ln58_fu_454_p1 = select_ln57_fu_410_p3;

assign zext_ln69_1_fu_470_p1 = add_ln69_fu_464_p2;

assign zext_ln69_fu_460_p1 = select_ln57_fu_410_p3;

assign zext_ln96_fu_780_p1 = tmp_6_reg_1209;

assign zext_ln99_1_fu_772_p1 = tmp_2_fu_765_p3;

assign zext_ln99_fu_877_p1 = tmp_9_fu_861_p3;

always @ (posedge ap_clk) begin
    sum_axis_reg_1188[11:0] <= 12'b000000000000;
    sum_diag_reg_1193[11:0] <= 12'b000000000000;
end

endmodule //top_kernel_compute_Pipeline_VITIS_LOOP_57_6_VITIS_LOOP_58_7
