-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2025.1.1 (lin64) Build 6233196 Thu Sep 11 21:27:11 MDT 2025
-- Date        : Tue Mar 10 16:14:13 2026
-- Host        : ece-linlabsrv01 running 64-bit Red Hat Enterprise Linux release 8.10 (Ootpa)
-- Command     : write_vhdl -force -mode synth_stub
--               /nethome/shanda34/FPGA_ECE8893_SJH/2026_Spring/lab3/project_1/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0_stub.vhdl
-- Design      : bd_0_hls_inst_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xczu3eg-sbva484-1-e
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity bd_0_hls_inst_0 is
  Port ( 
    s_axi_control_ARADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_ARREADY : out STD_LOGIC;
    s_axi_control_ARVALID : in STD_LOGIC;
    s_axi_control_AWADDR : in STD_LOGIC_VECTOR ( 5 downto 0 );
    s_axi_control_AWREADY : out STD_LOGIC;
    s_axi_control_AWVALID : in STD_LOGIC;
    s_axi_control_BREADY : in STD_LOGIC;
    s_axi_control_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_BVALID : out STD_LOGIC;
    s_axi_control_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_RREADY : in STD_LOGIC;
    s_axi_control_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    s_axi_control_RVALID : out STD_LOGIC;
    s_axi_control_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    s_axi_control_WREADY : out STD_LOGIC;
    s_axi_control_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    s_axi_control_WVALID : in STD_LOGIC;
    ap_clk : in STD_LOGIC;
    ap_rst_n : in STD_LOGIC;
    interrupt : out STD_LOGIC;
    m_axi_in_r_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_in_r_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_in_r_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_in_r_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_in_r_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_ARREADY : in STD_LOGIC;
    m_axi_in_r_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_in_r_ARVALID : out STD_LOGIC;
    m_axi_in_r_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_in_r_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_in_r_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_in_r_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_in_r_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_AWREADY : in STD_LOGIC;
    m_axi_in_r_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_in_r_AWVALID : out STD_LOGIC;
    m_axi_in_r_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_in_r_BREADY : out STD_LOGIC;
    m_axi_in_r_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_BVALID : in STD_LOGIC;
    m_axi_in_r_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_in_r_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_in_r_RLAST : in STD_LOGIC;
    m_axi_in_r_RREADY : out STD_LOGIC;
    m_axi_in_r_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_in_r_RVALID : in STD_LOGIC;
    m_axi_in_r_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_in_r_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_in_r_WLAST : out STD_LOGIC;
    m_axi_in_r_WREADY : in STD_LOGIC;
    m_axi_in_r_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_in_r_WVALID : out STD_LOGIC;
    m_axi_out_r_ARADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_out_r_ARBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_ARCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_ARID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_out_r_ARLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_out_r_ARLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_ARPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_out_r_ARQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_ARREADY : in STD_LOGIC;
    m_axi_out_r_ARREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_ARSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_out_r_ARVALID : out STD_LOGIC;
    m_axi_out_r_AWADDR : out STD_LOGIC_VECTOR ( 63 downto 0 );
    m_axi_out_r_AWBURST : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_AWCACHE : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_AWID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_out_r_AWLEN : out STD_LOGIC_VECTOR ( 7 downto 0 );
    m_axi_out_r_AWLOCK : out STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_AWPROT : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_out_r_AWQOS : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_AWREADY : in STD_LOGIC;
    m_axi_out_r_AWREGION : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_AWSIZE : out STD_LOGIC_VECTOR ( 2 downto 0 );
    m_axi_out_r_AWVALID : out STD_LOGIC;
    m_axi_out_r_BID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_out_r_BREADY : out STD_LOGIC;
    m_axi_out_r_BRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_BVALID : in STD_LOGIC;
    m_axi_out_r_RDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_out_r_RID : in STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_out_r_RLAST : in STD_LOGIC;
    m_axi_out_r_RREADY : out STD_LOGIC;
    m_axi_out_r_RRESP : in STD_LOGIC_VECTOR ( 1 downto 0 );
    m_axi_out_r_RVALID : in STD_LOGIC;
    m_axi_out_r_WDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    m_axi_out_r_WID : out STD_LOGIC_VECTOR ( 0 to 0 );
    m_axi_out_r_WLAST : out STD_LOGIC;
    m_axi_out_r_WREADY : in STD_LOGIC;
    m_axi_out_r_WSTRB : out STD_LOGIC_VECTOR ( 3 downto 0 );
    m_axi_out_r_WVALID : out STD_LOGIC
  );

  attribute CHECK_LICENSE_TYPE : string;
  attribute CHECK_LICENSE_TYPE of bd_0_hls_inst_0 : entity is "bd_0_hls_inst_0,top_kernel,{}";
  attribute CORE_GENERATION_INFO : string;
  attribute CORE_GENERATION_INFO of bd_0_hls_inst_0 : entity is "bd_0_hls_inst_0,top_kernel,{x_ipProduct=Vivado 2025.1.1,x_ipVendor=xilinx.com,x_ipLibrary=hls,x_ipName=top_kernel,x_ipVersion=1.0,x_ipCoreRevision=2114515030,x_ipLanguage=VERILOG,x_ipSimLanguage=MIXED,C_S_AXI_CONTROL_ADDR_WIDTH=6,C_S_AXI_CONTROL_DATA_WIDTH=32,C_M_AXI_IN_R_ID_WIDTH=1,C_M_AXI_IN_R_ADDR_WIDTH=64,C_M_AXI_IN_R_DATA_WIDTH=32,C_M_AXI_IN_R_AWUSER_WIDTH=1,C_M_AXI_IN_R_ARUSER_WIDTH=1,C_M_AXI_IN_R_WUSER_WIDTH=1,C_M_AXI_IN_R_RUSER_WIDTH=1,C_M_AXI_IN_R_BUSER_WIDTH=1,C_M_AXI_IN_R_USER_VALUE=0x00000000,C_M_AXI_IN_R_PROT_VALUE=000,C_M_AXI_IN_R_CACHE_VALUE=0011,C_M_AXI_OUT_R_ID_WIDTH=1,C_M_AXI_OUT_R_ADDR_WIDTH=64,C_M_AXI_OUT_R_DATA_WIDTH=32,C_M_AXI_OUT_R_AWUSER_WIDTH=1,C_M_AXI_OUT_R_ARUSER_WIDTH=1,C_M_AXI_OUT_R_WUSER_WIDTH=1,C_M_AXI_OUT_R_RUSER_WIDTH=1,C_M_AXI_OUT_R_BUSER_WIDTH=1,C_M_AXI_OUT_R_USER_VALUE=0x00000000,C_M_AXI_OUT_R_PROT_VALUE=000,C_M_AXI_OUT_R_CACHE_VALUE=0011}";
  attribute DowngradeIPIdentifiedWarnings : string;
  attribute DowngradeIPIdentifiedWarnings of bd_0_hls_inst_0 : entity is "yes";
  attribute IP_DEFINITION_SOURCE : string;
  attribute IP_DEFINITION_SOURCE of bd_0_hls_inst_0 : entity is "HLS";
  attribute hls_module : string;
  attribute hls_module of bd_0_hls_inst_0 : entity is "yes";
end bd_0_hls_inst_0;

architecture stub of bd_0_hls_inst_0 is
  attribute syn_black_box : boolean;
  attribute black_box_pad_pin : string;
  attribute syn_black_box of stub : architecture is true;
  attribute black_box_pad_pin of stub : architecture is "s_axi_control_ARADDR[5:0],s_axi_control_ARREADY,s_axi_control_ARVALID,s_axi_control_AWADDR[5:0],s_axi_control_AWREADY,s_axi_control_AWVALID,s_axi_control_BREADY,s_axi_control_BRESP[1:0],s_axi_control_BVALID,s_axi_control_RDATA[31:0],s_axi_control_RREADY,s_axi_control_RRESP[1:0],s_axi_control_RVALID,s_axi_control_WDATA[31:0],s_axi_control_WREADY,s_axi_control_WSTRB[3:0],s_axi_control_WVALID,ap_clk,ap_rst_n,interrupt,m_axi_in_r_ARADDR[63:0],m_axi_in_r_ARBURST[1:0],m_axi_in_r_ARCACHE[3:0],m_axi_in_r_ARID[0:0],m_axi_in_r_ARLEN[7:0],m_axi_in_r_ARLOCK[1:0],m_axi_in_r_ARPROT[2:0],m_axi_in_r_ARQOS[3:0],m_axi_in_r_ARREADY,m_axi_in_r_ARREGION[3:0],m_axi_in_r_ARSIZE[2:0],m_axi_in_r_ARVALID,m_axi_in_r_AWADDR[63:0],m_axi_in_r_AWBURST[1:0],m_axi_in_r_AWCACHE[3:0],m_axi_in_r_AWID[0:0],m_axi_in_r_AWLEN[7:0],m_axi_in_r_AWLOCK[1:0],m_axi_in_r_AWPROT[2:0],m_axi_in_r_AWQOS[3:0],m_axi_in_r_AWREADY,m_axi_in_r_AWREGION[3:0],m_axi_in_r_AWSIZE[2:0],m_axi_in_r_AWVALID,m_axi_in_r_BID[0:0],m_axi_in_r_BREADY,m_axi_in_r_BRESP[1:0],m_axi_in_r_BVALID,m_axi_in_r_RDATA[31:0],m_axi_in_r_RID[0:0],m_axi_in_r_RLAST,m_axi_in_r_RREADY,m_axi_in_r_RRESP[1:0],m_axi_in_r_RVALID,m_axi_in_r_WDATA[31:0],m_axi_in_r_WID[0:0],m_axi_in_r_WLAST,m_axi_in_r_WREADY,m_axi_in_r_WSTRB[3:0],m_axi_in_r_WVALID,m_axi_out_r_ARADDR[63:0],m_axi_out_r_ARBURST[1:0],m_axi_out_r_ARCACHE[3:0],m_axi_out_r_ARID[0:0],m_axi_out_r_ARLEN[7:0],m_axi_out_r_ARLOCK[1:0],m_axi_out_r_ARPROT[2:0],m_axi_out_r_ARQOS[3:0],m_axi_out_r_ARREADY,m_axi_out_r_ARREGION[3:0],m_axi_out_r_ARSIZE[2:0],m_axi_out_r_ARVALID,m_axi_out_r_AWADDR[63:0],m_axi_out_r_AWBURST[1:0],m_axi_out_r_AWCACHE[3:0],m_axi_out_r_AWID[0:0],m_axi_out_r_AWLEN[7:0],m_axi_out_r_AWLOCK[1:0],m_axi_out_r_AWPROT[2:0],m_axi_out_r_AWQOS[3:0],m_axi_out_r_AWREADY,m_axi_out_r_AWREGION[3:0],m_axi_out_r_AWSIZE[2:0],m_axi_out_r_AWVALID,m_axi_out_r_BID[0:0],m_axi_out_r_BREADY,m_axi_out_r_BRESP[1:0],m_axi_out_r_BVALID,m_axi_out_r_RDATA[31:0],m_axi_out_r_RID[0:0],m_axi_out_r_RLAST,m_axi_out_r_RREADY,m_axi_out_r_RRESP[1:0],m_axi_out_r_RVALID,m_axi_out_r_WDATA[31:0],m_axi_out_r_WID[0:0],m_axi_out_r_WLAST,m_axi_out_r_WREADY,m_axi_out_r_WSTRB[3:0],m_axi_out_r_WVALID";
  attribute X_INTERFACE_INFO : string;
  attribute X_INTERFACE_INFO of s_axi_control_ARADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARADDR";
  attribute X_INTERFACE_MODE : string;
  attribute X_INTERFACE_MODE of s_axi_control_ARADDR : signal is "slave";
  attribute X_INTERFACE_PARAMETER : string;
  attribute X_INTERFACE_PARAMETER of s_axi_control_ARADDR : signal is "XIL_INTERFACENAME s_axi_control, ADDR_WIDTH 6, DATA_WIDTH 32, PROTOCOL AXI4LITE, READ_WRITE_MODE READ_WRITE, FREQ_HZ 100000000.0, ID_WIDTH 0, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_BURST 0, HAS_LOCK 0, HAS_PROT 0, HAS_CACHE 0, HAS_QOS 0, HAS_REGION 0, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, SUPPORTS_NARROW_BURST 0, NUM_READ_OUTSTANDING 1, NUM_WRITE_OUTSTANDING 1, MAX_BURST_LENGTH 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of s_axi_control_ARREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARREADY";
  attribute X_INTERFACE_INFO of s_axi_control_ARVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control ARVALID";
  attribute X_INTERFACE_INFO of s_axi_control_AWADDR : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWADDR";
  attribute X_INTERFACE_INFO of s_axi_control_AWREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWREADY";
  attribute X_INTERFACE_INFO of s_axi_control_AWVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control AWVALID";
  attribute X_INTERFACE_INFO of s_axi_control_BREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BREADY";
  attribute X_INTERFACE_INFO of s_axi_control_BRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BRESP";
  attribute X_INTERFACE_INFO of s_axi_control_BVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control BVALID";
  attribute X_INTERFACE_INFO of s_axi_control_RDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RDATA";
  attribute X_INTERFACE_INFO of s_axi_control_RREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RREADY";
  attribute X_INTERFACE_INFO of s_axi_control_RRESP : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RRESP";
  attribute X_INTERFACE_INFO of s_axi_control_RVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control RVALID";
  attribute X_INTERFACE_INFO of s_axi_control_WDATA : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WDATA";
  attribute X_INTERFACE_INFO of s_axi_control_WREADY : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WREADY";
  attribute X_INTERFACE_INFO of s_axi_control_WSTRB : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WSTRB";
  attribute X_INTERFACE_INFO of s_axi_control_WVALID : signal is "xilinx.com:interface:aximm:1.0 s_axi_control WVALID";
  attribute X_INTERFACE_INFO of ap_clk : signal is "xilinx.com:signal:clock:1.0 ap_clk CLK";
  attribute X_INTERFACE_MODE of ap_clk : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_clk : signal is "XIL_INTERFACENAME ap_clk, ASSOCIATED_BUSIF s_axi_control:m_axi_in_r:m_axi_out_r, ASSOCIATED_RESET ap_rst_n, FREQ_HZ 100000000.0, FREQ_TOLERANCE_HZ 0, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of ap_rst_n : signal is "xilinx.com:signal:reset:1.0 ap_rst_n RST";
  attribute X_INTERFACE_MODE of ap_rst_n : signal is "slave";
  attribute X_INTERFACE_PARAMETER of ap_rst_n : signal is "XIL_INTERFACENAME ap_rst_n, POLARITY ACTIVE_LOW, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of interrupt : signal is "xilinx.com:signal:interrupt:1.0 interrupt INTERRUPT";
  attribute X_INTERFACE_MODE of interrupt : signal is "master";
  attribute X_INTERFACE_PARAMETER of interrupt : signal is "XIL_INTERFACENAME interrupt, SENSITIVITY LEVEL_HIGH, PortWidth 1";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARADDR";
  attribute X_INTERFACE_MODE of m_axi_in_r_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_in_r_ARADDR : signal is "XIL_INTERFACENAME m_axi_in_r, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE READ_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARBURST";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARID";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARLEN";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARPROT";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARQOS";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARREADY";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARREGION";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_in_r_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r ARVALID";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWADDR";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWBURST";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWID";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWLEN";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWPROT";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWQOS";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWREADY";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWREGION";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_in_r_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r AWVALID";
  attribute X_INTERFACE_INFO of m_axi_in_r_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r BID";
  attribute X_INTERFACE_INFO of m_axi_in_r_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r BREADY";
  attribute X_INTERFACE_INFO of m_axi_in_r_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r BRESP";
  attribute X_INTERFACE_INFO of m_axi_in_r_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r BVALID";
  attribute X_INTERFACE_INFO of m_axi_in_r_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RDATA";
  attribute X_INTERFACE_INFO of m_axi_in_r_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RID";
  attribute X_INTERFACE_INFO of m_axi_in_r_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RLAST";
  attribute X_INTERFACE_INFO of m_axi_in_r_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RREADY";
  attribute X_INTERFACE_INFO of m_axi_in_r_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RRESP";
  attribute X_INTERFACE_INFO of m_axi_in_r_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r RVALID";
  attribute X_INTERFACE_INFO of m_axi_in_r_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WDATA";
  attribute X_INTERFACE_INFO of m_axi_in_r_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WID";
  attribute X_INTERFACE_INFO of m_axi_in_r_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WLAST";
  attribute X_INTERFACE_INFO of m_axi_in_r_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WREADY";
  attribute X_INTERFACE_INFO of m_axi_in_r_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WSTRB";
  attribute X_INTERFACE_INFO of m_axi_in_r_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_in_r WVALID";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARADDR";
  attribute X_INTERFACE_MODE of m_axi_out_r_ARADDR : signal is "master";
  attribute X_INTERFACE_PARAMETER of m_axi_out_r_ARADDR : signal is "XIL_INTERFACENAME m_axi_out_r, NUM_READ_OUTSTANDING 16, NUM_WRITE_OUTSTANDING 16, MAX_READ_BURST_LENGTH 16, MAX_WRITE_BURST_LENGTH 16, MAX_BURST_LENGTH 256, PROTOCOL AXI4, READ_WRITE_MODE WRITE_ONLY, HAS_BURST 0, SUPPORTS_NARROW_BURST 0, ADDR_WIDTH 64, DATA_WIDTH 32, FREQ_HZ 100000000.0, ID_WIDTH 1, AWUSER_WIDTH 0, ARUSER_WIDTH 0, WUSER_WIDTH 0, RUSER_WIDTH 0, BUSER_WIDTH 0, HAS_LOCK 1, HAS_PROT 1, HAS_CACHE 1, HAS_QOS 1, HAS_REGION 1, HAS_WSTRB 1, HAS_BRESP 1, HAS_RRESP 1, PHASE 0.0, CLK_DOMAIN bd_0_ap_clk_0, NUM_READ_THREADS 1, NUM_WRITE_THREADS 1, RUSER_BITS_PER_BYTE 0, WUSER_BITS_PER_BYTE 0, INSERT_VIP 0";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARBURST";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARCACHE";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARID";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARLEN";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARLOCK";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARPROT";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARQOS";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARREADY";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARREGION";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARSIZE";
  attribute X_INTERFACE_INFO of m_axi_out_r_ARVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r ARVALID";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWADDR : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWADDR";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWBURST : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWBURST";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWCACHE : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWCACHE";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWID";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWLEN : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWLEN";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWLOCK : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWLOCK";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWPROT : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWPROT";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWQOS : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWQOS";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWREADY";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWREGION : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWREGION";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWSIZE : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWSIZE";
  attribute X_INTERFACE_INFO of m_axi_out_r_AWVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r AWVALID";
  attribute X_INTERFACE_INFO of m_axi_out_r_BID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r BID";
  attribute X_INTERFACE_INFO of m_axi_out_r_BREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r BREADY";
  attribute X_INTERFACE_INFO of m_axi_out_r_BRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r BRESP";
  attribute X_INTERFACE_INFO of m_axi_out_r_BVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r BVALID";
  attribute X_INTERFACE_INFO of m_axi_out_r_RDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RDATA";
  attribute X_INTERFACE_INFO of m_axi_out_r_RID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RID";
  attribute X_INTERFACE_INFO of m_axi_out_r_RLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RLAST";
  attribute X_INTERFACE_INFO of m_axi_out_r_RREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RREADY";
  attribute X_INTERFACE_INFO of m_axi_out_r_RRESP : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RRESP";
  attribute X_INTERFACE_INFO of m_axi_out_r_RVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r RVALID";
  attribute X_INTERFACE_INFO of m_axi_out_r_WDATA : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WDATA";
  attribute X_INTERFACE_INFO of m_axi_out_r_WID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WID";
  attribute X_INTERFACE_INFO of m_axi_out_r_WLAST : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WLAST";
  attribute X_INTERFACE_INFO of m_axi_out_r_WREADY : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WREADY";
  attribute X_INTERFACE_INFO of m_axi_out_r_WSTRB : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WSTRB";
  attribute X_INTERFACE_INFO of m_axi_out_r_WVALID : signal is "xilinx.com:interface:aximm:1.0 m_axi_out_r WVALID";
  attribute X_CORE_INFO : string;
  attribute X_CORE_INFO of stub : architecture is "top_kernel,Vivado 2025.1.1";
begin
end;
