

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST", "Parent" : "", "Child" : ["1", "2", "3", "4", "5", "6", "7", "8", "91", "93"],
		"CDFG" : "top_kernel",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "Dataflow", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "1",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4311956", "EstimateLatencyMax" : "4311956",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "1",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"InputProcess" : [
			{"ID" : "6", "Name" : "entry_proc_U0"},
			{"ID" : "7", "Name" : "read_input_U0"}],
		"OutputProcess" : [
			{"ID" : "91", "Name" : "write_output_U0"}],
		"Port" : [
			{"Name" : "A_in", "Type" : "MAXI", "Direction" : "I",
				"SubConnect" : [
					{"ID" : "7", "SubInstance" : "read_input_U0", "Port" : "A_in"}]},
			{"Name" : "A_out", "Type" : "MAXI", "Direction" : "O",
				"SubConnect" : [
					{"ID" : "91", "SubInstance" : "write_output_U0", "Port" : "A_out"}]},
			{"Name" : "A_in_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_out_r", "Type" : "None", "Direction" : "I"}]},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_initial_U", "Parent" : "0"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_final_U", "Parent" : "0"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U", "Parent" : "0"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_in_m_axi_U", "Parent" : "0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_m_axi_U", "Parent" : "0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0", "Parent" : "0",
		"CDFG" : "entry_proc",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "1",
		"VariableLatency" : "0", "ExactLatency" : "0", "EstimateLatencyMin" : "0", "EstimateLatencyMax" : "0",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_out_r", "Type" : "None", "Direction" : "I"},
			{"Name" : "A_out_r_c", "Type" : "Fifo", "Direction" : "O", "DependentProc" : ["91"], "DependentChan" : "93", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "A_out_r_c_blk_n", "Type" : "RtlSignal"}]}]},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_U0", "Parent" : "0",
		"CDFG" : "read_input",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "197128", "EstimateLatencyMax" : "197128",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "A_in", "Type" : "MAXI", "Direction" : "I",
				"BlockSignal" : [
					{"Name" : "A_in_blk_n_AR", "Type" : "RtlSignal"},
					{"Name" : "A_in_blk_n_R", "Type" : "RtlSignal"}]},
			{"Name" : "A_in1", "Type" : "None", "Direction" : "I"},
			{"Name" : "stream_out", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["8"], "DependentChan" : "1"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_8_2", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "12", "FirstState" : "ap_ST_fsm_state10", "LastState" : ["ap_ST_fsm_state12"], "QuitState" : ["ap_ST_fsm_state10"], "PreState" : ["ap_ST_fsm_state9"], "PostState" : ["ap_ST_fsm_state9"], "OneDepthLoop" : "0", "OneStateBlock": ""}},
			{"Name" : "VITIS_LOOP_7_1", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "12", "FirstState" : "ap_ST_fsm_state9", "LastState" : ["ap_ST_fsm_state10"], "QuitState" : ["ap_ST_fsm_state9"], "PreState" : ["ap_ST_fsm_state8"], "PostState" : ["ap_ST_fsm_state1"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "8", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0", "Parent" : "0", "Child" : ["9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "26", "31", "42", "48", "84"],
		"CDFG" : "compute",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "4049281", "EstimateLatencyMax" : "4049281",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "stream_in", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["7"], "DependentChan" : "1",
				"SubConnect" : [
					{"ID" : "19", "SubInstance" : "grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78", "Port" : "stream_in", "Inst_start_state" : "1", "Inst_end_state" : "2"}]},
			{"Name" : "stream_out", "Type" : "Memory", "Direction" : "O", "DependentProc" : ["91"], "DependentChan" : "2",
				"SubConnect" : [
					{"ID" : "31", "SubInstance" : "grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110", "Port" : "stream_out", "Inst_start_state" : "3", "Inst_end_state" : "11"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_35_3", "PipelineType" : "no",
				"LoopDec" : {"FSMBitwidth" : "11", "FirstState" : "ap_ST_fsm_state3", "LastState" : ["ap_ST_fsm_state10"], "QuitState" : ["ap_ST_fsm_state3"], "PreState" : ["ap_ST_fsm_state2"], "PostState" : ["ap_ST_fsm_state11"], "OneDepthLoop" : "0", "OneStateBlock": ""}}]},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_U", "Parent" : "8"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_1_U", "Parent" : "8"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_2_U", "Parent" : "8"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_3_U", "Parent" : "8"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_4_U", "Parent" : "8"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_5_U", "Parent" : "8"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_6_U", "Parent" : "8"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_7_U", "Parent" : "8"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_8_U", "Parent" : "8"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.nxt_U", "Parent" : "8"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78", "Parent" : "8", "Child" : ["20", "21", "22", "23", "24", "25"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65549", "EstimateLatencyMax" : "65549",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "stream_in", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_8", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_27_1_VITIS_LOOP_28_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.mul_9ns_11ns_19_1_1_U6", "Parent" : "19"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.urem_9ns_3ns_2_13_1_U7", "Parent" : "19"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.urem_9ns_3ns_2_13_1_U8", "Parent" : "19"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.mul_9ns_11ns_19_1_1_U9", "Parent" : "19"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.mac_muladd_8ns_7ns_8ns_13_4_1_U10", "Parent" : "19"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_27_1_VITIS_LOOP_28_2_fu_78.flow_control_loop_pipe_sequential_init_U", "Parent" : "19"},
	{"ID" : "26", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_37_4_fu_102", "Parent" : "8", "Child" : ["27", "28", "29", "30"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_37_4",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "258", "EstimateLatencyMax" : "258",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "nxt", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_2", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_37_4", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter1", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter1", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_37_4_fu_102.mul_8ns_10ns_17_1_1_U24", "Parent" : "26"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_37_4_fu_102.sparsemux_7_2_24_1_1_U25", "Parent" : "26"},
	{"ID" : "29", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_37_4_fu_102.sparsemux_7_2_24_1_1_U26", "Parent" : "26"},
	{"ID" : "30", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_37_4_fu_102.flow_control_loop_pipe_sequential_init_U", "Parent" : "26"},
	{"ID" : "31", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110", "Parent" : "8", "Child" : ["32", "33", "34", "35", "36", "37", "38", "39", "40", "41"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65549", "EstimateLatencyMax" : "65549",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "stream_out", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_8", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_77_10_VITIS_LOOP_78_11", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "32", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.mul_9ns_11ns_19_1_1_U107", "Parent" : "31"},
	{"ID" : "33", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.urem_9ns_3ns_2_13_1_U108", "Parent" : "31"},
	{"ID" : "34", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.urem_9ns_3ns_2_13_1_U109", "Parent" : "31"},
	{"ID" : "35", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.mul_9ns_11ns_19_1_1_U110", "Parent" : "31"},
	{"ID" : "36", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.sparsemux_7_2_24_1_1_U111", "Parent" : "31"},
	{"ID" : "37", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.sparsemux_7_2_24_1_1_U112", "Parent" : "31"},
	{"ID" : "38", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.sparsemux_7_2_24_1_1_U113", "Parent" : "31"},
	{"ID" : "39", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.sparsemux_7_2_24_1_1_U114", "Parent" : "31"},
	{"ID" : "40", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.mac_muladd_8ns_7ns_8ns_13_4_1_U115", "Parent" : "31"},
	{"ID" : "41", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_77_10_VITIS_LOOP_78_11_fu_110.flow_control_loop_pipe_sequential_init_U", "Parent" : "31"},
	{"ID" : "42", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125", "Parent" : "8", "Child" : ["43", "44", "45", "46", "47"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_42_5",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "259", "EstimateLatencyMax" : "259",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "nxt", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_6", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_42_5", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter2", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter2", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "43", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125.mul_8ns_10ns_17_1_1_U33", "Parent" : "42"},
	{"ID" : "44", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125.mul_7ns_8ns_14_1_1_U34", "Parent" : "42"},
	{"ID" : "45", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125.sparsemux_7_2_24_1_1_U35", "Parent" : "42"},
	{"ID" : "46", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125.sparsemux_7_2_24_1_1_U36", "Parent" : "42"},
	{"ID" : "47", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_42_5_fu_125.flow_control_loop_pipe_sequential_init_U", "Parent" : "42"},
	{"ID" : "48", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133", "Parent" : "8", "Child" : ["49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "64532", "EstimateLatencyMax" : "64532",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "nxt", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_1", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_2", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_3", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_4", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_5", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_6", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_7", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur_8", "Type" : "Memory", "Direction" : "I"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_49_6_VITIS_LOOP_50_7", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter15", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter15", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "49", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_39s_24ns_63_1_1_U42", "Parent" : "48"},
	{"ID" : "50", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_39s_26ns_65_1_1_U43", "Parent" : "48"},
	{"ID" : "51", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U44", "Parent" : "48"},
	{"ID" : "52", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U45", "Parent" : "48"},
	{"ID" : "53", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U46", "Parent" : "48"},
	{"ID" : "54", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U47", "Parent" : "48"},
	{"ID" : "55", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U48", "Parent" : "48"},
	{"ID" : "56", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U49", "Parent" : "48"},
	{"ID" : "57", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U50", "Parent" : "48"},
	{"ID" : "58", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U51", "Parent" : "48"},
	{"ID" : "59", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U52", "Parent" : "48"},
	{"ID" : "60", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.urem_8ns_3ns_2_12_1_U53", "Parent" : "48"},
	{"ID" : "61", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U54", "Parent" : "48"},
	{"ID" : "62", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.urem_8ns_3ns_2_12_1_U55", "Parent" : "48"},
	{"ID" : "63", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U56", "Parent" : "48"},
	{"ID" : "64", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U57", "Parent" : "48"},
	{"ID" : "65", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U58", "Parent" : "48"},
	{"ID" : "66", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_7ns_8ns_13_1_1_U59", "Parent" : "48"},
	{"ID" : "67", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_7ns_8ns_13_1_1_U60", "Parent" : "48"},
	{"ID" : "68", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_7ns_8ns_13_1_1_U61", "Parent" : "48"},
	{"ID" : "69", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U62", "Parent" : "48"},
	{"ID" : "70", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.mul_8ns_10ns_17_1_1_U63", "Parent" : "48"},
	{"ID" : "71", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U64", "Parent" : "48"},
	{"ID" : "72", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U65", "Parent" : "48"},
	{"ID" : "73", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U66", "Parent" : "48"},
	{"ID" : "74", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U67", "Parent" : "48"},
	{"ID" : "75", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U68", "Parent" : "48"},
	{"ID" : "76", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U69", "Parent" : "48"},
	{"ID" : "77", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U70", "Parent" : "48"},
	{"ID" : "78", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_x_U71", "Parent" : "48"},
	{"ID" : "79", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U72", "Parent" : "48"},
	{"ID" : "80", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U73", "Parent" : "48"},
	{"ID" : "81", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U74", "Parent" : "48"},
	{"ID" : "82", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.sparsemux_7_2_24_1_1_U75", "Parent" : "48"},
	{"ID" : "83", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_49_6_VITIS_LOOP_50_7_fu_133.flow_control_loop_pipe_sequential_init_U", "Parent" : "48"},
	{"ID" : "84", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147", "Parent" : "8", "Child" : ["85", "86", "87", "88", "89", "90"],
		"CDFG" : "compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "0", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65549", "EstimateLatencyMax" : "65549",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "0",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "nxt", "Type" : "Memory", "Direction" : "I"},
			{"Name" : "cur", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_1", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_2", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_3", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_4", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_5", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_6", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_7", "Type" : "Memory", "Direction" : "O"},
			{"Name" : "cur_8", "Type" : "Memory", "Direction" : "O"}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_68_8_VITIS_LOOP_69_9", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter13", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter13", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "0"}}]},
	{"ID" : "85", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.mul_9ns_11ns_19_1_1_U92", "Parent" : "84"},
	{"ID" : "86", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.urem_9ns_3ns_2_13_1_U93", "Parent" : "84"},
	{"ID" : "87", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.urem_9ns_3ns_2_13_1_U94", "Parent" : "84"},
	{"ID" : "88", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.mul_9ns_11ns_19_1_1_U95", "Parent" : "84"},
	{"ID" : "89", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.mac_muladd_8ns_7ns_8ns_13_4_1_U96", "Parent" : "84"},
	{"ID" : "90", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_68_8_VITIS_LOOP_69_9_fu_147.flow_control_loop_pipe_sequential_init_U", "Parent" : "84"},
	{"ID" : "91", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_output_U0", "Parent" : "0", "Child" : ["92"],
		"CDFG" : "write_output",
		"Protocol" : "ap_ctrl_hs",
		"ControlExist" : "1", "ap_start" : "1", "ap_ready" : "1", "ap_done" : "1", "ap_continue" : "1", "ap_idle" : "1", "real_start" : "0",
		"Pipeline" : "None", "UnalignedPipeline" : "0", "RewindPipeline" : "0", "ProcessNetwork" : "0",
		"II" : "0",
		"VariableLatency" : "1", "ExactLatency" : "-1", "EstimateLatencyMin" : "65545", "EstimateLatencyMax" : "65545",
		"Combinational" : "0",
		"Datapath" : "0",
		"ClockEnable" : "0",
		"HasSubDataflow" : "0",
		"InDataflowNetwork" : "1",
		"HasNonBlockingOperation" : "0",
		"IsBlackBox" : "0",
		"Port" : [
			{"Name" : "stream_in", "Type" : "Memory", "Direction" : "I", "DependentProc" : ["8"], "DependentChan" : "2"},
			{"Name" : "A_out", "Type" : "MAXI", "Direction" : "O",
				"BlockSignal" : [
					{"Name" : "A_out_blk_n_AW", "Type" : "RtlSignal"},
					{"Name" : "A_out_blk_n_W", "Type" : "RtlSignal"},
					{"Name" : "A_out_blk_n_B", "Type" : "RtlSignal"}]},
			{"Name" : "A_out1", "Type" : "Fifo", "Direction" : "I", "DependentProc" : ["6"], "DependentChan" : "93", "DependentChanDepth" : "4", "DependentChanType" : "2",
				"BlockSignal" : [
					{"Name" : "A_out1_blk_n", "Type" : "RtlSignal"}]}],
		"Loop" : [
			{"Name" : "VITIS_LOOP_89_1_VITIS_LOOP_90_2", "PipelineType" : "UPC",
				"LoopDec" : {"FSMBitwidth" : "1", "FirstState" : "ap_ST_fsm_pp0_stage0", "FirstStateIter" : "ap_enable_reg_pp0_iter0", "FirstStateBlock" : "ap_block_pp0_stage0_subdone", "LastState" : "ap_ST_fsm_pp0_stage0", "LastStateIter" : "ap_enable_reg_pp0_iter8", "LastStateBlock" : "ap_block_pp0_stage0_subdone", "QuitState" : "ap_ST_fsm_pp0_stage0", "QuitStateIter" : "ap_enable_reg_pp0_iter8", "QuitStateBlock" : "ap_block_pp0_stage0_subdone", "OneDepthLoop" : "0", "has_ap_ctrl" : "1", "has_continue" : "1"}}]},
	{"ID" : "92", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_output_U0.flow_control_loop_pipe_U", "Parent" : "91"},
	{"ID" : "93", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_r_c_U", "Parent" : "0"}]}
