

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_in_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_U0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.buffer_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.buffer_1_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.buffer_2_U"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.buffer_3_U"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2_fu_94"},
	{"ID" : "12", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_33_1_VITIS_LOOP_34_2_fu_94.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_50_4_fu_108"},
	{"ID" : "14", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_50_4_fu_108.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_130_9_VITIS_LOOP_131_10_fu_118"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_130_9_VITIS_LOOP_131_10_fu_118.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_55_5_fu_128"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_55_5_fu_128.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.line_buf_1_U"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.line_buf_U"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.mul_39s_24ns_63_1_1_U23"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.mul_39s_26ns_65_1_1_U24"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.add_41s_41s_41_1_1_U25"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.add_42s_42s_42_1_1_U26"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_62_6_VITIS_LOOP_63_7_fu_138.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_output_U0"},
	{"ID" : "28", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_output_U0.flow_control_loop_pipe_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_r_c_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_initial_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_final_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_output_U0_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U"}]}
set DependenceCheckSize 0
