

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_in_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_U0"},
	{"ID" : "6", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.read_input_U0.flow_control_loop_pipe_U"},
	{"ID" : "7", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.cur_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.nxt_U"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_35_1_VITIS_LOOP_36_2_fu_82"},
	{"ID" : "11", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_35_1_VITIS_LOOP_36_2_fu_82.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_46_4_fu_90"},
	{"ID" : "13", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_46_4_fu_90.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_115_11_VITIS_LOOP_116_12_fu_96"},
	{"ID" : "15", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_115_11_VITIS_LOOP_116_12_fu_96.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "16", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_51_5_fu_103"},
	{"ID" : "17", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_51_5_fu_103.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "18", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109"},
	{"ID" : "19", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109.line_buf_1_U"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109.line_buf_U"},
	{"ID" : "21", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109.mul_39s_24ns_63_1_1_U12"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109.mul_39s_26ns_65_1_1_U13"},
	{"ID" : "23", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_58_6_VITIS_LOOP_59_7_fu_109.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "24", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_106_9_VITIS_LOOP_107_10_fu_124"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_106_9_VITIS_LOOP_107_10_fu_124.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "26", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_output_U0"},
	{"ID" : "27", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_r_c_U"},
	{"ID" : "28", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_initial_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_final_U"},
	{"ID" : "30", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_output_U0_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U"}]}
set DependenceCheckSize 0
