

set RtlHierarchyInfo {[
	{"ID" : "0", "Level" : "0", "Path" : "`AUTOTB_DUT_INST"},
	{"ID" : "1", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.control_s_axi_U"},
	{"ID" : "2", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_in_m_axi_U"},
	{"ID" : "3", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_m_axi_U"},
	{"ID" : "4", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.entry_proc_U0"},
	{"ID" : "5", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.read_input_U0"},
	{"ID" : "6", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.compute_U0"},
	{"ID" : "7", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferA_U"},
	{"ID" : "8", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferA_1_U"},
	{"ID" : "9", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferA_2_U"},
	{"ID" : "10", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferA_3_U"},
	{"ID" : "11", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferB_U"},
	{"ID" : "12", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferB_1_U"},
	{"ID" : "13", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferB_2_U"},
	{"ID" : "14", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.bufferB_3_U"},
	{"ID" : "15", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_34_1_VITIS_LOOP_35_2_fu_104"},
	{"ID" : "16", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_34_1_VITIS_LOOP_35_2_fu_104.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "17", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_50_4_fu_118"},
	{"ID" : "18", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_50_4_fu_118.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "19", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_133_9_VITIS_LOOP_134_10_fu_131"},
	{"ID" : "20", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_133_9_VITIS_LOOP_134_10_fu_131.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "21", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_60_5_fu_141"},
	{"ID" : "22", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_60_5_fu_141.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "23", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154"},
	{"ID" : "24", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154.line_buf_1_U"},
	{"ID" : "25", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154.line_buf_U"},
	{"ID" : "26", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154.mul_39s_24ns_63_1_1_U29"},
	{"ID" : "27", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154.mul_39s_26ns_65_1_1_U30"},
	{"ID" : "28", "Level" : "3", "Path" : "`AUTOTB_DUT_INST.compute_U0.grp_compute_Pipeline_VITIS_LOOP_72_6_VITIS_LOOP_73_7_fu_154.flow_control_loop_pipe_sequential_init_U"},
	{"ID" : "29", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.write_output_U0"},
	{"ID" : "30", "Level" : "2", "Path" : "`AUTOTB_DUT_INST.write_output_U0.flow_control_loop_pipe_U"},
	{"ID" : "31", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.A_out_r_c_U"},
	{"ID" : "32", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_initial_U"},
	{"ID" : "33", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.grid_final_U"},
	{"ID" : "34", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_write_output_U0_U"},
	{"ID" : "35", "Level" : "1", "Path" : "`AUTOTB_DUT_INST.start_for_compute_U0_U"}]}
set DependenceCheckSize 0
